// Code generated by go-bindata. DO NOT EDIT.

// Code generated for package migration by go-bindata DO NOT EDIT. (@generated)
// sources:
// scripts/0001_init.up.sql
// scripts/0002_add_table_user_profile.up.sql
// scripts/0003_add_table_session.up.sql
// scripts/0004_add_table_user_profile_session_rel.up.sql
// scripts/0005_add_table_race.up.sql
// scripts/0006_add_table_session_user_profile_race.up.sql
// scripts/0007_add_table_invitation.up.sql
package migration

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// Mode return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __0001_initUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func _0001_initUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__0001_initUpSql,
		"0001_init.up.sql",
	)
}

func _0001_initUpSql() (*asset, error) {
	bytes, err := _0001_initUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0001_init.up.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __0002_add_table_user_profileUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\x91\xc1\x6e\xdb\x30\x10\x44\xef\xfa\x8a\xb9\x39\x06\x14\xff\x40\x2f\x65\x52\x16\x55\xab\xca\xa9\x22\x05\xc8\x29\x58\x8b\x6b\x8b\x30\x45\x1a\x5c\x3a\x81\xff\xbe\x90\x64\xc7\x2d\x7c\x22\x81\x79\xb3\xd8\x9d\x79\xac\xb5\x6a\x34\x1a\xf5\x50\x6a\x1c\x85\xe3\xdb\x21\x86\xad\x75\x8c\xbb\x0c\x00\xac\xc1\x8b\xaa\x1f\x7f\xa8\x1a\x4f\x75\xf1\x5b\xd5\xaf\xf8\xa5\x5f\xf3\x49\xe3\x81\xac\xfb\x94\xab\x75\x83\xaa\x2d\xcb\x59\xb3\xf2\x46\x5d\xb2\xef\x8c\x87\xf5\xba\xd4\xaa\xba\xd5\x07\xf2\xb4\xe3\x78\x03\xe0\x9b\xfe\xae\xda\xb2\xc1\x96\x9c\xf0\x8c\x7b\xdb\xed\x3d\x0d\x8c\x77\x8a\x5d\x4f\xf1\x0a\xb7\x55\xf1\xa7\xd5\x33\x45\x07\xbb\xe7\xd3\x65\xa3\x6c\xf9\x25\xcb\xee\xef\x61\xbd\x70\x4c\x20\xc8\x49\x12\x0f\xd3\x95\x48\x3d\x25\x7c\x58\xe7\xb0\x61\x84\x0f\xcf\x11\x61\x8b\xd4\xf3\xe8\xd8\x84\x84\x48\x1d\xcb\x0a\x45\x42\x4f\x02\x1f\x40\x66\xb0\x1e\xd1\xee\xfa\x24\x20\x6f\xe0\x43\x82\x7a\x2a\xb0\xe7\xd3\x6a\x74\x35\xbd\x95\x79\xf8\x65\xee\x86\x71\x14\xda\x38\x46\x0a\x70\x61\x67\xfd\x0a\x3f\x8f\x92\x46\xca\x80\x04\x34\xfa\x0e\x8e\x3a\xee\x83\x33\x1c\x61\x3d\x84\x45\x6c\xf0\x32\x7a\xc8\x98\x71\x19\x59\x65\x45\xf5\xac\xeb\x06\x45\xd5\xac\xff\xab\x69\xba\xfb\xce\x9a\x7c\x6e\x23\xbf\x06\x9f\xff\x93\x71\xfe\x19\x60\x7e\x0e\x69\x99\xbd\xa8\xb2\xd5\xcf\xb3\x7f\x31\x47\xb3\xc8\x71\xfe\x7d\x9d\xa6\x2d\xf2\x73\x07\x97\xe7\xca\xf9\xa3\x73\xcb\x2c\xfb\x1b\x00\x00\xff\xff\x74\x39\x8b\x4d\x3f\x02\x00\x00")

func _0002_add_table_user_profileUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__0002_add_table_user_profileUpSql,
		"0002_add_table_user_profile.up.sql",
	)
}

func _0002_add_table_user_profileUpSql() (*asset, error) {
	bytes, err := _0002_add_table_user_profileUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0002_add_table_user_profile.up.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __0003_add_table_sessionUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x3c\xc9\xc1\x0a\xc2\x30\x0c\x06\xe0\x7b\x9f\xe2\x3f\x2a\xf8\x12\xd9\x8c\x28\xc6\x56\x42\x26\xec\x58\x30\x42\x41\xa7\x18\xf1\xf9\x05\x07\x3b\x7f\xbd\x32\x19\xc3\xa8\x13\x46\x78\x44\x7b\x4e\x58\x25\x00\x68\x57\x5c\x48\xfb\x3d\x29\xce\x7a\x38\x91\x8e\x38\xf2\xb8\xf9\xdb\x54\x1f\xbe\x68\x2e\x86\x3c\x88\xcc\xf4\x7a\xb7\x6f\xfd\x38\xba\x52\x84\x29\x2f\x8a\x2d\xef\x68\x10\xc3\xad\xde\xc3\xd3\x3a\xfd\x02\x00\x00\xff\xff\x92\x20\x95\xe9\x7b\x00\x00\x00")

func _0003_add_table_sessionUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__0003_add_table_sessionUpSql,
		"0003_add_table_session.up.sql",
	)
}

func _0003_add_table_sessionUpSql() (*asset, error) {
	bytes, err := _0003_add_table_sessionUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0003_add_table_session.up.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __0004_add_table_user_profile_session_relUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8f\xc1\x4e\x84\x30\x10\x86\xef\x3c\xc5\x7f\x84\x64\xdf\xc0\xd3\x6c\x19\x74\x63\x6d\xcd\x6c\x31\xe1\xd4\x90\x58\x4c\x13\x04\xd3\xc6\xf7\x37\x8a\x1a\xd8\xc0\x75\xfe\x6f\xbe\x7f\x46\x09\x93\x63\x38\x3a\x6b\xc6\x67\x0e\xc9\x7f\xa4\x79\x88\x63\xf0\x39\xe4\x1c\xe7\xc9\xa7\x30\xa2\x2c\x00\x6c\xe3\xf8\x8a\x17\x12\xf5\x40\x02\x63\x1d\x4c\xab\xf5\xe9\x87\xfa\xdb\x3b\x04\x62\xf6\xef\xfd\xd4\xbf\x85\x84\xb3\xb5\x9a\xc9\xfc\x03\xa8\xb9\xa1\x56\x3b\x0c\xfd\x98\xc3\x82\x3f\xcb\xe5\x89\xa4\xc3\x23\x77\x28\x6f\x4e\x38\xad\xda\xaa\x05\x6f\xac\xf0\xe5\xde\xec\xe2\x15\x84\x1b\x16\x36\x8a\xaf\x9b\x6f\x50\x7e\x87\xd6\xa0\x66\xcd\x8e\xa1\xe8\xaa\xa8\xe6\x1d\xe3\xaa\x6f\x2d\xfb\x1d\x1f\x78\x8a\xea\xae\xf8\x0a\x00\x00\xff\xff\x74\xb0\x79\x95\x69\x01\x00\x00")

func _0004_add_table_user_profile_session_relUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__0004_add_table_user_profile_session_relUpSql,
		"0004_add_table_user_profile_session_rel.up.sql",
	)
}

func _0004_add_table_user_profile_session_relUpSql() (*asset, error) {
	bytes, err := _0004_add_table_user_profile_session_relUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0004_add_table_user_profile_session_rel.up.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __0005_add_table_raceUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\x91\x4d\x6b\xe3\x30\x10\x86\xef\xfe\x15\x2f\xbd\x24\x01\x77\xd9\xef\x4b\x4f\x5a\x57\xdd\x0d\xeb\x3a\x8b\xe2\x16\x7a\x2a\x72\xa5\x34\x02\x59\x53\x24\x99\xe2\x7f\xbf\xc8\xc9\x1a\xfb\x10\x58\xdf\x66\x3c\x0f\xcf\x8c\x5e\x17\x82\xb3\x9a\xa3\x66\x3f\x4a\x0e\x2f\x5f\x34\xd6\x19\x00\x18\x85\x47\x26\x8a\x5f\x4c\xe0\x8f\xd8\xde\x33\xf1\x84\xdf\xfc\x29\x1f\x66\x4e\xb6\xfa\xf9\xcd\x76\x5e\xda\x11\xaa\x76\x35\xaa\x87\xb2\x9c\x10\xc1\xb8\xd7\xce\x4a\x7f\x81\xe9\x82\xf6\xcf\x93\x35\xf3\xa9\x92\x51\x5e\x18\xdd\xed\x04\xdf\xfe\xac\xd2\x3d\x58\x9f\x2d\x1b\x08\x7e\xc7\x05\xaf\x0a\xbe\x3f\x99\xdf\x3c\x1d\x8c\xd5\x58\xa7\xe1\xae\xc2\x2d\x2f\x79\xcd\x51\xb0\x7d\xc1\x6e\x79\xb6\xb9\xc9\xb2\xeb\x6b\xc4\x23\x05\x0d\x09\xaf\xa1\xf4\x41\x76\x36\x0e\x21\x04\x1c\xc8\xa3\xa1\x18\x3e\xa0\x3e\xea\x1e\xd2\x6b\xd0\xbb\xd3\x0a\x4d\x0f\x89\xab\xd0\x87\xa8\xdb\xab\x61\x55\xf2\x48\xa7\xf0\x6e\xac\x45\xa3\xd3\x37\x05\x72\xb6\x4f\x6c\xd0\x21\x18\x72\x90\xaa\x35\x2e\x20\x12\xa4\x52\x83\x39\xd5\xf1\xa8\x8d\xc7\xab\x6c\x75\xc8\xb6\xd5\x9e\x8b\x1a\xdb\xaa\xde\x9d\x7f\x84\x51\xf9\x34\xeb\x7c\x1e\x6b\xfe\x2f\xc1\x7c\x08\x6b\x93\x3d\xb2\xf2\x81\xef\x87\x88\xd6\xab\x8f\xab\x1c\x2b\x2f\x9d\xa2\x76\x5e\x9d\x2e\x4f\x95\xa3\x53\xca\xe9\xa9\x32\x9d\x34\xac\x5d\x6d\xf2\xb3\xe2\x53\x82\x04\x35\x14\xc9\xa8\x30\x6d\x96\x79\x3e\x27\xa8\xee\xbc\x53\x9e\x9c\x0e\xb3\x6e\x99\xe9\x4b\x82\x58\x17\xa9\x35\xd1\x93\x0b\xf3\x76\x99\xeb\xeb\xe9\x41\x91\xa2\xb1\x36\x4c\x9b\x65\x9e\x6f\x09\x2a\xfa\x46\xfb\xf1\xa4\xb1\x5b\x66\xfa\x9e\xa0\xfb\x17\xe3\xa2\x19\xab\xff\x0c\xe8\x26\xcb\xfe\x06\x00\x00\xff\xff\x14\x35\xb0\x77\xc9\x03\x00\x00")

func _0005_add_table_raceUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__0005_add_table_raceUpSql,
		"0005_add_table_race.up.sql",
	)
}

func _0005_add_table_raceUpSql() (*asset, error) {
	bytes, err := _0005_add_table_raceUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0005_add_table_race.up.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __0006_add_table_session_user_profile_raceUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x92\x4f\x4f\xf2\x40\x10\xc6\xef\x7c\x8a\x39\xd2\x84\xbc\x09\x09\x9c\x5e\x38\xac\xcb\xa0\xc4\xba\x35\xcb\x62\xc2\x69\xd2\xc2\x20\x8d\x1b\x16\x77\x8b\xc6\x6f\x6f\xa0\x48\x6d\x11\xc2\x75\x9e\x67\x7e\xf3\x57\x6a\x14\x06\xc1\x88\xbb\x18\x21\x70\x08\xb9\xdb\xd0\x2e\xb0\xa7\xad\x77\xab\xdc\x32\xf9\x74\xc1\xd0\x6e\x01\xc0\x49\xcf\x97\xf0\x22\xb4\x7c\x10\x1a\x54\x62\x40\xcd\xe2\xb8\x73\x30\xd4\x12\x2f\xba\xf6\xc4\xcb\xea\xd6\xa6\x5f\xec\xc9\xf9\x25\x7b\xc8\x37\x05\xbf\xb2\x6f\x58\xf2\x40\x99\x2b\x20\x73\xce\x72\xba\x39\x89\x30\xc2\xb1\x98\xc5\x06\x56\xa9\x0d\x5c\x5a\x33\x57\x90\xe5\x0f\xb6\x3f\xa8\x32\xfc\xac\x27\x4f\x42\xcf\xe1\x11\xe7\xd0\xae\xc6\xea\x34\x27\x88\x4a\xfb\x38\xd1\x38\xb9\x57\xa5\xbd\x69\x01\x8d\x63\xd4\xa8\x24\x4e\x6b\xe9\xd0\xde\x8b\x89\x82\x11\xc6\x68\x10\xa4\x98\x4a\x31\xc2\x3f\x88\x55\x03\x35\xd8\x31\x7c\x3b\xe7\xb8\xd8\x1a\xa4\x3c\xdf\x15\x82\x4c\xd4\xd4\x68\x31\x51\xa6\x5a\x16\x85\xb5\xdb\xd9\x25\x65\x4c\xd6\x7d\x1e\xae\x41\xfc\xbe\x4b\x2d\x15\x8e\x7a\x87\x34\x80\xc5\x9a\x17\x6f\x55\xf3\x67\x4f\xf3\xaf\xda\xfd\x60\x08\xbd\xe8\xac\xdc\xef\x4b\x5f\xad\xd8\xed\xdf\x5a\xb2\xf6\x3c\x83\x21\x74\xfb\x51\x2b\xfa\xdf\xfa\x0e\x00\x00\xff\xff\xcc\x22\x42\x39\xe6\x02\x00\x00")

func _0006_add_table_session_user_profile_raceUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__0006_add_table_session_user_profile_raceUpSql,
		"0006_add_table_session_user_profile_race.up.sql",
	)
}

func _0006_add_table_session_user_profile_raceUpSql() (*asset, error) {
	bytes, err := _0006_add_table_session_user_profile_raceUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0006_add_table_session_user_profile_race.up.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __0007_add_table_invitationUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x41\xcb\x82\x40\x18\x84\xef\xfe\x8a\x39\xae\xe0\x3f\xf8\x4e\xfb\xad\xaf\x25\x6d\x6b\xbd\xae\x81\x27\x09\x32\x58\x08\x0d\xd7\xfa\xfd\x61\x06\xa6\xe4\x75\xe6\x99\x87\x51\x4c\xd2\x12\xac\xfc\xd7\x04\xd7\x3c\x5d\x7f\xee\x5d\xdb\x40\x04\x00\xe0\x2e\x38\x49\x56\x5b\xc9\x38\x70\xba\x97\x5c\x62\x47\x65\xf4\xee\x7c\xed\xbd\x6b\x9b\xea\x8b\x31\x99\x85\x29\xb4\x1e\x81\x87\xaf\xbb\xea\xde\xb5\x57\x77\xab\xd7\xa9\xc2\xa4\xc7\x82\x20\x26\x5d\xb4\x5c\x86\x23\x99\x64\x4c\xe9\xc6\x0c\x0f\x20\x96\x08\x98\x12\x62\x32\x8a\xf2\xd9\x1c\x62\x28\x33\x83\x98\x34\x59\x82\x92\xb9\x92\x31\xfd\x30\x4e\x07\x66\xb2\x4f\xbc\xe2\x09\xc2\xbf\xe0\x15\x00\x00\xff\xff\x97\x2f\x8d\xa7\x43\x01\x00\x00")

func _0007_add_table_invitationUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__0007_add_table_invitationUpSql,
		"0007_add_table_invitation.up.sql",
	)
}

func _0007_add_table_invitationUpSql() (*asset, error) {
	bytes, err := _0007_add_table_invitationUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0007_add_table_invitation.up.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"0001_init.up.sql":                                _0001_initUpSql,
	"0002_add_table_user_profile.up.sql":              _0002_add_table_user_profileUpSql,
	"0003_add_table_session.up.sql":                   _0003_add_table_sessionUpSql,
	"0004_add_table_user_profile_session_rel.up.sql":  _0004_add_table_user_profile_session_relUpSql,
	"0005_add_table_race.up.sql":                      _0005_add_table_raceUpSql,
	"0006_add_table_session_user_profile_race.up.sql": _0006_add_table_session_user_profile_raceUpSql,
	"0007_add_table_invitation.up.sql":                _0007_add_table_invitationUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"0001_init.up.sql":                                &bintree{_0001_initUpSql, map[string]*bintree{}},
	"0002_add_table_user_profile.up.sql":              &bintree{_0002_add_table_user_profileUpSql, map[string]*bintree{}},
	"0003_add_table_session.up.sql":                   &bintree{_0003_add_table_sessionUpSql, map[string]*bintree{}},
	"0004_add_table_user_profile_session_rel.up.sql":  &bintree{_0004_add_table_user_profile_session_relUpSql, map[string]*bintree{}},
	"0005_add_table_race.up.sql":                      &bintree{_0005_add_table_raceUpSql, map[string]*bintree{}},
	"0006_add_table_session_user_profile_race.up.sql": &bintree{_0006_add_table_session_user_profile_raceUpSql, map[string]*bintree{}},
	"0007_add_table_invitation.up.sql":                &bintree{_0007_add_table_invitationUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
