version: "2"

run:
  timeout: 2m

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/neper-stars/neper)

linters:
  default: none
  enable:
    # enable by default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # includes gosimple
    - unused

    # extra linters
    - asciicheck  # Simple linter to check that your code does not contain non-ASCII identifiers
    - bidichk  # Checks for dangerous unicode character sequences
    - bodyclose  # checks whether HTTP response body is closed successfully
    - contextcheck  # check the function whether use a non-inherited context
    - dogsled  # Checks assignments with too many blank identifiers (e.g. x, , , _, := f())
    - durationcheck  # check for two durations multiplied together
    - errchkjson  # Checks types passed to the json encoding functions
    - errorlint  # errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
    - gocritic  # Provides diagnostics that check for bugs, performance and style issues.
    - gosec  # Inspects source code for security problems
    - misspell  # Finds commonly misspelled English words in comments
    - revive  # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
    - thelper  # thelper detects golang test helpers without t.Helper() call and checks the consistency of test helpers
    - unconvert  # Remove unnecessary type conversions
    - whitespace  # Tool for detection of leading and trailing whitespace

  settings:
    varnamelen:
      ignore-names:
        - db
        - msg
      ignore-decls:
        - t testing.T
        - i int

  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "SA5008"  # duplicate struct tag
      - linters:
          - revive
        text: "unused-parameter:"
      - linters:
          - revive
        text: "if-return:"
      - linters:
          - revive
        text: "empty-block:"
      - path: '(.+)_test\.go'
        linters:
          - bodyclose
