services:
  postgres:
    image: postgres:16
    container_name: neper-postgres
    environment:
      POSTGRES_USER: neper
      POSTGRES_PASSWORD: neper
      POSTGRES_DB: neper
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neper"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - neper-net

  neper:
    #build:
    #  context: .
    #  dockerfile: ./docker/Dockerfile
    image: registry.figaro.home.arpa:5001/gaming/starshosting/neper:latest
    container_name: neper-app
    hostname: neper-app
    depends_on:
      postgres:
        condition: service_healthy # service_healthy, service_started
    environment:
      NEPER_UID: 1000
      NEPER_GID: 1000
      NEPER_DB_DSN: "postgres://neper:neper@neper-postgres:5432/neper?sslmode=disable"
      NEPER_LOG_FORMAT: "pretty"
      NEPER_LOG_LEVEL: "debug"
      NEPER_SERVE_SCHEME: "http"
      NEPER_SERVE_HOST: "0.0.0.0"
      NEPER_SERVE_PORT: "33670"
      NEPER_SERVE_STARS_EXECUTABLE_DIR: "~/stars"
      NEPER_SERVE_STARS_SAVE_DIR: "~/saves"
      NEPER_SERVE_WINE_PREFIX: "~/wine"
      NEPER_SERVE_WINE_COMMANDS_TIMEOUT: "20"
      # use your own NKey here, see command: generate-nkey in docker-compose.yml
      NEPER_SERVE_NATS_CLIENT_NKEY:
      # use your own token secret here, see command: generate-token-secret in docker-compose.yml
      NEPER_SERVE_TOKEN_SECRET:
      NEPER_SERVE_REGISTRATION_ENABLED: false
      # set this to true in order to be able to access the stars files and debug some issues
      # in production you should not need this and can safely keep this option to false
      # WARNING: setting this to true will rapidely clutter your disk with a lot of session directories
      # and files that YOU will need to cleanup manually.
      NEPER_SERVE_PRESERVE_SAVE_FILES: false
      # set this to true in order to systematically remove passwords from race files
      # WARNING, ATM this will not remove change password orders in the order files
      # so a user can still protect its turn files
      NEPER_SERVE_STRIP_RACE_PASSWORDS: false
      # if set to true, the server will attempt to fix race files that are corrupted
      # this happens when editing a race file with different "machines" or wine prefixes
      # the checksum gets corrupted because only part or the file is rewritten
      # the server can recompute a proper checksum for the file
      NEPER_SERVE_FIX_RACE_FILES: false
    volumes:
      - "./neper_data/etc:/etc/neper"
      - "./neper_data:/home/neper"
    ports:
      - "33670:33670"
    networks:
      - neper-net
    # enable this when you want to create the initial user (which is a manager)
    # command: create-user admin --manager --email=admin@mydomain.com
    # enable this to get a secret for token encryption to put in NEPER_SERVE_NATS_CLIENT_NKEY above
    # command: generate-token-secret
    # enable this to get an NKey to put in NEPER_SERVE_NATS_CLIENT_NKEY above
    # command: generate-nkey

networks:
  neper-net:
    driver: bridge
