apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:

- path: dependencies
  contents:

  - path: go-orusapi
    hg:
      url: https://orus.io/orus-io/go-orusapi
      ref: d543a6b4538e

  - path: json-schema-generate
    git:
      url: https://github.com/orus-io/json-schema-generate
      ref: cc402b93ccf6619eef48ac33c0dcbbcfd2cc96a7
