// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// AuthenticateOKCode is the HTTP code returned for type AuthenticateOK
const AuthenticateOKCode int = 200

/*AuthenticateOK A Json Web Token with a 5 minutes validity

swagger:response authenticateOK
*/
type AuthenticateOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAuthenticateOK creates AuthenticateOK with default headers values
func NewAuthenticateOK() *AuthenticateOK {

	return &AuthenticateOK{}
}

// WithPayload adds the payload to the authenticate o k response
func (o *AuthenticateOK) WithPayload(payload string) *AuthenticateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authenticate o k response
func (o *AuthenticateOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthenticateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// AuthenticateUnauthorizedCode is the HTTP code returned for type AuthenticateUnauthorized
const AuthenticateUnauthorizedCode int = 401

/*AuthenticateUnauthorized Invalid credentials

swagger:response authenticateUnauthorized
*/
type AuthenticateUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAuthenticateUnauthorized creates AuthenticateUnauthorized with default headers values
func NewAuthenticateUnauthorized() *AuthenticateUnauthorized {

	return &AuthenticateUnauthorized{}
}

// WithPayload adds the payload to the authenticate unauthorized response
func (o *AuthenticateUnauthorized) WithPayload(payload *models.Error) *AuthenticateUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authenticate unauthorized response
func (o *AuthenticateUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthenticateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AuthenticateDefault generic error response

swagger:response authenticateDefault
*/
type AuthenticateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAuthenticateDefault creates AuthenticateDefault with default headers values
func NewAuthenticateDefault(code int) *AuthenticateDefault {
	if code <= 0 {
		code = 500
	}

	return &AuthenticateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the authenticate default response
func (o *AuthenticateDefault) WithStatusCode(code int) *AuthenticateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the authenticate default response
func (o *AuthenticateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the authenticate default response
func (o *AuthenticateDefault) WithPayload(payload *models.Error) *AuthenticateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the authenticate default response
func (o *AuthenticateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthenticateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
