// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// HistoricBackupOKCode is the HTTP code returned for type HistoricBackupOK
const HistoricBackupOKCode int = 200

/*HistoricBackupOK ZIP file containing all historic game files

swagger:response historicBackupOK
*/
type HistoricBackupOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewHistoricBackupOK creates HistoricBackupOK with default headers values
func NewHistoricBackupOK() *HistoricBackupOK {

	return &HistoricBackupOK{}
}

// WithPayload adds the payload to the historic backup o k response
func (o *HistoricBackupOK) WithPayload(payload io.ReadCloser) *HistoricBackupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the historic backup o k response
func (o *HistoricBackupOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HistoricBackupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// HistoricBackupUnauthorizedCode is the HTTP code returned for type HistoricBackupUnauthorized
const HistoricBackupUnauthorizedCode int = 401

/*HistoricBackupUnauthorized Invalid credentials

swagger:response historicBackupUnauthorized
*/
type HistoricBackupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHistoricBackupUnauthorized creates HistoricBackupUnauthorized with default headers values
func NewHistoricBackupUnauthorized() *HistoricBackupUnauthorized {

	return &HistoricBackupUnauthorized{}
}

// WithPayload adds the payload to the historic backup unauthorized response
func (o *HistoricBackupUnauthorized) WithPayload(payload *models.Error) *HistoricBackupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the historic backup unauthorized response
func (o *HistoricBackupUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HistoricBackupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HistoricBackupForbiddenCode is the HTTP code returned for type HistoricBackupForbidden
const HistoricBackupForbiddenCode int = 403

/*HistoricBackupForbidden Access forbidden

swagger:response historicBackupForbidden
*/
type HistoricBackupForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHistoricBackupForbidden creates HistoricBackupForbidden with default headers values
func NewHistoricBackupForbidden() *HistoricBackupForbidden {

	return &HistoricBackupForbidden{}
}

// WithPayload adds the payload to the historic backup forbidden response
func (o *HistoricBackupForbidden) WithPayload(payload *models.Error) *HistoricBackupForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the historic backup forbidden response
func (o *HistoricBackupForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HistoricBackupForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HistoricBackupNotFoundCode is the HTTP code returned for type HistoricBackupNotFound
const HistoricBackupNotFoundCode int = 404

/*HistoricBackupNotFound Resource not found

swagger:response historicBackupNotFound
*/
type HistoricBackupNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHistoricBackupNotFound creates HistoricBackupNotFound with default headers values
func NewHistoricBackupNotFound() *HistoricBackupNotFound {

	return &HistoricBackupNotFound{}
}

// WithPayload adds the payload to the historic backup not found response
func (o *HistoricBackupNotFound) WithPayload(payload *models.Error) *HistoricBackupNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the historic backup not found response
func (o *HistoricBackupNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HistoricBackupNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HistoricBackupPreconditionFailedCode is the HTTP code returned for type HistoricBackupPreconditionFailed
const HistoricBackupPreconditionFailedCode int = 412

/*HistoricBackupPreconditionFailed Session has not started yet (no turns generated)

swagger:response historicBackupPreconditionFailed
*/
type HistoricBackupPreconditionFailed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHistoricBackupPreconditionFailed creates HistoricBackupPreconditionFailed with default headers values
func NewHistoricBackupPreconditionFailed() *HistoricBackupPreconditionFailed {

	return &HistoricBackupPreconditionFailed{}
}

// WithPayload adds the payload to the historic backup precondition failed response
func (o *HistoricBackupPreconditionFailed) WithPayload(payload *models.Error) *HistoricBackupPreconditionFailed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the historic backup precondition failed response
func (o *HistoricBackupPreconditionFailed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HistoricBackupPreconditionFailed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(412)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*HistoricBackupDefault Generic error response

swagger:response historicBackupDefault
*/
type HistoricBackupDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHistoricBackupDefault creates HistoricBackupDefault with default headers values
func NewHistoricBackupDefault(code int) *HistoricBackupDefault {
	if code <= 0 {
		code = 500
	}

	return &HistoricBackupDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the historic backup default response
func (o *HistoricBackupDefault) WithStatusCode(code int) *HistoricBackupDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the historic backup default response
func (o *HistoricBackupDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the historic backup default response
func (o *HistoricBackupDefault) WithPayload(payload *models.Error) *HistoricBackupDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the historic backup default response
func (o *HistoricBackupDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HistoricBackupDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
