// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// InvitationAcceptHandlerFunc turns a function with the right signature into a invitation accept handler
type InvitationAcceptHandlerFunc func(InvitationAcceptParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn InvitationAcceptHandlerFunc) Handle(params InvitationAcceptParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// InvitationAcceptHandler interface for that can handle valid invitation accept params
type InvitationAcceptHandler interface {
	Handle(InvitationAcceptParams, *models.Principal) middleware.Responder
}

// NewInvitationAccept creates a new http.Handler for the invitation accept operation
func NewInvitationAccept(ctx *middleware.Context, handler InvitationAcceptHandler) *InvitationAccept {
	return &InvitationAccept{Context: ctx, Handler: handler}
}

/* InvitationAccept swagger:route PUT /v1/invitations/{invitation_id} invitationAccept

Join a session by accepting the invitation.
You will become member of the session that is referenced in
the invitation.
You can only accept an invitation that was addressed to you,
otherwise you will receive a 403 response.
In case of success you will receive the session details of the session
you just accepted to join.
Cannot join a session that has already started (returns 412).


*/
type InvitationAccept struct {
	Context *middleware.Context
	Handler InvitationAcceptHandler
}

func (o *InvitationAccept) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewInvitationAcceptParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
