// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// InvitationSentListHandlerFunc turns a function with the right signature into a invitation sent list handler
type InvitationSentListHandlerFunc func(InvitationSentListParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn InvitationSentListHandlerFunc) Handle(params InvitationSentListParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// InvitationSentListHandler interface for that can handle valid invitation sent list params
type InvitationSentListHandler interface {
	Handle(InvitationSentListParams, *models.Principal) middleware.Responder
}

// NewInvitationSentList creates a new http.Handler for the invitation sent list operation
func NewInvitationSentList(ctx *middleware.Context, handler InvitationSentListHandler) *InvitationSentList {
	return &InvitationSentList{Context: ctx, Handler: handler}
}

/* InvitationSentList swagger:route GET /v1/invitations/sent invitationSentList

List invitations sent by the current user

Returns all pending invitations where the current user is the inviter.


*/
type InvitationSentList struct {
	Context *middleware.Context
	Handler InvitationSentListHandler
}

func (o *InvitationSentList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewInvitationSentListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
