// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// InvitationDeclineHandlerFunc turns a function with the right signature into a invitation decline handler
type InvitationDeclineHandlerFunc func(InvitationDeclineParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn InvitationDeclineHandlerFunc) Handle(params InvitationDeclineParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// InvitationDeclineHandler interface for that can handle valid invitation decline params
type InvitationDeclineHandler interface {
	Handle(InvitationDeclineParams, *models.Principal) middleware.Responder
}

// NewInvitationDecline creates a new http.Handler for the invitation decline operation
func NewInvitationDecline(ctx *middleware.Context, handler InvitationDeclineHandler) *InvitationDecline {
	return &InvitationDecline{Context: ctx, Handler: handler}
}

/* InvitationDecline swagger:route DELETE /v1/invitations/{invitation_id} invitationDecline

Decline an invitation and remove it from the system.
You can only decline an invitation that was addressed to you,
otherwise you will receive a 403 response.


*/
type InvitationDecline struct {
	Context *middleware.Context
	Handler InvitationDeclineHandler
}

func (o *InvitationDecline) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewInvitationDeclineParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
