// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/neper-stars/neper/models"
)

// NewInvitationCreateParams creates a new InvitationCreateParams object
//
// There are no default values defined in the spec.
func NewInvitationCreateParams() InvitationCreateParams {

	return InvitationCreateParams{}
}

// InvitationCreateParams contains all the bound params for the invitation create operation
// typically these are obtained from a http.Request
//
// swagger:parameters invitationCreate
type InvitationCreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Invitation *models.Invitation
	/*
	  Required: true
	  In: path
	*/
	SessionID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewInvitationCreateParams() beforehand.
func (o *InvitationCreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Invitation
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("invitation", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Invitation = &body
			}
		}
	}

	rSessionID, rhkSessionID, _ := route.Params.GetOK("session_id")
	if err := o.bindSessionID(rSessionID, rhkSessionID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSessionID binds and validates parameter SessionID from path.
func (o *InvitationCreateParams) bindSessionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SessionID = raw

	return nil
}
