// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// InvitationCreateHandlerFunc turns a function with the right signature into a invitation create handler
type InvitationCreateHandlerFunc func(InvitationCreateParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn InvitationCreateHandlerFunc) Handle(params InvitationCreateParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// InvitationCreateHandler interface for that can handle valid invitation create params
type InvitationCreateHandler interface {
	Handle(InvitationCreateParams, *models.Principal) middleware.Responder
}

// NewInvitationCreate creates a new http.Handler for the invitation create operation
func NewInvitationCreate(ctx *middleware.Context, handler InvitationCreateHandler) *InvitationCreate {
	return &InvitationCreate{Context: ctx, Handler: handler}
}

/* InvitationCreate swagger:route POST /v1/sessions/{session_id}/invite invitationCreate

invite a player to a session. You can do this if you are the manager of this session.

invite a player to the session

*/
type InvitationCreate struct {
	Context *middleware.Context
	Handler InvitationCreateHandler
}

func (o *InvitationCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewInvitationCreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
