// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// InvitationSentListOKCode is the HTTP code returned for type InvitationSentListOK
const InvitationSentListOKCode int = 200

/*InvitationSentListOK the list of invitations sent by the current user

swagger:response invitationSentListOK
*/
type InvitationSentListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Invitation `json:"body,omitempty"`
}

// NewInvitationSentListOK creates InvitationSentListOK with default headers values
func NewInvitationSentListOK() *InvitationSentListOK {

	return &InvitationSentListOK{}
}

// WithPayload adds the payload to the invitation sent list o k response
func (o *InvitationSentListOK) WithPayload(payload []*models.Invitation) *InvitationSentListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invitation sent list o k response
func (o *InvitationSentListOK) SetPayload(payload []*models.Invitation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InvitationSentListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Invitation, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// InvitationSentListUnauthorizedCode is the HTTP code returned for type InvitationSentListUnauthorized
const InvitationSentListUnauthorizedCode int = 401

/*InvitationSentListUnauthorized Invalid credentials

swagger:response invitationSentListUnauthorized
*/
type InvitationSentListUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewInvitationSentListUnauthorized creates InvitationSentListUnauthorized with default headers values
func NewInvitationSentListUnauthorized() *InvitationSentListUnauthorized {

	return &InvitationSentListUnauthorized{}
}

// WithPayload adds the payload to the invitation sent list unauthorized response
func (o *InvitationSentListUnauthorized) WithPayload(payload *models.Error) *InvitationSentListUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invitation sent list unauthorized response
func (o *InvitationSentListUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InvitationSentListUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*InvitationSentListDefault Generic error response

swagger:response invitationSentListDefault
*/
type InvitationSentListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewInvitationSentListDefault creates InvitationSentListDefault with default headers values
func NewInvitationSentListDefault(code int) *InvitationSentListDefault {
	if code <= 0 {
		code = 500
	}

	return &InvitationSentListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the invitation sent list default response
func (o *InvitationSentListDefault) WithStatusCode(code int) *InvitationSentListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the invitation sent list default response
func (o *InvitationSentListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the invitation sent list default response
func (o *InvitationSentListDefault) WithPayload(payload *models.Error) *InvitationSentListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invitation sent list default response
func (o *InvitationSentListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InvitationSentListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
