// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/neper-stars/neper/models"
)

// NewNeperAPI creates a new Neper instance
func NewNeperAPI(spec *loads.Document) *NeperAPI {
	return &NeperAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		BinProducer:  runtime.ByteStreamProducer(),
		JSONProducer: runtime.JSONProducer(),

		AuthenticateHandler: AuthenticateHandlerFunc(func(params AuthenticateParams) middleware.Responder {
			return middleware.NotImplemented("operation Authenticate has not yet been implemented")
		}),
		DownloadStarsExeHandler: DownloadStarsExeHandlerFunc(func(params DownloadStarsExeParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation DownloadStarsExe has not yet been implemented")
		}),
		GameCreateHandler: GameCreateHandlerFunc(func(params GameCreateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation GameCreate has not yet been implemented")
		}),
		InvitationAcceptHandler: InvitationAcceptHandlerFunc(func(params InvitationAcceptParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation InvitationAccept has not yet been implemented")
		}),
		InvitationCreateHandler: InvitationCreateHandlerFunc(func(params InvitationCreateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation InvitationCreate has not yet been implemented")
		}),
		InvitationDeclineHandler: InvitationDeclineHandlerFunc(func(params InvitationDeclineParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation InvitationDecline has not yet been implemented")
		}),
		InvitationListHandler: InvitationListHandlerFunc(func(params InvitationListParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation InvitationList has not yet been implemented")
		}),
		NotificationsHandler: NotificationsHandlerFunc(func(params NotificationsParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation Notifications has not yet been implemented")
		}),
		OrdersStatusHandler: OrdersStatusHandlerFunc(func(params OrdersStatusParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation OrdersStatus has not yet been implemented")
		}),
		RaceCreateHandler: RaceCreateHandlerFunc(func(params RaceCreateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation RaceCreate has not yet been implemented")
		}),
		RaceDeleteHandler: RaceDeleteHandlerFunc(func(params RaceDeleteParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation RaceDelete has not yet been implemented")
		}),
		RaceReadHandler: RaceReadHandlerFunc(func(params RaceReadParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation RaceRead has not yet been implemented")
		}),
		RacesListHandler: RacesListHandlerFunc(func(params RacesListParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation RacesList has not yet been implemented")
		}),
		RefreshTokenHandler: RefreshTokenHandlerFunc(func(params RefreshTokenParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation RefreshToken has not yet been implemented")
		}),
		ReorderPlayersHandler: ReorderPlayersHandlerFunc(func(params ReorderPlayersParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation ReorderPlayers has not yet been implemented")
		}),
		RulesCreateHandler: RulesCreateHandlerFunc(func(params RulesCreateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation RulesCreate has not yet been implemented")
		}),
		RulesReadHandler: RulesReadHandlerFunc(func(params RulesReadParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation RulesRead has not yet been implemented")
		}),
		SessionCreateHandler: SessionCreateHandlerFunc(func(params SessionCreateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionCreate has not yet been implemented")
		}),
		SessionDeleteHandler: SessionDeleteHandlerFunc(func(params SessionDeleteParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionDelete has not yet been implemented")
		}),
		SessionJoinHandler: SessionJoinHandlerFunc(func(params SessionJoinParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionJoin has not yet been implemented")
		}),
		SessionPlayerRaceCreateHandler: SessionPlayerRaceCreateHandlerFunc(func(params SessionPlayerRaceCreateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionPlayerRaceCreate has not yet been implemented")
		}),
		SessionPlayerRaceGetHandler: SessionPlayerRaceGetHandlerFunc(func(params SessionPlayerRaceGetParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionPlayerRaceGet has not yet been implemented")
		}),
		SessionPlayerRaceSetReadyHandler: SessionPlayerRaceSetReadyHandlerFunc(func(params SessionPlayerRaceSetReadyParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionPlayerRaceSetReady has not yet been implemented")
		}),
		SessionReadHandler: SessionReadHandlerFunc(func(params SessionReadParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionRead has not yet been implemented")
		}),
		SessionUpdateHandler: SessionUpdateHandlerFunc(func(params SessionUpdateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionUpdate has not yet been implemented")
		}),
		SessionsListHandler: SessionsListHandlerFunc(func(params SessionsListParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation SessionsList has not yet been implemented")
		}),
		TurnGetHandler: TurnGetHandlerFunc(func(params TurnGetParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation TurnGet has not yet been implemented")
		}),
		TurnLatestHandler: TurnLatestHandlerFunc(func(params TurnLatestParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation TurnLatest has not yet been implemented")
		}),
		TurnSubmitHandler: TurnSubmitHandlerFunc(func(params TurnSubmitParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation TurnSubmit has not yet been implemented")
		}),
		UserProfileCreateHandler: UserProfileCreateHandlerFunc(func(params UserProfileCreateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation UserProfileCreate has not yet been implemented")
		}),
		UserProfileListHandler: UserProfileListHandlerFunc(func(params UserProfileListParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation UserProfileList has not yet been implemented")
		}),
		UserProfileReadHandler: UserProfileReadHandlerFunc(func(params UserProfileReadParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation UserProfileRead has not yet been implemented")
		}),
		UserProfileResetApikeyHandler: UserProfileResetApikeyHandlerFunc(func(params UserProfileResetApikeyParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation UserProfileResetApikey has not yet been implemented")
		}),
		UserProfileUpdateHandler: UserProfileUpdateHandlerFunc(func(params UserProfileUpdateParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation UserProfileUpdate has not yet been implemented")
		}),
		UserinfoHandler: UserinfoHandlerFunc(func(params UserinfoParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation Userinfo has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		KeyAuth: func(token string) (*models.Principal, error) {
			return nil, errors.NotImplemented("api key auth (key) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*NeperAPI The Neper API
 */
type NeperAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// BinProducer registers a producer for the following mime types:
	//   - application/octet-stream
	BinProducer runtime.Producer
	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// KeyAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	KeyAuth func(string) (*models.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// AuthenticateHandler sets the operation handler for the authenticate operation
	AuthenticateHandler AuthenticateHandler
	// DownloadStarsExeHandler sets the operation handler for the download stars exe operation
	DownloadStarsExeHandler DownloadStarsExeHandler
	// GameCreateHandler sets the operation handler for the game create operation
	GameCreateHandler GameCreateHandler
	// InvitationAcceptHandler sets the operation handler for the invitation accept operation
	InvitationAcceptHandler InvitationAcceptHandler
	// InvitationCreateHandler sets the operation handler for the invitation create operation
	InvitationCreateHandler InvitationCreateHandler
	// InvitationDeclineHandler sets the operation handler for the invitation decline operation
	InvitationDeclineHandler InvitationDeclineHandler
	// InvitationListHandler sets the operation handler for the invitation list operation
	InvitationListHandler InvitationListHandler
	// NotificationsHandler sets the operation handler for the notifications operation
	NotificationsHandler NotificationsHandler
	// OrdersStatusHandler sets the operation handler for the orders status operation
	OrdersStatusHandler OrdersStatusHandler
	// RaceCreateHandler sets the operation handler for the race create operation
	RaceCreateHandler RaceCreateHandler
	// RaceDeleteHandler sets the operation handler for the race delete operation
	RaceDeleteHandler RaceDeleteHandler
	// RaceReadHandler sets the operation handler for the race read operation
	RaceReadHandler RaceReadHandler
	// RacesListHandler sets the operation handler for the races list operation
	RacesListHandler RacesListHandler
	// RefreshTokenHandler sets the operation handler for the refresh token operation
	RefreshTokenHandler RefreshTokenHandler
	// ReorderPlayersHandler sets the operation handler for the reorder players operation
	ReorderPlayersHandler ReorderPlayersHandler
	// RulesCreateHandler sets the operation handler for the rules create operation
	RulesCreateHandler RulesCreateHandler
	// RulesReadHandler sets the operation handler for the rules read operation
	RulesReadHandler RulesReadHandler
	// SessionCreateHandler sets the operation handler for the session create operation
	SessionCreateHandler SessionCreateHandler
	// SessionDeleteHandler sets the operation handler for the session delete operation
	SessionDeleteHandler SessionDeleteHandler
	// SessionJoinHandler sets the operation handler for the session join operation
	SessionJoinHandler SessionJoinHandler
	// SessionPlayerRaceCreateHandler sets the operation handler for the session player race create operation
	SessionPlayerRaceCreateHandler SessionPlayerRaceCreateHandler
	// SessionPlayerRaceGetHandler sets the operation handler for the session player race get operation
	SessionPlayerRaceGetHandler SessionPlayerRaceGetHandler
	// SessionPlayerRaceSetReadyHandler sets the operation handler for the session player race set ready operation
	SessionPlayerRaceSetReadyHandler SessionPlayerRaceSetReadyHandler
	// SessionReadHandler sets the operation handler for the session read operation
	SessionReadHandler SessionReadHandler
	// SessionUpdateHandler sets the operation handler for the session update operation
	SessionUpdateHandler SessionUpdateHandler
	// SessionsListHandler sets the operation handler for the sessions list operation
	SessionsListHandler SessionsListHandler
	// TurnGetHandler sets the operation handler for the turn get operation
	TurnGetHandler TurnGetHandler
	// TurnLatestHandler sets the operation handler for the turn latest operation
	TurnLatestHandler TurnLatestHandler
	// TurnSubmitHandler sets the operation handler for the turn submit operation
	TurnSubmitHandler TurnSubmitHandler
	// UserProfileCreateHandler sets the operation handler for the user profile create operation
	UserProfileCreateHandler UserProfileCreateHandler
	// UserProfileListHandler sets the operation handler for the user profile list operation
	UserProfileListHandler UserProfileListHandler
	// UserProfileReadHandler sets the operation handler for the user profile read operation
	UserProfileReadHandler UserProfileReadHandler
	// UserProfileResetApikeyHandler sets the operation handler for the user profile reset apikey operation
	UserProfileResetApikeyHandler UserProfileResetApikeyHandler
	// UserProfileUpdateHandler sets the operation handler for the user profile update operation
	UserProfileUpdateHandler UserProfileUpdateHandler
	// UserinfoHandler sets the operation handler for the userinfo operation
	UserinfoHandler UserinfoHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *NeperAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *NeperAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *NeperAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *NeperAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *NeperAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *NeperAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *NeperAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *NeperAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *NeperAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the NeperAPI
func (o *NeperAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.BinProducer == nil {
		unregistered = append(unregistered, "BinProducer")
	}
	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.KeyAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.AuthenticateHandler == nil {
		unregistered = append(unregistered, "AuthenticateHandler")
	}
	if o.DownloadStarsExeHandler == nil {
		unregistered = append(unregistered, "DownloadStarsExeHandler")
	}
	if o.GameCreateHandler == nil {
		unregistered = append(unregistered, "GameCreateHandler")
	}
	if o.InvitationAcceptHandler == nil {
		unregistered = append(unregistered, "InvitationAcceptHandler")
	}
	if o.InvitationCreateHandler == nil {
		unregistered = append(unregistered, "InvitationCreateHandler")
	}
	if o.InvitationDeclineHandler == nil {
		unregistered = append(unregistered, "InvitationDeclineHandler")
	}
	if o.InvitationListHandler == nil {
		unregistered = append(unregistered, "InvitationListHandler")
	}
	if o.NotificationsHandler == nil {
		unregistered = append(unregistered, "NotificationsHandler")
	}
	if o.OrdersStatusHandler == nil {
		unregistered = append(unregistered, "OrdersStatusHandler")
	}
	if o.RaceCreateHandler == nil {
		unregistered = append(unregistered, "RaceCreateHandler")
	}
	if o.RaceDeleteHandler == nil {
		unregistered = append(unregistered, "RaceDeleteHandler")
	}
	if o.RaceReadHandler == nil {
		unregistered = append(unregistered, "RaceReadHandler")
	}
	if o.RacesListHandler == nil {
		unregistered = append(unregistered, "RacesListHandler")
	}
	if o.RefreshTokenHandler == nil {
		unregistered = append(unregistered, "RefreshTokenHandler")
	}
	if o.ReorderPlayersHandler == nil {
		unregistered = append(unregistered, "ReorderPlayersHandler")
	}
	if o.RulesCreateHandler == nil {
		unregistered = append(unregistered, "RulesCreateHandler")
	}
	if o.RulesReadHandler == nil {
		unregistered = append(unregistered, "RulesReadHandler")
	}
	if o.SessionCreateHandler == nil {
		unregistered = append(unregistered, "SessionCreateHandler")
	}
	if o.SessionDeleteHandler == nil {
		unregistered = append(unregistered, "SessionDeleteHandler")
	}
	if o.SessionJoinHandler == nil {
		unregistered = append(unregistered, "SessionJoinHandler")
	}
	if o.SessionPlayerRaceCreateHandler == nil {
		unregistered = append(unregistered, "SessionPlayerRaceCreateHandler")
	}
	if o.SessionPlayerRaceGetHandler == nil {
		unregistered = append(unregistered, "SessionPlayerRaceGetHandler")
	}
	if o.SessionPlayerRaceSetReadyHandler == nil {
		unregistered = append(unregistered, "SessionPlayerRaceSetReadyHandler")
	}
	if o.SessionReadHandler == nil {
		unregistered = append(unregistered, "SessionReadHandler")
	}
	if o.SessionUpdateHandler == nil {
		unregistered = append(unregistered, "SessionUpdateHandler")
	}
	if o.SessionsListHandler == nil {
		unregistered = append(unregistered, "SessionsListHandler")
	}
	if o.TurnGetHandler == nil {
		unregistered = append(unregistered, "TurnGetHandler")
	}
	if o.TurnLatestHandler == nil {
		unregistered = append(unregistered, "TurnLatestHandler")
	}
	if o.TurnSubmitHandler == nil {
		unregistered = append(unregistered, "TurnSubmitHandler")
	}
	if o.UserProfileCreateHandler == nil {
		unregistered = append(unregistered, "UserProfileCreateHandler")
	}
	if o.UserProfileListHandler == nil {
		unregistered = append(unregistered, "UserProfileListHandler")
	}
	if o.UserProfileReadHandler == nil {
		unregistered = append(unregistered, "UserProfileReadHandler")
	}
	if o.UserProfileResetApikeyHandler == nil {
		unregistered = append(unregistered, "UserProfileResetApikeyHandler")
	}
	if o.UserProfileUpdateHandler == nil {
		unregistered = append(unregistered, "UserProfileUpdateHandler")
	}
	if o.UserinfoHandler == nil {
		unregistered = append(unregistered, "UserinfoHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *NeperAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *NeperAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "key":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.KeyAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *NeperAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *NeperAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *NeperAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/octet-stream":
			result["application/octet-stream"] = o.BinProducer
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *NeperAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the neper API
func (o *NeperAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *NeperAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/auth/authenticate"] = NewAuthenticate(o.context, o.AuthenticateHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/downloads/stars.exe"] = NewDownloadStarsExe(o.context, o.DownloadStarsExeHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/sessions/{session_id}/game"] = NewGameCreate(o.context, o.GameCreateHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/invitations/{invitation_id}"] = NewInvitationAccept(o.context, o.InvitationAcceptHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/sessions/{session_id}/invite"] = NewInvitationCreate(o.context, o.InvitationCreateHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/invitations/{invitation_id}"] = NewInvitationDecline(o.context, o.InvitationDeclineHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/invitations"] = NewInvitationList(o.context, o.InvitationListHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/notifications"] = NewNotifications(o.context, o.NotificationsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/sessions/{session_id}/orders/{year}"] = NewOrdersStatus(o.context, o.OrdersStatusHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/user_profiles/{user_profile_id}/races"] = NewRaceCreate(o.context, o.RaceCreateHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/user_profiles/{user_profile_id}/races/{race_id}"] = NewRaceDelete(o.context, o.RaceDeleteHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/user_profiles/{user_profile_id}/races/{race_id}"] = NewRaceRead(o.context, o.RaceReadHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/user_profiles/{user_profile_id}/races"] = NewRacesList(o.context, o.RacesListHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/auth/refresh_token"] = NewRefreshToken(o.context, o.RefreshTokenHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/sessions/{session_id}/reorder_players"] = NewReorderPlayers(o.context, o.ReorderPlayersHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/sessions/{session_id}/rules"] = NewRulesCreate(o.context, o.RulesCreateHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/sessions/{session_id}/rules"] = NewRulesRead(o.context, o.RulesReadHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/sessions"] = NewSessionCreate(o.context, o.SessionCreateHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/sessions/{session_id}"] = NewSessionDelete(o.context, o.SessionDeleteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/sessions/{session_id}/join"] = NewSessionJoin(o.context, o.SessionJoinHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/sessions/{session_id}/player_race"] = NewSessionPlayerRaceCreate(o.context, o.SessionPlayerRaceCreateHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/sessions/{session_id}/player_race"] = NewSessionPlayerRaceGet(o.context, o.SessionPlayerRaceGetHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/sessions/{session_id}/player_race/ready"] = NewSessionPlayerRaceSetReady(o.context, o.SessionPlayerRaceSetReadyHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/sessions/{session_id}"] = NewSessionRead(o.context, o.SessionReadHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/sessions/{session_id}"] = NewSessionUpdate(o.context, o.SessionUpdateHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/sessions"] = NewSessionsList(o.context, o.SessionsListHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/sessions/{session_id}/turn/{year}"] = NewTurnGet(o.context, o.TurnGetHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/sessions/{session_id}/turn/latest"] = NewTurnLatest(o.context, o.TurnLatestHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/sessions/{session_id}/turn/{year}"] = NewTurnSubmit(o.context, o.TurnSubmitHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/user_profiles"] = NewUserProfileCreate(o.context, o.UserProfileCreateHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/user_profiles"] = NewUserProfileList(o.context, o.UserProfileListHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/user_profiles/{user_profile_id}"] = NewUserProfileRead(o.context, o.UserProfileReadHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/user_profiles/{user_profile_id}/reset_apikey"] = NewUserProfileResetApikey(o.context, o.UserProfileResetApikeyHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/user_profiles/{user_profile_id}"] = NewUserProfileUpdate(o.context, o.UserProfileUpdateHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/auth/userinfo"] = NewUserinfo(o.context, o.UserinfoHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *NeperAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *NeperAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *NeperAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *NeperAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *NeperAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
