// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// NotificationsHandlerFunc turns a function with the right signature into a notifications handler
type NotificationsHandlerFunc func(NotificationsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn NotificationsHandlerFunc) Handle(params NotificationsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// NotificationsHandler interface for that can handle valid notifications params
type NotificationsHandler interface {
	Handle(NotificationsParams, *models.Principal) middleware.Responder
}

// NewNotifications creates a new http.Handler for the notifications operation
func NewNotifications(ctx *middleware.Context, handler NotificationsHandler) *Notifications {
	return &Notifications{Context: ctx, Handler: handler}
}

/* Notifications swagger:route GET /v1/notifications notifications

WebSocket endpoint for real-time resource change notifications

Upgrades to WebSocket connection. Sends JSON notifications when
resources the user has access to are modified.

Message format:
```json
{
  "type": "session",
  "id": "abc123",
  "action": "updated",
  "timestamp": 1702400000
}
```

Types: session, invitation, race, ruleset, session_player_race
Actions: created, updated, deleted


*/
type Notifications struct {
	Context *middleware.Context
	Handler NotificationsHandler
}

func (o *Notifications) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNotificationsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
