// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// NotificationsSwitchingProtocolsCode is the HTTP code returned for type NotificationsSwitchingProtocols
const NotificationsSwitchingProtocolsCode int = 101

/*NotificationsSwitchingProtocols WebSocket upgrade successful

swagger:response notificationsSwitchingProtocols
*/
type NotificationsSwitchingProtocols struct {
}

// NewNotificationsSwitchingProtocols creates NotificationsSwitchingProtocols with default headers values
func NewNotificationsSwitchingProtocols() *NotificationsSwitchingProtocols {

	return &NotificationsSwitchingProtocols{}
}

// WriteResponse to the client
func (o *NotificationsSwitchingProtocols) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(101)
}

// NotificationsUnauthorizedCode is the HTTP code returned for type NotificationsUnauthorized
const NotificationsUnauthorizedCode int = 401

/*NotificationsUnauthorized Invalid credentials

swagger:response notificationsUnauthorized
*/
type NotificationsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNotificationsUnauthorized creates NotificationsUnauthorized with default headers values
func NewNotificationsUnauthorized() *NotificationsUnauthorized {

	return &NotificationsUnauthorized{}
}

// WithPayload adds the payload to the notifications unauthorized response
func (o *NotificationsUnauthorized) WithPayload(payload *models.Error) *NotificationsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the notifications unauthorized response
func (o *NotificationsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NotificationsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NotificationsDefault Generic error response

swagger:response notificationsDefault
*/
type NotificationsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNotificationsDefault creates NotificationsDefault with default headers values
func NewNotificationsDefault(code int) *NotificationsDefault {
	if code <= 0 {
		code = 500
	}

	return &NotificationsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the notifications default response
func (o *NotificationsDefault) WithStatusCode(code int) *NotificationsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the notifications default response
func (o *NotificationsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the notifications default response
func (o *NotificationsDefault) WithPayload(payload *models.Error) *NotificationsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the notifications default response
func (o *NotificationsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NotificationsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
