// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// PendingRegistrationApproveOKCode is the HTTP code returned for type PendingRegistrationApproveOK
const PendingRegistrationApproveOKCode int = 200

/*PendingRegistrationApproveOK the approved user profile with API key

swagger:response pendingRegistrationApproveOK
*/
type PendingRegistrationApproveOK struct {

	/*
	  In: Body
	*/
	Payload *models.ApikeyReset `json:"body,omitempty"`
}

// NewPendingRegistrationApproveOK creates PendingRegistrationApproveOK with default headers values
func NewPendingRegistrationApproveOK() *PendingRegistrationApproveOK {

	return &PendingRegistrationApproveOK{}
}

// WithPayload adds the payload to the pending registration approve o k response
func (o *PendingRegistrationApproveOK) WithPayload(payload *models.ApikeyReset) *PendingRegistrationApproveOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pending registration approve o k response
func (o *PendingRegistrationApproveOK) SetPayload(payload *models.ApikeyReset) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PendingRegistrationApproveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PendingRegistrationApproveUnauthorizedCode is the HTTP code returned for type PendingRegistrationApproveUnauthorized
const PendingRegistrationApproveUnauthorizedCode int = 401

/*PendingRegistrationApproveUnauthorized Invalid credentials

swagger:response pendingRegistrationApproveUnauthorized
*/
type PendingRegistrationApproveUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPendingRegistrationApproveUnauthorized creates PendingRegistrationApproveUnauthorized with default headers values
func NewPendingRegistrationApproveUnauthorized() *PendingRegistrationApproveUnauthorized {

	return &PendingRegistrationApproveUnauthorized{}
}

// WithPayload adds the payload to the pending registration approve unauthorized response
func (o *PendingRegistrationApproveUnauthorized) WithPayload(payload *models.Error) *PendingRegistrationApproveUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pending registration approve unauthorized response
func (o *PendingRegistrationApproveUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PendingRegistrationApproveUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PendingRegistrationApproveForbiddenCode is the HTTP code returned for type PendingRegistrationApproveForbidden
const PendingRegistrationApproveForbiddenCode int = 403

/*PendingRegistrationApproveForbidden Access forbidden

swagger:response pendingRegistrationApproveForbidden
*/
type PendingRegistrationApproveForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPendingRegistrationApproveForbidden creates PendingRegistrationApproveForbidden with default headers values
func NewPendingRegistrationApproveForbidden() *PendingRegistrationApproveForbidden {

	return &PendingRegistrationApproveForbidden{}
}

// WithPayload adds the payload to the pending registration approve forbidden response
func (o *PendingRegistrationApproveForbidden) WithPayload(payload *models.Error) *PendingRegistrationApproveForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pending registration approve forbidden response
func (o *PendingRegistrationApproveForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PendingRegistrationApproveForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PendingRegistrationApproveNotFoundCode is the HTTP code returned for type PendingRegistrationApproveNotFound
const PendingRegistrationApproveNotFoundCode int = 404

/*PendingRegistrationApproveNotFound Resource not found

swagger:response pendingRegistrationApproveNotFound
*/
type PendingRegistrationApproveNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPendingRegistrationApproveNotFound creates PendingRegistrationApproveNotFound with default headers values
func NewPendingRegistrationApproveNotFound() *PendingRegistrationApproveNotFound {

	return &PendingRegistrationApproveNotFound{}
}

// WithPayload adds the payload to the pending registration approve not found response
func (o *PendingRegistrationApproveNotFound) WithPayload(payload *models.Error) *PendingRegistrationApproveNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pending registration approve not found response
func (o *PendingRegistrationApproveNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PendingRegistrationApproveNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PendingRegistrationApproveDefault Generic error response

swagger:response pendingRegistrationApproveDefault
*/
type PendingRegistrationApproveDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPendingRegistrationApproveDefault creates PendingRegistrationApproveDefault with default headers values
func NewPendingRegistrationApproveDefault(code int) *PendingRegistrationApproveDefault {
	if code <= 0 {
		code = 500
	}

	return &PendingRegistrationApproveDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the pending registration approve default response
func (o *PendingRegistrationApproveDefault) WithStatusCode(code int) *PendingRegistrationApproveDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the pending registration approve default response
func (o *PendingRegistrationApproveDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the pending registration approve default response
func (o *PendingRegistrationApproveDefault) WithPayload(payload *models.Error) *PendingRegistrationApproveDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pending registration approve default response
func (o *PendingRegistrationApproveDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PendingRegistrationApproveDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
