// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// PendingRegistrationListHandlerFunc turns a function with the right signature into a pending registration list handler
type PendingRegistrationListHandlerFunc func(PendingRegistrationListParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PendingRegistrationListHandlerFunc) Handle(params PendingRegistrationListParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PendingRegistrationListHandler interface for that can handle valid pending registration list params
type PendingRegistrationListHandler interface {
	Handle(PendingRegistrationListParams, *models.Principal) middleware.Responder
}

// NewPendingRegistrationList creates a new http.Handler for the pending registration list operation
func NewPendingRegistrationList(ctx *middleware.Context, handler PendingRegistrationListHandler) *PendingRegistrationList {
	return &PendingRegistrationList{Context: ctx, Handler: handler}
}

/* PendingRegistrationList swagger:route GET /v1/pending_registrations pendingRegistrationList

list all pending registration requests

Returns the list of all user profiles with pending=true.
Only global managers can access this endpoint.


*/
type PendingRegistrationList struct {
	Context *middleware.Context
	Handler PendingRegistrationListHandler
}

func (o *PendingRegistrationList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPendingRegistrationListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
