// Code generated by go-swagger/go-orusapi;; DO NOT EDIT.

package operations

import (
	"github.com/prometheus/client_golang/prometheus"
)

func (o *NeperAPI) PrometheusInstrumentHandlers() {
	o.Init()

	o.handlers["POST"]["/v1/auth/authenticate"] = AuthenticateInstrumentHandler(
		o.handlers["POST"]["/v1/auth/authenticate"])

	o.handlers["POST"]["/v1/sessions/{session_id}/game"] = GameCreateInstrumentHandler(
		o.handlers["POST"]["/v1/sessions/{session_id}/game"])

	o.handlers["PUT"]["/v1/invitations/{invitation_id}"] = InvitationAcceptInstrumentHandler(
		o.handlers["PUT"]["/v1/invitations/{invitation_id}"])

	o.handlers["POST"]["/v1/sessions/{session_id}/invite"] = InvitationCreateInstrumentHandler(
		o.handlers["POST"]["/v1/sessions/{session_id}/invite"])

	o.handlers["GET"]["/v1/invitations"] = InvitationListInstrumentHandler(
		o.handlers["GET"]["/v1/invitations"])

	o.handlers["POST"]["/v1/user_profiles/{user_profile_id}/races"] = RaceCreateInstrumentHandler(
		o.handlers["POST"]["/v1/user_profiles/{user_profile_id}/races"])

	o.handlers["GET"]["/v1/user_profiles/{user_profile_id}/races/{race_id}"] = RaceReadInstrumentHandler(
		o.handlers["GET"]["/v1/user_profiles/{user_profile_id}/races/{race_id}"])

	o.handlers["GET"]["/v1/user_profiles/{user_profile_id}/races"] = RacesListInstrumentHandler(
		o.handlers["GET"]["/v1/user_profiles/{user_profile_id}/races"])

	o.handlers["POST"]["/v1/auth/refresh_token"] = RefreshTokenInstrumentHandler(
		o.handlers["POST"]["/v1/auth/refresh_token"])

	o.handlers["PUT"]["/v1/sessions/{session_id}/reorder_players"] = ReorderPlayersInstrumentHandler(
		o.handlers["PUT"]["/v1/sessions/{session_id}/reorder_players"])

	o.handlers["POST"]["/v1/sessions/{session_id}/rules"] = RulesCreateInstrumentHandler(
		o.handlers["POST"]["/v1/sessions/{session_id}/rules"])

	o.handlers["POST"]["/v1/sessions"] = SessionCreateInstrumentHandler(
		o.handlers["POST"]["/v1/sessions"])

	o.handlers["POST"]["/v1/sessions/{session_id}/join"] = SessionJoinInstrumentHandler(
		o.handlers["POST"]["/v1/sessions/{session_id}/join"])

	o.handlers["POST"]["/v1/sessions/{session_id}/player_race"] = SessionPlayerRaceCreateInstrumentHandler(
		o.handlers["POST"]["/v1/sessions/{session_id}/player_race"])

	o.handlers["GET"]["/v1/sessions/{session_id}"] = SessionReadInstrumentHandler(
		o.handlers["GET"]["/v1/sessions/{session_id}"])

	o.handlers["PUT"]["/v1/sessions/{session_id}"] = SessionUpdateInstrumentHandler(
		o.handlers["PUT"]["/v1/sessions/{session_id}"])

	o.handlers["GET"]["/v1/sessions"] = SessionsListInstrumentHandler(
		o.handlers["GET"]["/v1/sessions"])

	o.handlers["POST"]["/v1/user_profiles"] = UserProfileCreateInstrumentHandler(
		o.handlers["POST"]["/v1/user_profiles"])

	o.handlers["GET"]["/v1/user_profiles"] = UserProfileListInstrumentHandler(
		o.handlers["GET"]["/v1/user_profiles"])

	o.handlers["GET"]["/v1/user_profiles/{user_profile_id}"] = UserProfileReadInstrumentHandler(
		o.handlers["GET"]["/v1/user_profiles/{user_profile_id}"])

	o.handlers["PUT"]["/v1/user_profiles/{user_profile_id}"] = UserProfileUpdateInstrumentHandler(
		o.handlers["PUT"]["/v1/user_profiles/{user_profile_id}"])

	o.handlers["GET"]["/v1/auth/userinfo"] = UserinfoInstrumentHandler(
		o.handlers["GET"]["/v1/auth/userinfo"])

}

func init() {
	reg := prometheus.WrapRegistererWith(prometheus.Labels{
		"api_name":    "Neper",
		"api_title":   "Neper API",
		"api_version": "1.0.0",
	}, prometheus.DefaultRegisterer)

	RegisterPrometheus(reg)
}
