// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewRaceDeleteParams creates a new RaceDeleteParams object
//
// There are no default values defined in the spec.
func NewRaceDeleteParams() RaceDeleteParams {

	return RaceDeleteParams{}
}

// RaceDeleteParams contains all the bound params for the race delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters raceDelete
type RaceDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	RaceID string
	/*
	  Required: true
	  In: path
	*/
	UserProfileID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRaceDeleteParams() beforehand.
func (o *RaceDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRaceID, rhkRaceID, _ := route.Params.GetOK("race_id")
	if err := o.bindRaceID(rRaceID, rhkRaceID, route.Formats); err != nil {
		res = append(res, err)
	}

	rUserProfileID, rhkUserProfileID, _ := route.Params.GetOK("user_profile_id")
	if err := o.bindUserProfileID(rUserProfileID, rhkUserProfileID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRaceID binds and validates parameter RaceID from path.
func (o *RaceDeleteParams) bindRaceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.RaceID = raw

	return nil
}

// bindUserProfileID binds and validates parameter UserProfileID from path.
func (o *RaceDeleteParams) bindUserProfileID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.UserProfileID = raw

	return nil
}
