// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// RaceCreateCreatedCode is the HTTP code returned for type RaceCreateCreated
const RaceCreateCreatedCode int = 201

/*RaceCreateCreated the uploaded race, with the auto calculated fields filled

swagger:response raceCreateCreated
*/
type RaceCreateCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Race `json:"body,omitempty"`
}

// NewRaceCreateCreated creates RaceCreateCreated with default headers values
func NewRaceCreateCreated() *RaceCreateCreated {

	return &RaceCreateCreated{}
}

// WithPayload adds the payload to the race create created response
func (o *RaceCreateCreated) WithPayload(payload *models.Race) *RaceCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the race create created response
func (o *RaceCreateCreated) SetPayload(payload *models.Race) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RaceCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RaceCreateBadRequestCode is the HTTP code returned for type RaceCreateBadRequest
const RaceCreateBadRequestCode int = 400

/*RaceCreateBadRequest invalid client request

swagger:response raceCreateBadRequest
*/
type RaceCreateBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRaceCreateBadRequest creates RaceCreateBadRequest with default headers values
func NewRaceCreateBadRequest() *RaceCreateBadRequest {

	return &RaceCreateBadRequest{}
}

// WithPayload adds the payload to the race create bad request response
func (o *RaceCreateBadRequest) WithPayload(payload *models.Error) *RaceCreateBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the race create bad request response
func (o *RaceCreateBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RaceCreateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RaceCreateUnauthorizedCode is the HTTP code returned for type RaceCreateUnauthorized
const RaceCreateUnauthorizedCode int = 401

/*RaceCreateUnauthorized Invalid credentials

swagger:response raceCreateUnauthorized
*/
type RaceCreateUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRaceCreateUnauthorized creates RaceCreateUnauthorized with default headers values
func NewRaceCreateUnauthorized() *RaceCreateUnauthorized {

	return &RaceCreateUnauthorized{}
}

// WithPayload adds the payload to the race create unauthorized response
func (o *RaceCreateUnauthorized) WithPayload(payload *models.Error) *RaceCreateUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the race create unauthorized response
func (o *RaceCreateUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RaceCreateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RaceCreateForbiddenCode is the HTTP code returned for type RaceCreateForbidden
const RaceCreateForbiddenCode int = 403

/*RaceCreateForbidden Access forbidden

swagger:response raceCreateForbidden
*/
type RaceCreateForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRaceCreateForbidden creates RaceCreateForbidden with default headers values
func NewRaceCreateForbidden() *RaceCreateForbidden {

	return &RaceCreateForbidden{}
}

// WithPayload adds the payload to the race create forbidden response
func (o *RaceCreateForbidden) WithPayload(payload *models.Error) *RaceCreateForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the race create forbidden response
func (o *RaceCreateForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RaceCreateForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*RaceCreateDefault Generic error response

swagger:response raceCreateDefault
*/
type RaceCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRaceCreateDefault creates RaceCreateDefault with default headers values
func NewRaceCreateDefault(code int) *RaceCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &RaceCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the race create default response
func (o *RaceCreateDefault) WithStatusCode(code int) *RaceCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the race create default response
func (o *RaceCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the race create default response
func (o *RaceCreateDefault) WithPayload(payload *models.Error) *RaceCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the race create default response
func (o *RaceCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RaceCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
