// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"bytes"
	"io"
	"io/ioutil"
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// RefreshTokenHandlerFunc turns a function with the right signature into a refresh token handler
type RefreshTokenHandlerFunc func(RefreshTokenParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn RefreshTokenHandlerFunc) Handle(params RefreshTokenParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// RefreshTokenHandler interface for that can handle valid refresh token params
type RefreshTokenHandler interface {
	Handle(RefreshTokenParams, *models.Principal) middleware.Responder
}

// NewRefreshToken creates a new http.Handler for the refresh token operation
func NewRefreshToken(ctx *middleware.Context, handler RefreshTokenHandler) *RefreshToken {
	return &RefreshToken{Context: ctx, Handler: handler}
}

/* RefreshToken swagger:route POST /v1/auth/refresh_token refreshToken

RefreshToken refresh token API

*/
type RefreshToken struct {
	Context *middleware.Context
	Handler RefreshTokenHandler
}

func (o *RefreshToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}

	var Params = NewRefreshTokenParams()
	var bodyExists bool
	var body []byte
	if r.Body != nil {
		var err error
		bodyExists = true
		body, err = io.ReadAll(r.Body)
		if err != nil {
			o.Context.Respond(rw, r, route.Produces, route, err)
			return
		}
		r.Body = ioutil.NopCloser(bytes.NewReader(body))
	}
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	if bodyExists {
		// restore body
		r.Body = ioutil.NopCloser(bytes.NewReader(body))
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
