// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// RefreshTokenOKCode is the HTTP code returned for type RefreshTokenOK
const RefreshTokenOKCode int = 200

/*RefreshTokenOK A Json Web Token with a 5 minutes validity

swagger:response refreshTokenOK
*/
type RefreshTokenOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewRefreshTokenOK creates RefreshTokenOK with default headers values
func NewRefreshTokenOK() *RefreshTokenOK {

	return &RefreshTokenOK{}
}

// WithPayload adds the payload to the refresh token o k response
func (o *RefreshTokenOK) WithPayload(payload string) *RefreshTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token o k response
func (o *RefreshTokenOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*RefreshTokenDefault generic error response

swagger:response refreshTokenDefault
*/
type RefreshTokenDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRefreshTokenDefault creates RefreshTokenDefault with default headers values
func NewRefreshTokenDefault(code int) *RefreshTokenDefault {
	if code <= 0 {
		code = 500
	}

	return &RefreshTokenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the refresh token default response
func (o *RefreshTokenDefault) WithStatusCode(code int) *RefreshTokenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the refresh token default response
func (o *RefreshTokenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the refresh token default response
func (o *RefreshTokenDefault) WithPayload(payload *models.Error) *RefreshTokenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token default response
func (o *RefreshTokenDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
