// Code generated by go-swagger/go-orusapi; DO NOT EDIT.

// Copyright Orus.io team

package operations

import (
	"net/http"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	reorderPlayersHandlerDuration = prometheus.NewSummaryVec(
		prometheus.SummaryOpts{
			Name:       "orus_api_handler",
			Help:       "The handlers duration and count.",
			Objectives: map[float64]float64{0.9: 0.01, 0.95: 0.01, 0.99: 0.001},
			ConstLabels: map[string]string{
				"service": "reorderPlayers",
			},
		},
		[]string{"code"},
	)

	reorderPlayersHandlerInFlight = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "orus_api_handler_in_flight",
			Help: "The number of handlers currently running.",
			ConstLabels: map[string]string{
				"service": "reorderPlayers",
			},
		},
	)
)

func ReorderPlayersInstrumentHandler(handler http.Handler) http.Handler {
	return promhttp.InstrumentHandlerInFlight(reorderPlayersHandlerInFlight,
		promhttp.InstrumentHandlerDuration(reorderPlayersHandlerDuration,
			handler,
		),
	)
}
