// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// ReorderPlayersOKCode is the HTTP code returned for type ReorderPlayersOK
const ReorderPlayersOKCode int = 200

/*ReorderPlayersOK the updated player order

swagger:response reorderPlayersOK
*/
type ReorderPlayersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.PlayerOrder `json:"body,omitempty"`
}

// NewReorderPlayersOK creates ReorderPlayersOK with default headers values
func NewReorderPlayersOK() *ReorderPlayersOK {

	return &ReorderPlayersOK{}
}

// WithPayload adds the payload to the reorder players o k response
func (o *ReorderPlayersOK) WithPayload(payload []*models.PlayerOrder) *ReorderPlayersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reorder players o k response
func (o *ReorderPlayersOK) SetPayload(payload []*models.PlayerOrder) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReorderPlayersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.PlayerOrder, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ReorderPlayersUnauthorizedCode is the HTTP code returned for type ReorderPlayersUnauthorized
const ReorderPlayersUnauthorizedCode int = 401

/*ReorderPlayersUnauthorized Invalid credentials

swagger:response reorderPlayersUnauthorized
*/
type ReorderPlayersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReorderPlayersUnauthorized creates ReorderPlayersUnauthorized with default headers values
func NewReorderPlayersUnauthorized() *ReorderPlayersUnauthorized {

	return &ReorderPlayersUnauthorized{}
}

// WithPayload adds the payload to the reorder players unauthorized response
func (o *ReorderPlayersUnauthorized) WithPayload(payload *models.Error) *ReorderPlayersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reorder players unauthorized response
func (o *ReorderPlayersUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReorderPlayersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReorderPlayersForbiddenCode is the HTTP code returned for type ReorderPlayersForbidden
const ReorderPlayersForbiddenCode int = 403

/*ReorderPlayersForbidden Access forbidden

swagger:response reorderPlayersForbidden
*/
type ReorderPlayersForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReorderPlayersForbidden creates ReorderPlayersForbidden with default headers values
func NewReorderPlayersForbidden() *ReorderPlayersForbidden {

	return &ReorderPlayersForbidden{}
}

// WithPayload adds the payload to the reorder players forbidden response
func (o *ReorderPlayersForbidden) WithPayload(payload *models.Error) *ReorderPlayersForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reorder players forbidden response
func (o *ReorderPlayersForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReorderPlayersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ReorderPlayersDefault Generic error response

swagger:response reorderPlayersDefault
*/
type ReorderPlayersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReorderPlayersDefault creates ReorderPlayersDefault with default headers values
func NewReorderPlayersDefault(code int) *ReorderPlayersDefault {
	if code <= 0 {
		code = 500
	}

	return &ReorderPlayersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the reorder players default response
func (o *ReorderPlayersDefault) WithStatusCode(code int) *ReorderPlayersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the reorder players default response
func (o *ReorderPlayersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the reorder players default response
func (o *ReorderPlayersDefault) WithPayload(payload *models.Error) *ReorderPlayersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reorder players default response
func (o *ReorderPlayersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReorderPlayersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
