// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// RulesReadOKCode is the HTTP code returned for type RulesReadOK
const RulesReadOKCode int = 200

/*RulesReadOK the session rules

swagger:response rulesReadOK
*/
type RulesReadOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ruleset `json:"body,omitempty"`
}

// NewRulesReadOK creates RulesReadOK with default headers values
func NewRulesReadOK() *RulesReadOK {

	return &RulesReadOK{}
}

// WithPayload adds the payload to the rules read o k response
func (o *RulesReadOK) WithPayload(payload *models.Ruleset) *RulesReadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules read o k response
func (o *RulesReadOK) SetPayload(payload *models.Ruleset) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesReadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RulesReadUnauthorizedCode is the HTTP code returned for type RulesReadUnauthorized
const RulesReadUnauthorizedCode int = 401

/*RulesReadUnauthorized Invalid credentials

swagger:response rulesReadUnauthorized
*/
type RulesReadUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRulesReadUnauthorized creates RulesReadUnauthorized with default headers values
func NewRulesReadUnauthorized() *RulesReadUnauthorized {

	return &RulesReadUnauthorized{}
}

// WithPayload adds the payload to the rules read unauthorized response
func (o *RulesReadUnauthorized) WithPayload(payload *models.Error) *RulesReadUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules read unauthorized response
func (o *RulesReadUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesReadUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RulesReadForbiddenCode is the HTTP code returned for type RulesReadForbidden
const RulesReadForbiddenCode int = 403

/*RulesReadForbidden Access forbidden

swagger:response rulesReadForbidden
*/
type RulesReadForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRulesReadForbidden creates RulesReadForbidden with default headers values
func NewRulesReadForbidden() *RulesReadForbidden {

	return &RulesReadForbidden{}
}

// WithPayload adds the payload to the rules read forbidden response
func (o *RulesReadForbidden) WithPayload(payload *models.Error) *RulesReadForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules read forbidden response
func (o *RulesReadForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesReadForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*RulesReadDefault Generic error response

swagger:response rulesReadDefault
*/
type RulesReadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRulesReadDefault creates RulesReadDefault with default headers values
func NewRulesReadDefault(code int) *RulesReadDefault {
	if code <= 0 {
		code = 500
	}

	return &RulesReadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the rules read default response
func (o *RulesReadDefault) WithStatusCode(code int) *RulesReadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the rules read default response
func (o *RulesReadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the rules read default response
func (o *RulesReadDefault) WithPayload(payload *models.Error) *RulesReadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules read default response
func (o *RulesReadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesReadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
