// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// RulesCreateOKCode is the HTTP code returned for type RulesCreateOK
const RulesCreateOKCode int = 200

/*RulesCreateOK the uploaded ruleset

swagger:response rulesCreateOK
*/
type RulesCreateOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ruleset `json:"body,omitempty"`
}

// NewRulesCreateOK creates RulesCreateOK with default headers values
func NewRulesCreateOK() *RulesCreateOK {

	return &RulesCreateOK{}
}

// WithPayload adds the payload to the rules create o k response
func (o *RulesCreateOK) WithPayload(payload *models.Ruleset) *RulesCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules create o k response
func (o *RulesCreateOK) SetPayload(payload *models.Ruleset) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RulesCreateBadRequestCode is the HTTP code returned for type RulesCreateBadRequest
const RulesCreateBadRequestCode int = 400

/*RulesCreateBadRequest invalid client request

swagger:response rulesCreateBadRequest
*/
type RulesCreateBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRulesCreateBadRequest creates RulesCreateBadRequest with default headers values
func NewRulesCreateBadRequest() *RulesCreateBadRequest {

	return &RulesCreateBadRequest{}
}

// WithPayload adds the payload to the rules create bad request response
func (o *RulesCreateBadRequest) WithPayload(payload *models.Error) *RulesCreateBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules create bad request response
func (o *RulesCreateBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesCreateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RulesCreateUnauthorizedCode is the HTTP code returned for type RulesCreateUnauthorized
const RulesCreateUnauthorizedCode int = 401

/*RulesCreateUnauthorized Invalid credentials

swagger:response rulesCreateUnauthorized
*/
type RulesCreateUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRulesCreateUnauthorized creates RulesCreateUnauthorized with default headers values
func NewRulesCreateUnauthorized() *RulesCreateUnauthorized {

	return &RulesCreateUnauthorized{}
}

// WithPayload adds the payload to the rules create unauthorized response
func (o *RulesCreateUnauthorized) WithPayload(payload *models.Error) *RulesCreateUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules create unauthorized response
func (o *RulesCreateUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesCreateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RulesCreateForbiddenCode is the HTTP code returned for type RulesCreateForbidden
const RulesCreateForbiddenCode int = 403

/*RulesCreateForbidden Access forbidden

swagger:response rulesCreateForbidden
*/
type RulesCreateForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRulesCreateForbidden creates RulesCreateForbidden with default headers values
func NewRulesCreateForbidden() *RulesCreateForbidden {

	return &RulesCreateForbidden{}
}

// WithPayload adds the payload to the rules create forbidden response
func (o *RulesCreateForbidden) WithPayload(payload *models.Error) *RulesCreateForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules create forbidden response
func (o *RulesCreateForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesCreateForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*RulesCreateDefault Generic error response

swagger:response rulesCreateDefault
*/
type RulesCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRulesCreateDefault creates RulesCreateDefault with default headers values
func NewRulesCreateDefault(code int) *RulesCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &RulesCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the rules create default response
func (o *RulesCreateDefault) WithStatusCode(code int) *RulesCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the rules create default response
func (o *RulesCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the rules create default response
func (o *RulesCreateDefault) WithPayload(payload *models.Error) *RulesCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rules create default response
func (o *RulesCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RulesCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
