// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewSessionPlayerRaceSetReadyParams creates a new SessionPlayerRaceSetReadyParams object
//
// There are no default values defined in the spec.
func NewSessionPlayerRaceSetReadyParams() SessionPlayerRaceSetReadyParams {

	return SessionPlayerRaceSetReadyParams{}
}

// SessionPlayerRaceSetReadyParams contains all the bound params for the session player race set ready operation
// typically these are obtained from a http.Request
//
// swagger:parameters sessionPlayerRaceSetReady
type SessionPlayerRaceSetReadyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Ready bool
	/*
	  Required: true
	  In: path
	*/
	SessionID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSessionPlayerRaceSetReadyParams() beforehand.
func (o *SessionPlayerRaceSetReadyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body bool
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("ready", "body", ""))
			} else {
				res = append(res, errors.NewParseError("ready", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.Ready = body
		}
	} else {
		res = append(res, errors.Required("ready", "body", ""))
	}

	rSessionID, rhkSessionID, _ := route.Params.GetOK("session_id")
	if err := o.bindSessionID(rSessionID, rhkSessionID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSessionID binds and validates parameter SessionID from path.
func (o *SessionPlayerRaceSetReadyParams) bindSessionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SessionID = raw

	return nil
}
