// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionPlayerControlOKCode is the HTTP code returned for type SessionPlayerControlOK
const SessionPlayerControlOKCode int = 200

/*SessionPlayerControlOK list of player control statuses

swagger:response sessionPlayerControlOK
*/
type SessionPlayerControlOK struct {

	/*
	  In: Body
	*/
	Payload *models.PlayerControlList `json:"body,omitempty"`
}

// NewSessionPlayerControlOK creates SessionPlayerControlOK with default headers values
func NewSessionPlayerControlOK() *SessionPlayerControlOK {

	return &SessionPlayerControlOK{}
}

// WithPayload adds the payload to the session player control o k response
func (o *SessionPlayerControlOK) WithPayload(payload *models.PlayerControlList) *SessionPlayerControlOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player control o k response
func (o *SessionPlayerControlOK) SetPayload(payload *models.PlayerControlList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerControlOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerControlUnauthorizedCode is the HTTP code returned for type SessionPlayerControlUnauthorized
const SessionPlayerControlUnauthorizedCode int = 401

/*SessionPlayerControlUnauthorized Invalid credentials

swagger:response sessionPlayerControlUnauthorized
*/
type SessionPlayerControlUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerControlUnauthorized creates SessionPlayerControlUnauthorized with default headers values
func NewSessionPlayerControlUnauthorized() *SessionPlayerControlUnauthorized {

	return &SessionPlayerControlUnauthorized{}
}

// WithPayload adds the payload to the session player control unauthorized response
func (o *SessionPlayerControlUnauthorized) WithPayload(payload *models.Error) *SessionPlayerControlUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player control unauthorized response
func (o *SessionPlayerControlUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerControlUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerControlForbiddenCode is the HTTP code returned for type SessionPlayerControlForbidden
const SessionPlayerControlForbiddenCode int = 403

/*SessionPlayerControlForbidden Access forbidden

swagger:response sessionPlayerControlForbidden
*/
type SessionPlayerControlForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerControlForbidden creates SessionPlayerControlForbidden with default headers values
func NewSessionPlayerControlForbidden() *SessionPlayerControlForbidden {

	return &SessionPlayerControlForbidden{}
}

// WithPayload adds the payload to the session player control forbidden response
func (o *SessionPlayerControlForbidden) WithPayload(payload *models.Error) *SessionPlayerControlForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player control forbidden response
func (o *SessionPlayerControlForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerControlForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerControlNotFoundCode is the HTTP code returned for type SessionPlayerControlNotFound
const SessionPlayerControlNotFoundCode int = 404

/*SessionPlayerControlNotFound Resource not found

swagger:response sessionPlayerControlNotFound
*/
type SessionPlayerControlNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerControlNotFound creates SessionPlayerControlNotFound with default headers values
func NewSessionPlayerControlNotFound() *SessionPlayerControlNotFound {

	return &SessionPlayerControlNotFound{}
}

// WithPayload adds the payload to the session player control not found response
func (o *SessionPlayerControlNotFound) WithPayload(payload *models.Error) *SessionPlayerControlNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player control not found response
func (o *SessionPlayerControlNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerControlNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionPlayerControlDefault Generic error response

swagger:response sessionPlayerControlDefault
*/
type SessionPlayerControlDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerControlDefault creates SessionPlayerControlDefault with default headers values
func NewSessionPlayerControlDefault(code int) *SessionPlayerControlDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionPlayerControlDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session player control default response
func (o *SessionPlayerControlDefault) WithStatusCode(code int) *SessionPlayerControlDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session player control default response
func (o *SessionPlayerControlDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session player control default response
func (o *SessionPlayerControlDefault) WithPayload(payload *models.Error) *SessionPlayerControlDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player control default response
func (o *SessionPlayerControlDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerControlDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
