// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionPlayerRaceGetOKCode is the HTTP code returned for type SessionPlayerRaceGetOK
const SessionPlayerRaceGetOKCode int = 200

/*SessionPlayerRaceGetOK the player's race for this session

swagger:response sessionPlayerRaceGetOK
*/
type SessionPlayerRaceGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Race `json:"body,omitempty"`
}

// NewSessionPlayerRaceGetOK creates SessionPlayerRaceGetOK with default headers values
func NewSessionPlayerRaceGetOK() *SessionPlayerRaceGetOK {

	return &SessionPlayerRaceGetOK{}
}

// WithPayload adds the payload to the session player race get o k response
func (o *SessionPlayerRaceGetOK) WithPayload(payload *models.Race) *SessionPlayerRaceGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race get o k response
func (o *SessionPlayerRaceGetOK) SetPayload(payload *models.Race) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerRaceGetUnauthorizedCode is the HTTP code returned for type SessionPlayerRaceGetUnauthorized
const SessionPlayerRaceGetUnauthorizedCode int = 401

/*SessionPlayerRaceGetUnauthorized Invalid credentials

swagger:response sessionPlayerRaceGetUnauthorized
*/
type SessionPlayerRaceGetUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerRaceGetUnauthorized creates SessionPlayerRaceGetUnauthorized with default headers values
func NewSessionPlayerRaceGetUnauthorized() *SessionPlayerRaceGetUnauthorized {

	return &SessionPlayerRaceGetUnauthorized{}
}

// WithPayload adds the payload to the session player race get unauthorized response
func (o *SessionPlayerRaceGetUnauthorized) WithPayload(payload *models.Error) *SessionPlayerRaceGetUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race get unauthorized response
func (o *SessionPlayerRaceGetUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceGetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerRaceGetForbiddenCode is the HTTP code returned for type SessionPlayerRaceGetForbidden
const SessionPlayerRaceGetForbiddenCode int = 403

/*SessionPlayerRaceGetForbidden Access forbidden

swagger:response sessionPlayerRaceGetForbidden
*/
type SessionPlayerRaceGetForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerRaceGetForbidden creates SessionPlayerRaceGetForbidden with default headers values
func NewSessionPlayerRaceGetForbidden() *SessionPlayerRaceGetForbidden {

	return &SessionPlayerRaceGetForbidden{}
}

// WithPayload adds the payload to the session player race get forbidden response
func (o *SessionPlayerRaceGetForbidden) WithPayload(payload *models.Error) *SessionPlayerRaceGetForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race get forbidden response
func (o *SessionPlayerRaceGetForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceGetForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerRaceGetNotFoundCode is the HTTP code returned for type SessionPlayerRaceGetNotFound
const SessionPlayerRaceGetNotFoundCode int = 404

/*SessionPlayerRaceGetNotFound Resource not found

swagger:response sessionPlayerRaceGetNotFound
*/
type SessionPlayerRaceGetNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerRaceGetNotFound creates SessionPlayerRaceGetNotFound with default headers values
func NewSessionPlayerRaceGetNotFound() *SessionPlayerRaceGetNotFound {

	return &SessionPlayerRaceGetNotFound{}
}

// WithPayload adds the payload to the session player race get not found response
func (o *SessionPlayerRaceGetNotFound) WithPayload(payload *models.Error) *SessionPlayerRaceGetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race get not found response
func (o *SessionPlayerRaceGetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionPlayerRaceGetDefault Generic error response

swagger:response sessionPlayerRaceGetDefault
*/
type SessionPlayerRaceGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerRaceGetDefault creates SessionPlayerRaceGetDefault with default headers values
func NewSessionPlayerRaceGetDefault(code int) *SessionPlayerRaceGetDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionPlayerRaceGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session player race get default response
func (o *SessionPlayerRaceGetDefault) WithStatusCode(code int) *SessionPlayerRaceGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session player race get default response
func (o *SessionPlayerRaceGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session player race get default response
func (o *SessionPlayerRaceGetDefault) WithPayload(payload *models.Error) *SessionPlayerRaceGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race get default response
func (o *SessionPlayerRaceGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
