// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionCreateHandlerFunc turns a function with the right signature into a session create handler
type SessionCreateHandlerFunc func(SessionCreateParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionCreateHandlerFunc) Handle(params SessionCreateParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionCreateHandler interface for that can handle valid session create params
type SessionCreateHandler interface {
	Handle(SessionCreateParams, *models.Principal) middleware.Responder
}

// NewSessionCreate creates a new http.Handler for the session create operation
func NewSessionCreate(ctx *middleware.Context, handler SessionCreateHandler) *SessionCreate {
	return &SessionCreate{Context: ctx, Handler: handler}
}

/* SessionCreate swagger:route POST /v1/sessions sessionCreate

Creates a new session


*/
type SessionCreate struct {
	Context *middleware.Context
	Handler SessionCreateHandler
}

func (o *SessionCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionCreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
