// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// SessionPlayerRaceDeleteURL generates an URL for the session player race delete operation
type SessionPlayerRaceDeleteURL struct {
	PlayerRaceID string
	SessionID    string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SessionPlayerRaceDeleteURL) WithBasePath(bp string) *SessionPlayerRaceDeleteURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SessionPlayerRaceDeleteURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SessionPlayerRaceDeleteURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v1/sessions/{session_id}/player_race/{player_race_id}"

	playerRaceID := o.PlayerRaceID
	if playerRaceID != "" {
		_path = strings.Replace(_path, "{player_race_id}", playerRaceID, -1)
	} else {
		return nil, errors.New("playerRaceId is required on SessionPlayerRaceDeleteURL")
	}

	sessionID := o.SessionID
	if sessionID != "" {
		_path = strings.Replace(_path, "{session_id}", sessionID, -1)
	} else {
		return nil, errors.New("sessionId is required on SessionPlayerRaceDeleteURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SessionPlayerRaceDeleteURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SessionPlayerRaceDeleteURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SessionPlayerRaceDeleteURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SessionPlayerRaceDeleteURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SessionPlayerRaceDeleteURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SessionPlayerRaceDeleteURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
