// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionPlayerSwitchToHumanHandlerFunc turns a function with the right signature into a session player switch to human handler
type SessionPlayerSwitchToHumanHandlerFunc func(SessionPlayerSwitchToHumanParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionPlayerSwitchToHumanHandlerFunc) Handle(params SessionPlayerSwitchToHumanParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionPlayerSwitchToHumanHandler interface for that can handle valid session player switch to human params
type SessionPlayerSwitchToHumanHandler interface {
	Handle(SessionPlayerSwitchToHumanParams, *models.Principal) middleware.Responder
}

// NewSessionPlayerSwitchToHuman creates a new http.Handler for the session player switch to human operation
func NewSessionPlayerSwitchToHuman(ctx *middleware.Context, handler SessionPlayerSwitchToHumanHandler) *SessionPlayerSwitchToHuman {
	return &SessionPlayerSwitchToHuman{Context: ctx, Handler: handler}
}

/* SessionPlayerSwitchToHuman swagger:route POST /v1/sessions/{session_id}/player/{player_order}/switch_to_human sessionPlayerSwitchToHuman

switch an AI player back to human control

Switch an AI-controlled player back to human control by modifying the .hst file.
This is useful when a player returns to the game and wants to take back control
from the AI that was managing their position.

Preconditions:
- The game must be started (session files must exist)
- The player must currently be AI-controlled (ai_control_type is NOT NULL)
- The player must have a real user associated (not a bot slot)
- Only session managers or global managers can perform this action


*/
type SessionPlayerSwitchToHuman struct {
	Context *middleware.Context
	Handler SessionPlayerSwitchToHumanHandler
}

func (o *SessionPlayerSwitchToHuman) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionPlayerSwitchToHumanParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
