// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionsListHandlerFunc turns a function with the right signature into a sessions list handler
type SessionsListHandlerFunc func(SessionsListParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionsListHandlerFunc) Handle(params SessionsListParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionsListHandler interface for that can handle valid sessions list params
type SessionsListHandler interface {
	Handle(SessionsListParams, *models.Principal) middleware.Responder
}

// NewSessionsList creates a new http.Handler for the sessions list operation
func NewSessionsList(ctx *middleware.Context, handler SessionsListHandler) *SessionsList {
	return &SessionsList{Context: ctx, Handler: handler}
}

/* SessionsList swagger:route GET /v1/sessions sessionsList

SessionsList sessions list API

*/
type SessionsList struct {
	Context *middleware.Context
	Handler SessionsListHandler
}

func (o *SessionsList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionsListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
