// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionJoinOKCode is the HTTP code returned for type SessionJoinOK
const SessionJoinOKCode int = 200

/*SessionJoinOK the session that has been joined

swagger:response sessionJoinOK
*/
type SessionJoinOK struct {

	/*
	  In: Body
	*/
	Payload *models.Session `json:"body,omitempty"`
}

// NewSessionJoinOK creates SessionJoinOK with default headers values
func NewSessionJoinOK() *SessionJoinOK {

	return &SessionJoinOK{}
}

// WithPayload adds the payload to the session join o k response
func (o *SessionJoinOK) WithPayload(payload *models.Session) *SessionJoinOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session join o k response
func (o *SessionJoinOK) SetPayload(payload *models.Session) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionJoinOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionJoinBadRequestCode is the HTTP code returned for type SessionJoinBadRequest
const SessionJoinBadRequestCode int = 400

/*SessionJoinBadRequest invalid client request

swagger:response sessionJoinBadRequest
*/
type SessionJoinBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionJoinBadRequest creates SessionJoinBadRequest with default headers values
func NewSessionJoinBadRequest() *SessionJoinBadRequest {

	return &SessionJoinBadRequest{}
}

// WithPayload adds the payload to the session join bad request response
func (o *SessionJoinBadRequest) WithPayload(payload *models.Error) *SessionJoinBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session join bad request response
func (o *SessionJoinBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionJoinBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionJoinUnauthorizedCode is the HTTP code returned for type SessionJoinUnauthorized
const SessionJoinUnauthorizedCode int = 401

/*SessionJoinUnauthorized Invalid credentials

swagger:response sessionJoinUnauthorized
*/
type SessionJoinUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionJoinUnauthorized creates SessionJoinUnauthorized with default headers values
func NewSessionJoinUnauthorized() *SessionJoinUnauthorized {

	return &SessionJoinUnauthorized{}
}

// WithPayload adds the payload to the session join unauthorized response
func (o *SessionJoinUnauthorized) WithPayload(payload *models.Error) *SessionJoinUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session join unauthorized response
func (o *SessionJoinUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionJoinUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionJoinForbiddenCode is the HTTP code returned for type SessionJoinForbidden
const SessionJoinForbiddenCode int = 403

/*SessionJoinForbidden Access forbidden

swagger:response sessionJoinForbidden
*/
type SessionJoinForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionJoinForbidden creates SessionJoinForbidden with default headers values
func NewSessionJoinForbidden() *SessionJoinForbidden {

	return &SessionJoinForbidden{}
}

// WithPayload adds the payload to the session join forbidden response
func (o *SessionJoinForbidden) WithPayload(payload *models.Error) *SessionJoinForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session join forbidden response
func (o *SessionJoinForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionJoinForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionJoinPreconditionFailedCode is the HTTP code returned for type SessionJoinPreconditionFailed
const SessionJoinPreconditionFailedCode int = 412

/*SessionJoinPreconditionFailed Precondition not met

swagger:response sessionJoinPreconditionFailed
*/
type SessionJoinPreconditionFailed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionJoinPreconditionFailed creates SessionJoinPreconditionFailed with default headers values
func NewSessionJoinPreconditionFailed() *SessionJoinPreconditionFailed {

	return &SessionJoinPreconditionFailed{}
}

// WithPayload adds the payload to the session join precondition failed response
func (o *SessionJoinPreconditionFailed) WithPayload(payload *models.Error) *SessionJoinPreconditionFailed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session join precondition failed response
func (o *SessionJoinPreconditionFailed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionJoinPreconditionFailed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(412)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionJoinTooManyRequestsCode is the HTTP code returned for type SessionJoinTooManyRequests
const SessionJoinTooManyRequestsCode int = 429

/*SessionJoinTooManyRequests Limit exceeded

swagger:response sessionJoinTooManyRequests
*/
type SessionJoinTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionJoinTooManyRequests creates SessionJoinTooManyRequests with default headers values
func NewSessionJoinTooManyRequests() *SessionJoinTooManyRequests {

	return &SessionJoinTooManyRequests{}
}

// WithPayload adds the payload to the session join too many requests response
func (o *SessionJoinTooManyRequests) WithPayload(payload *models.Error) *SessionJoinTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session join too many requests response
func (o *SessionJoinTooManyRequests) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionJoinTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionJoinDefault Generic error response

swagger:response sessionJoinDefault
*/
type SessionJoinDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionJoinDefault creates SessionJoinDefault with default headers values
func NewSessionJoinDefault(code int) *SessionJoinDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionJoinDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session join default response
func (o *SessionJoinDefault) WithStatusCode(code int) *SessionJoinDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session join default response
func (o *SessionJoinDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session join default response
func (o *SessionJoinDefault) WithPayload(payload *models.Error) *SessionJoinDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session join default response
func (o *SessionJoinDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionJoinDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
