// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionFilesGetOKCode is the HTTP code returned for type SessionFilesGetOK
const SessionFilesGetOKCode int = 200

/*SessionFilesGetOK all session files for the latest turn

swagger:response sessionFilesGetOK
*/
type SessionFilesGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.SessionFiles `json:"body,omitempty"`
}

// NewSessionFilesGetOK creates SessionFilesGetOK with default headers values
func NewSessionFilesGetOK() *SessionFilesGetOK {

	return &SessionFilesGetOK{}
}

// WithPayload adds the payload to the session files get o k response
func (o *SessionFilesGetOK) WithPayload(payload *models.SessionFiles) *SessionFilesGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session files get o k response
func (o *SessionFilesGetOK) SetPayload(payload *models.SessionFiles) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionFilesGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionFilesGetUnauthorizedCode is the HTTP code returned for type SessionFilesGetUnauthorized
const SessionFilesGetUnauthorizedCode int = 401

/*SessionFilesGetUnauthorized Invalid credentials

swagger:response sessionFilesGetUnauthorized
*/
type SessionFilesGetUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionFilesGetUnauthorized creates SessionFilesGetUnauthorized with default headers values
func NewSessionFilesGetUnauthorized() *SessionFilesGetUnauthorized {

	return &SessionFilesGetUnauthorized{}
}

// WithPayload adds the payload to the session files get unauthorized response
func (o *SessionFilesGetUnauthorized) WithPayload(payload *models.Error) *SessionFilesGetUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session files get unauthorized response
func (o *SessionFilesGetUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionFilesGetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionFilesGetForbiddenCode is the HTTP code returned for type SessionFilesGetForbidden
const SessionFilesGetForbiddenCode int = 403

/*SessionFilesGetForbidden Access forbidden

swagger:response sessionFilesGetForbidden
*/
type SessionFilesGetForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionFilesGetForbidden creates SessionFilesGetForbidden with default headers values
func NewSessionFilesGetForbidden() *SessionFilesGetForbidden {

	return &SessionFilesGetForbidden{}
}

// WithPayload adds the payload to the session files get forbidden response
func (o *SessionFilesGetForbidden) WithPayload(payload *models.Error) *SessionFilesGetForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session files get forbidden response
func (o *SessionFilesGetForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionFilesGetForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionFilesGetNotFoundCode is the HTTP code returned for type SessionFilesGetNotFound
const SessionFilesGetNotFoundCode int = 404

/*SessionFilesGetNotFound Resource not found

swagger:response sessionFilesGetNotFound
*/
type SessionFilesGetNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionFilesGetNotFound creates SessionFilesGetNotFound with default headers values
func NewSessionFilesGetNotFound() *SessionFilesGetNotFound {

	return &SessionFilesGetNotFound{}
}

// WithPayload adds the payload to the session files get not found response
func (o *SessionFilesGetNotFound) WithPayload(payload *models.Error) *SessionFilesGetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session files get not found response
func (o *SessionFilesGetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionFilesGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionFilesGetDefault Generic error response

swagger:response sessionFilesGetDefault
*/
type SessionFilesGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionFilesGetDefault creates SessionFilesGetDefault with default headers values
func NewSessionFilesGetDefault(code int) *SessionFilesGetDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionFilesGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session files get default response
func (o *SessionFilesGetDefault) WithStatusCode(code int) *SessionFilesGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session files get default response
func (o *SessionFilesGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session files get default response
func (o *SessionFilesGetDefault) WithPayload(payload *models.Error) *SessionFilesGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session files get default response
func (o *SessionFilesGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionFilesGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
