// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/neper-stars/neper/models"
)

// NewSessionPlayerSwitchToAIParams creates a new SessionPlayerSwitchToAIParams object
//
// There are no default values defined in the spec.
func NewSessionPlayerSwitchToAIParams() SessionPlayerSwitchToAIParams {

	return SessionPlayerSwitchToAIParams{}
}

// SessionPlayerSwitchToAIParams contains all the bound params for the session player switch to a i operation
// typically these are obtained from a http.Request
//
// swagger:parameters sessionPlayerSwitchToAI
type SessionPlayerSwitchToAIParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  Maximum: 15
	  Minimum: 0
	  In: path
	*/
	PlayerOrder int64
	/*
	  Required: true
	  In: path
	*/
	SessionID string
	/*
	  Required: true
	  In: body
	*/
	SwitchRequest *models.SwitchToAiRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSessionPlayerSwitchToAIParams() beforehand.
func (o *SessionPlayerSwitchToAIParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPlayerOrder, rhkPlayerOrder, _ := route.Params.GetOK("player_order")
	if err := o.bindPlayerOrder(rPlayerOrder, rhkPlayerOrder, route.Formats); err != nil {
		res = append(res, err)
	}

	rSessionID, rhkSessionID, _ := route.Params.GetOK("session_id")
	if err := o.bindSessionID(rSessionID, rhkSessionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.SwitchToAiRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("switchRequest", "body", ""))
			} else {
				res = append(res, errors.NewParseError("switchRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.SwitchRequest = &body
			}
		}
	} else {
		res = append(res, errors.Required("switchRequest", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPlayerOrder binds and validates parameter PlayerOrder from path.
func (o *SessionPlayerSwitchToAIParams) bindPlayerOrder(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("player_order", "path", "int64", raw)
	}
	o.PlayerOrder = value

	if err := o.validatePlayerOrder(formats); err != nil {
		return err
	}

	return nil
}

// validatePlayerOrder carries on validations for parameter PlayerOrder
func (o *SessionPlayerSwitchToAIParams) validatePlayerOrder(formats strfmt.Registry) error {

	if err := validate.MinimumInt("player_order", "path", o.PlayerOrder, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("player_order", "path", o.PlayerOrder, 15, false); err != nil {
		return err
	}

	return nil
}

// bindSessionID binds and validates parameter SessionID from path.
func (o *SessionPlayerSwitchToAIParams) bindSessionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SessionID = raw

	return nil
}
