// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionPlayerRaceSetReadyOKCode is the HTTP code returned for type SessionPlayerRaceSetReadyOK
const SessionPlayerRaceSetReadyOKCode int = 200

/*SessionPlayerRaceSetReadyOK the updated session player race mapping

swagger:response sessionPlayerRaceSetReadyOK
*/
type SessionPlayerRaceSetReadyOK struct {

	/*
	  In: Body
	*/
	Payload *models.SessionPlayerRace `json:"body,omitempty"`
}

// NewSessionPlayerRaceSetReadyOK creates SessionPlayerRaceSetReadyOK with default headers values
func NewSessionPlayerRaceSetReadyOK() *SessionPlayerRaceSetReadyOK {

	return &SessionPlayerRaceSetReadyOK{}
}

// WithPayload adds the payload to the session player race set ready o k response
func (o *SessionPlayerRaceSetReadyOK) WithPayload(payload *models.SessionPlayerRace) *SessionPlayerRaceSetReadyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race set ready o k response
func (o *SessionPlayerRaceSetReadyOK) SetPayload(payload *models.SessionPlayerRace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceSetReadyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerRaceSetReadyBadRequestCode is the HTTP code returned for type SessionPlayerRaceSetReadyBadRequest
const SessionPlayerRaceSetReadyBadRequestCode int = 400

/*SessionPlayerRaceSetReadyBadRequest invalid client request

swagger:response sessionPlayerRaceSetReadyBadRequest
*/
type SessionPlayerRaceSetReadyBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerRaceSetReadyBadRequest creates SessionPlayerRaceSetReadyBadRequest with default headers values
func NewSessionPlayerRaceSetReadyBadRequest() *SessionPlayerRaceSetReadyBadRequest {

	return &SessionPlayerRaceSetReadyBadRequest{}
}

// WithPayload adds the payload to the session player race set ready bad request response
func (o *SessionPlayerRaceSetReadyBadRequest) WithPayload(payload *models.Error) *SessionPlayerRaceSetReadyBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race set ready bad request response
func (o *SessionPlayerRaceSetReadyBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceSetReadyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerRaceSetReadyUnauthorizedCode is the HTTP code returned for type SessionPlayerRaceSetReadyUnauthorized
const SessionPlayerRaceSetReadyUnauthorizedCode int = 401

/*SessionPlayerRaceSetReadyUnauthorized Invalid credentials

swagger:response sessionPlayerRaceSetReadyUnauthorized
*/
type SessionPlayerRaceSetReadyUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerRaceSetReadyUnauthorized creates SessionPlayerRaceSetReadyUnauthorized with default headers values
func NewSessionPlayerRaceSetReadyUnauthorized() *SessionPlayerRaceSetReadyUnauthorized {

	return &SessionPlayerRaceSetReadyUnauthorized{}
}

// WithPayload adds the payload to the session player race set ready unauthorized response
func (o *SessionPlayerRaceSetReadyUnauthorized) WithPayload(payload *models.Error) *SessionPlayerRaceSetReadyUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race set ready unauthorized response
func (o *SessionPlayerRaceSetReadyUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceSetReadyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionPlayerRaceSetReadyForbiddenCode is the HTTP code returned for type SessionPlayerRaceSetReadyForbidden
const SessionPlayerRaceSetReadyForbiddenCode int = 403

/*SessionPlayerRaceSetReadyForbidden Access forbidden

swagger:response sessionPlayerRaceSetReadyForbidden
*/
type SessionPlayerRaceSetReadyForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerRaceSetReadyForbidden creates SessionPlayerRaceSetReadyForbidden with default headers values
func NewSessionPlayerRaceSetReadyForbidden() *SessionPlayerRaceSetReadyForbidden {

	return &SessionPlayerRaceSetReadyForbidden{}
}

// WithPayload adds the payload to the session player race set ready forbidden response
func (o *SessionPlayerRaceSetReadyForbidden) WithPayload(payload *models.Error) *SessionPlayerRaceSetReadyForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race set ready forbidden response
func (o *SessionPlayerRaceSetReadyForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceSetReadyForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionPlayerRaceSetReadyDefault Generic error response

swagger:response sessionPlayerRaceSetReadyDefault
*/
type SessionPlayerRaceSetReadyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionPlayerRaceSetReadyDefault creates SessionPlayerRaceSetReadyDefault with default headers values
func NewSessionPlayerRaceSetReadyDefault(code int) *SessionPlayerRaceSetReadyDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionPlayerRaceSetReadyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session player race set ready default response
func (o *SessionPlayerRaceSetReadyDefault) WithStatusCode(code int) *SessionPlayerRaceSetReadyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session player race set ready default response
func (o *SessionPlayerRaceSetReadyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session player race set ready default response
func (o *SessionPlayerRaceSetReadyDefault) WithPayload(payload *models.Error) *SessionPlayerRaceSetReadyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session player race set ready default response
func (o *SessionPlayerRaceSetReadyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionPlayerRaceSetReadyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
