// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionReadHandlerFunc turns a function with the right signature into a session read handler
type SessionReadHandlerFunc func(SessionReadParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionReadHandlerFunc) Handle(params SessionReadParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionReadHandler interface for that can handle valid session read params
type SessionReadHandler interface {
	Handle(SessionReadParams, *models.Principal) middleware.Responder
}

// NewSessionRead creates a new http.Handler for the session read operation
func NewSessionRead(ctx *middleware.Context, handler SessionReadHandler) *SessionRead {
	return &SessionRead{Context: ctx, Handler: handler}
}

/* SessionRead swagger:route GET /v1/sessions/{session_id} sessionRead

Return the session.


*/
type SessionRead struct {
	Context *middleware.Context
	Handler SessionReadHandler
}

func (o *SessionRead) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionReadParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
