// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionPlayerRaceGetHandlerFunc turns a function with the right signature into a session player race get handler
type SessionPlayerRaceGetHandlerFunc func(SessionPlayerRaceGetParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionPlayerRaceGetHandlerFunc) Handle(params SessionPlayerRaceGetParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionPlayerRaceGetHandler interface for that can handle valid session player race get params
type SessionPlayerRaceGetHandler interface {
	Handle(SessionPlayerRaceGetParams, *models.Principal) middleware.Responder
}

// NewSessionPlayerRaceGet creates a new http.Handler for the session player race get operation
func NewSessionPlayerRaceGet(ctx *middleware.Context, handler SessionPlayerRaceGetHandler) *SessionPlayerRaceGet {
	return &SessionPlayerRaceGet{Context: ctx, Handler: handler}
}

/* SessionPlayerRaceGet swagger:route GET /v1/sessions/{session_id}/player_race sessionPlayerRaceGet

get your race file for this session

Returns the race file (.r1 format, base64 encoded) that you have set for this session.
This allows you to download your race configuration for the current session.


*/
type SessionPlayerRaceGet struct {
	Context *middleware.Context
	Handler SessionPlayerRaceGetHandler
}

func (o *SessionPlayerRaceGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionPlayerRaceGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
