// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionReadOKCode is the HTTP code returned for type SessionReadOK
const SessionReadOKCode int = 200

/*SessionReadOK the session

swagger:response sessionReadOK
*/
type SessionReadOK struct {

	/*
	  In: Body
	*/
	Payload *models.Session `json:"body,omitempty"`
}

// NewSessionReadOK creates SessionReadOK with default headers values
func NewSessionReadOK() *SessionReadOK {

	return &SessionReadOK{}
}

// WithPayload adds the payload to the session read o k response
func (o *SessionReadOK) WithPayload(payload *models.Session) *SessionReadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session read o k response
func (o *SessionReadOK) SetPayload(payload *models.Session) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionReadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionReadUnauthorizedCode is the HTTP code returned for type SessionReadUnauthorized
const SessionReadUnauthorizedCode int = 401

/*SessionReadUnauthorized Invalid credentials

swagger:response sessionReadUnauthorized
*/
type SessionReadUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionReadUnauthorized creates SessionReadUnauthorized with default headers values
func NewSessionReadUnauthorized() *SessionReadUnauthorized {

	return &SessionReadUnauthorized{}
}

// WithPayload adds the payload to the session read unauthorized response
func (o *SessionReadUnauthorized) WithPayload(payload *models.Error) *SessionReadUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session read unauthorized response
func (o *SessionReadUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionReadUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionReadForbiddenCode is the HTTP code returned for type SessionReadForbidden
const SessionReadForbiddenCode int = 403

/*SessionReadForbidden Access forbidden

swagger:response sessionReadForbidden
*/
type SessionReadForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionReadForbidden creates SessionReadForbidden with default headers values
func NewSessionReadForbidden() *SessionReadForbidden {

	return &SessionReadForbidden{}
}

// WithPayload adds the payload to the session read forbidden response
func (o *SessionReadForbidden) WithPayload(payload *models.Error) *SessionReadForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session read forbidden response
func (o *SessionReadForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionReadForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionReadDefault Generic error response

swagger:response sessionReadDefault
*/
type SessionReadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionReadDefault creates SessionReadDefault with default headers values
func NewSessionReadDefault(code int) *SessionReadDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionReadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session read default response
func (o *SessionReadDefault) WithStatusCode(code int) *SessionReadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session read default response
func (o *SessionReadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session read default response
func (o *SessionReadDefault) WithPayload(payload *models.Error) *SessionReadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session read default response
func (o *SessionReadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionReadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
