// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionFilesGetHandlerFunc turns a function with the right signature into a session files get handler
type SessionFilesGetHandlerFunc func(SessionFilesGetParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionFilesGetHandlerFunc) Handle(params SessionFilesGetParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionFilesGetHandler interface for that can handle valid session files get params
type SessionFilesGetHandler interface {
	Handle(SessionFilesGetParams, *models.Principal) middleware.Responder
}

// NewSessionFilesGet creates a new http.Handler for the session files get operation
func NewSessionFilesGet(ctx *middleware.Context, handler SessionFilesGetHandler) *SessionFilesGet {
	return &SessionFilesGet{Context: ctx, Handler: handler}
}

/* SessionFilesGet swagger:route GET /v1/sessions/{session_id}/files sessionFilesGet

get all session files (managers only)

Returns all session files for the current/latest turn including the host file (.hst),
universe file (.xy), all player turn files (.mN), and all order files (.xN).
This endpoint is restricted to session managers and global managers only.
Regular players should use the /turn/latest endpoint to get their own turn file.


*/
type SessionFilesGet struct {
	Context *middleware.Context
	Handler SessionFilesGetHandler
}

func (o *SessionFilesGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionFilesGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
