// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionPlayerRaceCreateHandlerFunc turns a function with the right signature into a session player race create handler
type SessionPlayerRaceCreateHandlerFunc func(SessionPlayerRaceCreateParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionPlayerRaceCreateHandlerFunc) Handle(params SessionPlayerRaceCreateParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionPlayerRaceCreateHandler interface for that can handle valid session player race create params
type SessionPlayerRaceCreateHandler interface {
	Handle(SessionPlayerRaceCreateParams, *models.Principal) middleware.Responder
}

// NewSessionPlayerRaceCreate creates a new http.Handler for the session player race create operation
func NewSessionPlayerRaceCreate(ctx *middleware.Context, handler SessionPlayerRaceCreateHandler) *SessionPlayerRaceCreate {
	return &SessionPlayerRaceCreate{Context: ctx, Handler: handler}
}

/* SessionPlayerRaceCreate swagger:route POST /v1/sessions/{session_id}/player_race sessionPlayerRaceCreate

set the race with which you will be competing in this session

You will have to reference a previously uploaded race definition to indicate the host the race file
you will be using for this session.
If you are the host you will be able to change all races (in order to set some races for the bots)
You will also be able to determine the player order.
Players are not authorized to set their own order and an attempt to set this field will be ignored.


*/
type SessionPlayerRaceCreate struct {
	Context *middleware.Context
	Handler SessionPlayerRaceCreateHandler
}

func (o *SessionPlayerRaceCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionPlayerRaceCreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
