// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionPlayerRaceDeleteHandlerFunc turns a function with the right signature into a session player race delete handler
type SessionPlayerRaceDeleteHandlerFunc func(SessionPlayerRaceDeleteParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionPlayerRaceDeleteHandlerFunc) Handle(params SessionPlayerRaceDeleteParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionPlayerRaceDeleteHandler interface for that can handle valid session player race delete params
type SessionPlayerRaceDeleteHandler interface {
	Handle(SessionPlayerRaceDeleteParams, *models.Principal) middleware.Responder
}

// NewSessionPlayerRaceDelete creates a new http.Handler for the session player race delete operation
func NewSessionPlayerRaceDelete(ctx *middleware.Context, handler SessionPlayerRaceDeleteHandler) *SessionPlayerRaceDelete {
	return &SessionPlayerRaceDelete{Context: ctx, Handler: handler}
}

/* SessionPlayerRaceDelete swagger:route DELETE /v1/sessions/{session_id}/player_race/{player_race_id} sessionPlayerRaceDelete

remove a player from a session

Remove a player race mapping from a session.

Authorization rules:
- Session managers and global managers can remove anyone, including bots
- Regular users can only remove themselves

Removal rules:
- Human players (non-bots) must not be ready to be removed
- Bots can be removed regardless of their ready status


*/
type SessionPlayerRaceDelete struct {
	Context *middleware.Context
	Handler SessionPlayerRaceDeleteHandler
}

func (o *SessionPlayerRaceDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionPlayerRaceDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
