// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionInviteCreatedCode is the HTTP code returned for type SessionInviteCreated
const SessionInviteCreatedCode int = 201

/*SessionInviteCreated the invitation that has just been created

swagger:response sessionInviteCreated
*/
type SessionInviteCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Invitation `json:"body,omitempty"`
}

// NewSessionInviteCreated creates SessionInviteCreated with default headers values
func NewSessionInviteCreated() *SessionInviteCreated {

	return &SessionInviteCreated{}
}

// WithPayload adds the payload to the session invite created response
func (o *SessionInviteCreated) WithPayload(payload *models.Invitation) *SessionInviteCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session invite created response
func (o *SessionInviteCreated) SetPayload(payload *models.Invitation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionInviteCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionInviteBadRequestCode is the HTTP code returned for type SessionInviteBadRequest
const SessionInviteBadRequestCode int = 400

/*SessionInviteBadRequest invalid client request

swagger:response sessionInviteBadRequest
*/
type SessionInviteBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionInviteBadRequest creates SessionInviteBadRequest with default headers values
func NewSessionInviteBadRequest() *SessionInviteBadRequest {

	return &SessionInviteBadRequest{}
}

// WithPayload adds the payload to the session invite bad request response
func (o *SessionInviteBadRequest) WithPayload(payload *models.Error) *SessionInviteBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session invite bad request response
func (o *SessionInviteBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionInviteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionInviteUnauthorizedCode is the HTTP code returned for type SessionInviteUnauthorized
const SessionInviteUnauthorizedCode int = 401

/*SessionInviteUnauthorized Invalid credentials

swagger:response sessionInviteUnauthorized
*/
type SessionInviteUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionInviteUnauthorized creates SessionInviteUnauthorized with default headers values
func NewSessionInviteUnauthorized() *SessionInviteUnauthorized {

	return &SessionInviteUnauthorized{}
}

// WithPayload adds the payload to the session invite unauthorized response
func (o *SessionInviteUnauthorized) WithPayload(payload *models.Error) *SessionInviteUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session invite unauthorized response
func (o *SessionInviteUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionInviteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionInviteForbiddenCode is the HTTP code returned for type SessionInviteForbidden
const SessionInviteForbiddenCode int = 403

/*SessionInviteForbidden Access forbidden

swagger:response sessionInviteForbidden
*/
type SessionInviteForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionInviteForbidden creates SessionInviteForbidden with default headers values
func NewSessionInviteForbidden() *SessionInviteForbidden {

	return &SessionInviteForbidden{}
}

// WithPayload adds the payload to the session invite forbidden response
func (o *SessionInviteForbidden) WithPayload(payload *models.Error) *SessionInviteForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session invite forbidden response
func (o *SessionInviteForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionInviteForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionInviteDefault Generic error response

swagger:response sessionInviteDefault
*/
type SessionInviteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionInviteDefault creates SessionInviteDefault with default headers values
func NewSessionInviteDefault(code int) *SessionInviteDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionInviteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session invite default response
func (o *SessionInviteDefault) WithStatusCode(code int) *SessionInviteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session invite default response
func (o *SessionInviteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session invite default response
func (o *SessionInviteDefault) WithPayload(payload *models.Error) *SessionInviteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session invite default response
func (o *SessionInviteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionInviteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
