// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// SessionInviteHandlerFunc turns a function with the right signature into a session invite handler
type SessionInviteHandlerFunc func(SessionInviteParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionInviteHandlerFunc) Handle(params SessionInviteParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SessionInviteHandler interface for that can handle valid session invite params
type SessionInviteHandler interface {
	Handle(SessionInviteParams, *models.Principal) middleware.Responder
}

// NewSessionInvite creates a new http.Handler for the session invite operation
func NewSessionInvite(ctx *middleware.Context, handler SessionInviteHandler) *SessionInvite {
	return &SessionInvite{Context: ctx, Handler: handler}
}

/* SessionInvite swagger:route POST /v1/sessions/{session_id}/invite sessionInvite

invite a player to a session. You can do this if you are the manager of this session.

invite a player to the session

*/
type SessionInvite struct {
	Context *middleware.Context
	Handler SessionInviteHandler
}

func (o *SessionInvite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSessionInviteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
