// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionCreateCreatedCode is the HTTP code returned for type SessionCreateCreated
const SessionCreateCreatedCode int = 201

/*SessionCreateCreated the created session

swagger:response sessionCreateCreated
*/
type SessionCreateCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Session `json:"body,omitempty"`
}

// NewSessionCreateCreated creates SessionCreateCreated with default headers values
func NewSessionCreateCreated() *SessionCreateCreated {

	return &SessionCreateCreated{}
}

// WithPayload adds the payload to the session create created response
func (o *SessionCreateCreated) WithPayload(payload *models.Session) *SessionCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session create created response
func (o *SessionCreateCreated) SetPayload(payload *models.Session) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionCreateUnauthorizedCode is the HTTP code returned for type SessionCreateUnauthorized
const SessionCreateUnauthorizedCode int = 401

/*SessionCreateUnauthorized Invalid credentials

swagger:response sessionCreateUnauthorized
*/
type SessionCreateUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionCreateUnauthorized creates SessionCreateUnauthorized with default headers values
func NewSessionCreateUnauthorized() *SessionCreateUnauthorized {

	return &SessionCreateUnauthorized{}
}

// WithPayload adds the payload to the session create unauthorized response
func (o *SessionCreateUnauthorized) WithPayload(payload *models.Error) *SessionCreateUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session create unauthorized response
func (o *SessionCreateUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionCreateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionCreateForbiddenCode is the HTTP code returned for type SessionCreateForbidden
const SessionCreateForbiddenCode int = 403

/*SessionCreateForbidden Access forbidden

swagger:response sessionCreateForbidden
*/
type SessionCreateForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionCreateForbidden creates SessionCreateForbidden with default headers values
func NewSessionCreateForbidden() *SessionCreateForbidden {

	return &SessionCreateForbidden{}
}

// WithPayload adds the payload to the session create forbidden response
func (o *SessionCreateForbidden) WithPayload(payload *models.Error) *SessionCreateForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session create forbidden response
func (o *SessionCreateForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionCreateForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionCreateDefault Generic error response

swagger:response sessionCreateDefault
*/
type SessionCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionCreateDefault creates SessionCreateDefault with default headers values
func NewSessionCreateDefault(code int) *SessionCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session create default response
func (o *SessionCreateDefault) WithStatusCode(code int) *SessionCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session create default response
func (o *SessionCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session create default response
func (o *SessionCreateDefault) WithPayload(payload *models.Error) *SessionCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session create default response
func (o *SessionCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
