// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// SessionDeleteNoContentCode is the HTTP code returned for type SessionDeleteNoContent
const SessionDeleteNoContentCode int = 204

/*SessionDeleteNoContent session deleted successfully

swagger:response sessionDeleteNoContent
*/
type SessionDeleteNoContent struct {
}

// NewSessionDeleteNoContent creates SessionDeleteNoContent with default headers values
func NewSessionDeleteNoContent() *SessionDeleteNoContent {

	return &SessionDeleteNoContent{}
}

// WriteResponse to the client
func (o *SessionDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// SessionDeleteUnauthorizedCode is the HTTP code returned for type SessionDeleteUnauthorized
const SessionDeleteUnauthorizedCode int = 401

/*SessionDeleteUnauthorized Invalid credentials

swagger:response sessionDeleteUnauthorized
*/
type SessionDeleteUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionDeleteUnauthorized creates SessionDeleteUnauthorized with default headers values
func NewSessionDeleteUnauthorized() *SessionDeleteUnauthorized {

	return &SessionDeleteUnauthorized{}
}

// WithPayload adds the payload to the session delete unauthorized response
func (o *SessionDeleteUnauthorized) WithPayload(payload *models.Error) *SessionDeleteUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session delete unauthorized response
func (o *SessionDeleteUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionDeleteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionDeleteForbiddenCode is the HTTP code returned for type SessionDeleteForbidden
const SessionDeleteForbiddenCode int = 403

/*SessionDeleteForbidden Access forbidden

swagger:response sessionDeleteForbidden
*/
type SessionDeleteForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionDeleteForbidden creates SessionDeleteForbidden with default headers values
func NewSessionDeleteForbidden() *SessionDeleteForbidden {

	return &SessionDeleteForbidden{}
}

// WithPayload adds the payload to the session delete forbidden response
func (o *SessionDeleteForbidden) WithPayload(payload *models.Error) *SessionDeleteForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session delete forbidden response
func (o *SessionDeleteForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionDeleteForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SessionDeleteNotFoundCode is the HTTP code returned for type SessionDeleteNotFound
const SessionDeleteNotFoundCode int = 404

/*SessionDeleteNotFound Resource not found

swagger:response sessionDeleteNotFound
*/
type SessionDeleteNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionDeleteNotFound creates SessionDeleteNotFound with default headers values
func NewSessionDeleteNotFound() *SessionDeleteNotFound {

	return &SessionDeleteNotFound{}
}

// WithPayload adds the payload to the session delete not found response
func (o *SessionDeleteNotFound) WithPayload(payload *models.Error) *SessionDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session delete not found response
func (o *SessionDeleteNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SessionDeleteDefault Generic error response

swagger:response sessionDeleteDefault
*/
type SessionDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSessionDeleteDefault creates SessionDeleteDefault with default headers values
func NewSessionDeleteDefault(code int) *SessionDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &SessionDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the session delete default response
func (o *SessionDeleteDefault) WithStatusCode(code int) *SessionDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the session delete default response
func (o *SessionDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the session delete default response
func (o *SessionDeleteDefault) WithPayload(payload *models.Error) *SessionDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the session delete default response
func (o *SessionDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SessionDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
