// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// TurnLatestHandlerFunc turns a function with the right signature into a turn latest handler
type TurnLatestHandlerFunc func(TurnLatestParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn TurnLatestHandlerFunc) Handle(params TurnLatestParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// TurnLatestHandler interface for that can handle valid turn latest params
type TurnLatestHandler interface {
	Handle(TurnLatestParams, *models.Principal) middleware.Responder
}

// NewTurnLatest creates a new http.Handler for the turn latest operation
func NewTurnLatest(ctx *middleware.Context, handler TurnLatestHandler) *TurnLatest {
	return &TurnLatest{Context: ctx, Handler: handler}
}

/* TurnLatest swagger:route GET /v1/sessions/{session_id}/turn/latest turnLatest

get the latest turn for this session

Returns the turn files for the most recent turn (highest year) in this session.
This is useful for clients that want to fetch the current turn without knowing the year.
You will get a turn_files structure containing the Universe file (.xy) data in a base64 encoded field
and the Turn file (.mN) data in a base64 encoded field.


*/
type TurnLatest struct {
	Context *middleware.Context
	Handler TurnLatestHandler
}

func (o *TurnLatest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewTurnLatestParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
