// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/neper-stars/neper/models"
)

// NewTurnSubmitParams creates a new TurnSubmitParams object
//
// There are no default values defined in the spec.
func NewTurnSubmitParams() TurnSubmitParams {

	return TurnSubmitParams{}
}

// TurnSubmitParams contains all the bound params for the turn submit operation
// typically these are obtained from a http.Request
//
// swagger:parameters turnSubmit
type TurnSubmitParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	SessionID string
	/*
	  In: body
	*/
	Turnfile *models.Order
	/*
	  Required: true
	  In: path
	*/
	Year int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTurnSubmitParams() beforehand.
func (o *TurnSubmitParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSessionID, rhkSessionID, _ := route.Params.GetOK("session_id")
	if err := o.bindSessionID(rSessionID, rhkSessionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Order
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("turnfile", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Turnfile = &body
			}
		}
	}

	rYear, rhkYear, _ := route.Params.GetOK("year")
	if err := o.bindYear(rYear, rhkYear, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSessionID binds and validates parameter SessionID from path.
func (o *TurnSubmitParams) bindSessionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SessionID = raw

	return nil
}

// bindYear binds and validates parameter Year from path.
func (o *TurnSubmitParams) bindYear(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("year", "path", "int64", raw)
	}
	o.Year = value

	return nil
}
