// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// TurnGetOKCode is the HTTP code returned for type TurnGetOK
const TurnGetOKCode int = 200

/*TurnGetOK the returned player turn

swagger:response turnGetOK
*/
type TurnGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.TurnFiles `json:"body,omitempty"`
}

// NewTurnGetOK creates TurnGetOK with default headers values
func NewTurnGetOK() *TurnGetOK {

	return &TurnGetOK{}
}

// WithPayload adds the payload to the turn get o k response
func (o *TurnGetOK) WithPayload(payload *models.TurnFiles) *TurnGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the turn get o k response
func (o *TurnGetOK) SetPayload(payload *models.TurnFiles) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TurnGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// TurnGetUnauthorizedCode is the HTTP code returned for type TurnGetUnauthorized
const TurnGetUnauthorizedCode int = 401

/*TurnGetUnauthorized Invalid credentials

swagger:response turnGetUnauthorized
*/
type TurnGetUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTurnGetUnauthorized creates TurnGetUnauthorized with default headers values
func NewTurnGetUnauthorized() *TurnGetUnauthorized {

	return &TurnGetUnauthorized{}
}

// WithPayload adds the payload to the turn get unauthorized response
func (o *TurnGetUnauthorized) WithPayload(payload *models.Error) *TurnGetUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the turn get unauthorized response
func (o *TurnGetUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TurnGetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// TurnGetForbiddenCode is the HTTP code returned for type TurnGetForbidden
const TurnGetForbiddenCode int = 403

/*TurnGetForbidden Access forbidden

swagger:response turnGetForbidden
*/
type TurnGetForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTurnGetForbidden creates TurnGetForbidden with default headers values
func NewTurnGetForbidden() *TurnGetForbidden {

	return &TurnGetForbidden{}
}

// WithPayload adds the payload to the turn get forbidden response
func (o *TurnGetForbidden) WithPayload(payload *models.Error) *TurnGetForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the turn get forbidden response
func (o *TurnGetForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TurnGetForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
