// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// UserProfileResetApikeyHandlerFunc turns a function with the right signature into a user profile reset apikey handler
type UserProfileResetApikeyHandlerFunc func(UserProfileResetApikeyParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UserProfileResetApikeyHandlerFunc) Handle(params UserProfileResetApikeyParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UserProfileResetApikeyHandler interface for that can handle valid user profile reset apikey params
type UserProfileResetApikeyHandler interface {
	Handle(UserProfileResetApikeyParams, *models.Principal) middleware.Responder
}

// NewUserProfileResetApikey creates a new http.Handler for the user profile reset apikey operation
func NewUserProfileResetApikey(ctx *middleware.Context, handler UserProfileResetApikeyHandler) *UserProfileResetApikey {
	return &UserProfileResetApikey{Context: ctx, Handler: handler}
}

/* UserProfileResetApikey swagger:route POST /v1/user_profiles/{user_profile_id}/reset_apikey userProfileResetApikey

reset the API key for a user

Generate a new random API key for the specified user.
A user can reset their own API key, or a manager can reset any user's API key.


*/
type UserProfileResetApikey struct {
	Context *middleware.Context
	Handler UserProfileResetApikeyHandler
}

func (o *UserProfileResetApikey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUserProfileResetApikeyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
