// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"bytes"
	"io"
	"io/ioutil"
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// UserProfileCreateHandlerFunc turns a function with the right signature into a user profile create handler
type UserProfileCreateHandlerFunc func(UserProfileCreateParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UserProfileCreateHandlerFunc) Handle(params UserProfileCreateParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UserProfileCreateHandler interface for that can handle valid user profile create params
type UserProfileCreateHandler interface {
	Handle(UserProfileCreateParams, *models.Principal) middleware.Responder
}

// NewUserProfileCreate creates a new http.Handler for the user profile create operation
func NewUserProfileCreate(ctx *middleware.Context, handler UserProfileCreateHandler) *UserProfileCreate {
	return &UserProfileCreate{Context: ctx, Handler: handler}
}

/* UserProfileCreate swagger:route POST /v1/user_profiles userProfileCreate

Creates a user profile.


*/
type UserProfileCreate struct {
	Context *middleware.Context
	Handler UserProfileCreateHandler
}

func (o *UserProfileCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}

	var Params = NewUserProfileCreateParams()
	var bodyExists bool
	var body []byte
	if r.Body != nil {
		var err error
		bodyExists = true
		body, err = io.ReadAll(r.Body)
		if err != nil {
			o.Context.Respond(rw, r, route.Produces, route, err)
			return
		}
		r.Body = ioutil.NopCloser(bytes.NewReader(body))
	}
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	if bodyExists {
		// restore body
		r.Body = ioutil.NopCloser(bytes.NewReader(body))
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
