// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// UserProfileListOKCode is the HTTP code returned for type UserProfileListOK
const UserProfileListOKCode int = 200

/*UserProfileListOK the complete list of user profiles

swagger:response userProfileListOK
*/
type UserProfileListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.UserProfile `json:"body,omitempty"`
}

// NewUserProfileListOK creates UserProfileListOK with default headers values
func NewUserProfileListOK() *UserProfileListOK {

	return &UserProfileListOK{}
}

// WithPayload adds the payload to the user profile list o k response
func (o *UserProfileListOK) WithPayload(payload []*models.UserProfile) *UserProfileListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user profile list o k response
func (o *UserProfileListOK) SetPayload(payload []*models.UserProfile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserProfileListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.UserProfile, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// UserProfileListUnauthorizedCode is the HTTP code returned for type UserProfileListUnauthorized
const UserProfileListUnauthorizedCode int = 401

/*UserProfileListUnauthorized Invalid credentials

swagger:response userProfileListUnauthorized
*/
type UserProfileListUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUserProfileListUnauthorized creates UserProfileListUnauthorized with default headers values
func NewUserProfileListUnauthorized() *UserProfileListUnauthorized {

	return &UserProfileListUnauthorized{}
}

// WithPayload adds the payload to the user profile list unauthorized response
func (o *UserProfileListUnauthorized) WithPayload(payload *models.Error) *UserProfileListUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user profile list unauthorized response
func (o *UserProfileListUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserProfileListUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserProfileListForbiddenCode is the HTTP code returned for type UserProfileListForbidden
const UserProfileListForbiddenCode int = 403

/*UserProfileListForbidden Access forbidden

swagger:response userProfileListForbidden
*/
type UserProfileListForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUserProfileListForbidden creates UserProfileListForbidden with default headers values
func NewUserProfileListForbidden() *UserProfileListForbidden {

	return &UserProfileListForbidden{}
}

// WithPayload adds the payload to the user profile list forbidden response
func (o *UserProfileListForbidden) WithPayload(payload *models.Error) *UserProfileListForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user profile list forbidden response
func (o *UserProfileListForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserProfileListForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
