// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/neper-stars/neper/models"
)

// UserProfileDeleteHandlerFunc turns a function with the right signature into a user profile delete handler
type UserProfileDeleteHandlerFunc func(UserProfileDeleteParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UserProfileDeleteHandlerFunc) Handle(params UserProfileDeleteParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UserProfileDeleteHandler interface for that can handle valid user profile delete params
type UserProfileDeleteHandler interface {
	Handle(UserProfileDeleteParams, *models.Principal) middleware.Responder
}

// NewUserProfileDelete creates a new http.Handler for the user profile delete operation
func NewUserProfileDelete(ctx *middleware.Context, handler UserProfileDeleteHandler) *UserProfileDelete {
	return &UserProfileDelete{Context: ctx, Handler: handler}
}

/* UserProfileDelete swagger:route DELETE /v1/user_profiles/{user_profile_id} userProfileDelete

Delete a user profile. Only global managers can delete user profiles.
Returns 409 Conflict if the user is a member of any session.


*/
type UserProfileDelete struct {
	Context *middleware.Context
	Handler UserProfileDeleteHandler
}

func (o *UserProfileDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUserProfileDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
