// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/neper-stars/neper/models"
)

// UserProfileReadOKCode is the HTTP code returned for type UserProfileReadOK
const UserProfileReadOKCode int = 200

/*UserProfileReadOK the user profile

swagger:response userProfileReadOK
*/
type UserProfileReadOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserProfile `json:"body,omitempty"`
}

// NewUserProfileReadOK creates UserProfileReadOK with default headers values
func NewUserProfileReadOK() *UserProfileReadOK {

	return &UserProfileReadOK{}
}

// WithPayload adds the payload to the user profile read o k response
func (o *UserProfileReadOK) WithPayload(payload *models.UserProfile) *UserProfileReadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user profile read o k response
func (o *UserProfileReadOK) SetPayload(payload *models.UserProfile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserProfileReadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserProfileReadUnauthorizedCode is the HTTP code returned for type UserProfileReadUnauthorized
const UserProfileReadUnauthorizedCode int = 401

/*UserProfileReadUnauthorized Invalid credentials

swagger:response userProfileReadUnauthorized
*/
type UserProfileReadUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUserProfileReadUnauthorized creates UserProfileReadUnauthorized with default headers values
func NewUserProfileReadUnauthorized() *UserProfileReadUnauthorized {

	return &UserProfileReadUnauthorized{}
}

// WithPayload adds the payload to the user profile read unauthorized response
func (o *UserProfileReadUnauthorized) WithPayload(payload *models.Error) *UserProfileReadUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user profile read unauthorized response
func (o *UserProfileReadUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserProfileReadUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserProfileReadForbiddenCode is the HTTP code returned for type UserProfileReadForbidden
const UserProfileReadForbiddenCode int = 403

/*UserProfileReadForbidden Access forbidden

swagger:response userProfileReadForbidden
*/
type UserProfileReadForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUserProfileReadForbidden creates UserProfileReadForbidden with default headers values
func NewUserProfileReadForbidden() *UserProfileReadForbidden {

	return &UserProfileReadForbidden{}
}

// WithPayload adds the payload to the user profile read forbidden response
func (o *UserProfileReadForbidden) WithPayload(payload *models.Error) *UserProfileReadForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user profile read forbidden response
func (o *UserProfileReadForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserProfileReadForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
