// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Neper API
//
//  The Neper API
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /api
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/zip
//    - application/octet-stream
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
