package embeddednats

import (
	"fmt"

	"github.com/nats-io/nkeys"
	"github.com/rs/zerolog"
)

type ClientOptions struct {
	Url      string `long:"nats-url" env:"NATS_SERVER_URL" ini-name:"nats-url" description:"nats server url for service communications." default:"nats://localhost:4222"`
	NPrivkey string `long:"nkey" env:"NATS_CLIENT_NKEY" ini-name:"nkey" description:"private part of the nKey to connect to the nats server. Begins with an S"`
}

func (c *ClientOptions) NPrivateKey(log zerolog.Logger) ([]byte, error) {
	if c.NPrivkey != "" {
		return []byte(c.NPrivkey), nil
	}

	log.Warn().Msg("no NKey given in config, using an autogenerated one, if using an external Nats server this will fail!!")
	// else auto generate
	var kp nkeys.KeyPair
	var err error

	kp, err = nkeys.CreateUser()
	if err != nil {
		return nil, fmt.Errorf("failed to create key: %w", err)
	}
	seed, err := kp.Seed()
	if err != nil {
		return nil, fmt.Errorf("failed to get seed: %w", err)
	}

	return seed, nil
}

func NewNatsClientOptions() *ClientOptions {
	options := ClientOptions{}
	return &options
}
