package types

// This file was generated originally generated by the swagger tool.
// this was then moved to the types package to embed in a TurnList
// that knows how to serialize in postgresql JSONB

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Turn a turn file for a specific player.
// This is the binary file from the game: .mN file
// The data is encoded in base64.
//
// swagger:model turn
type Turn struct {

	// b64 data
	// Required: true
	B64Data string `json:"b64_data"`
}

// Validate validates this turn
func (m *Turn) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateB64Data(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Turn) validateB64Data(formats strfmt.Registry) error {
	if err := validate.RequiredString("b64_data", "body", m.B64Data); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this turn based on context it is used
func (m *Turn) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Turn) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Turn) UnmarshalBinary(b []byte) error {
	var res Turn
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
