// Code generated by go-swagger/go-orusapi; DO NOT EDIT.

package cmd

import (
	"fmt"

	"github.com/neper-stars/neper/restapi"
)

// VersionCmd is the "version" command
type VersionCmd struct{}

// Execute the 'version' commands
func (cmd *VersionCmd) Execute([]string) error {
	fmt.Println("Neper " + restapi.GetVersion())
	return nil
}

func init() {
	if _, err := parser.AddCommand("version", "Print the program version", "", &VersionCmd{}); err != nil {
		Logger.Fatal().Err(err).Msg("error adding command")
	}
}
