// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderStatusMeta Metadata for order_status notifications
//
// swagger:model OrderStatusMeta
type OrderStatusMeta struct {

	// The game year for which orders were submitted
	Year int64 `json:"year,omitempty"`
}

// Validate validates this order status meta
func (m *OrderStatusMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this order status meta based on context it is used
func (m *OrderStatusMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderStatusMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderStatusMeta) UnmarshalBinary(b []byte) error {
	var res OrderStatusMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
