// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlayerControlMeta Metadata for player_control notifications.
// Sent when a player's control status changes (human to AI or AI to human).
// Only session managers receive these notifications.
//
//
// swagger:model PlayerControlMeta
type PlayerControlMeta struct {

	// The new AI control type (null if switched to human, AI type code if switched to AI)
	AIControlType *string `json:"ai_control_type,omitempty"`

	// The session ID where the control change occurred
	SessionID string `json:"session_id,omitempty"`

	// The player order (0-indexed) of the affected player
	PlayerOrder int64 `json:"player_order,omitempty"`
}

// Validate validates this player control meta
func (m *PlayerControlMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this player control meta based on context it is used
func (m *PlayerControlMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlayerControlMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlayerControlMeta) UnmarshalBinary(b []byte) error {
	var res PlayerControlMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
