// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegistrationApprovalMeta Metadata for pending_registration approval notifications.
// Allows the approved user and admins to receive relevant info.
//
//
// swagger:model RegistrationApprovalMeta
type RegistrationApprovalMeta struct {

	// The user profile ID that was approved
	UserProfileID string `json:"user_profile_id,omitempty"`

	// The nickname of the approved user
	Nickname string `json:"nickname,omitempty"`
}

// Validate validates this registration approval meta
func (m *RegistrationApprovalMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this registration approval meta based on context it is used
func (m *RegistrationApprovalMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegistrationApprovalMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistrationApprovalMeta) UnmarshalBinary(b []byte) error {
	var res RegistrationApprovalMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
