// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResourceChange Base message format for all WebSocket notifications.
// Sent when resources the user has access to are modified.
//
//
// swagger:model ResourceChange
type ResourceChange struct {

	// The action performed on the resource
	// Required: true
	// Enum: [created updated deleted ready member_left approved rejected]
	Action *string `json:"action"`

	// The resource ID
	// Required: true
	ID *string `json:"id"`

	// Optional action-specific metadata (see specific metadata types)
	Metadata interface{} `json:"metadata,omitempty"`

	// Unix timestamp when the event occurred
	// Required: true
	Timestamp *int64 `json:"timestamp"`

	// The resource type
	// Required: true
	// Enum: [session session_turn order_status invitation race ruleset session_player_race pending_registration]
	Type *string `json:"type"`
}

// Validate validates this resource change
func (m *ResourceChange) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var resourceChangeTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["created","updated","deleted","ready","member_left","approved","rejected"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		resourceChangeTypeActionPropEnum = append(resourceChangeTypeActionPropEnum, v)
	}
}

const (

	// ResourceChangeActionCreated captures enum value "created"
	ResourceChangeActionCreated string = "created"

	// ResourceChangeActionUpdated captures enum value "updated"
	ResourceChangeActionUpdated string = "updated"

	// ResourceChangeActionDeleted captures enum value "deleted"
	ResourceChangeActionDeleted string = "deleted"

	// ResourceChangeActionReady captures enum value "ready"
	ResourceChangeActionReady string = "ready"

	// ResourceChangeActionMemberLeft captures enum value "member_left"
	ResourceChangeActionMemberLeft string = "member_left"

	// ResourceChangeActionApproved captures enum value "approved"
	ResourceChangeActionApproved string = "approved"

	// ResourceChangeActionRejected captures enum value "rejected"
	ResourceChangeActionRejected string = "rejected"
)

// prop value enum
func (m *ResourceChange) validateActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, resourceChangeTypeActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ResourceChange) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	// value enum
	if err := m.validateActionEnum("action", "body", *m.Action); err != nil {
		return err
	}

	return nil
}

func (m *ResourceChange) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ResourceChange) validateTimestamp(formats strfmt.Registry) error {

	if err := validate.Required("timestamp", "body", m.Timestamp); err != nil {
		return err
	}

	return nil
}

var resourceChangeTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["session","session_turn","order_status","invitation","race","ruleset","session_player_race","pending_registration"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		resourceChangeTypeTypePropEnum = append(resourceChangeTypeTypePropEnum, v)
	}
}

const (

	// ResourceChangeTypeSession captures enum value "session"
	ResourceChangeTypeSession string = "session"

	// ResourceChangeTypeSessionTurn captures enum value "session_turn"
	ResourceChangeTypeSessionTurn string = "session_turn"

	// ResourceChangeTypeOrderStatus captures enum value "order_status"
	ResourceChangeTypeOrderStatus string = "order_status"

	// ResourceChangeTypeInvitation captures enum value "invitation"
	ResourceChangeTypeInvitation string = "invitation"

	// ResourceChangeTypeRace captures enum value "race"
	ResourceChangeTypeRace string = "race"

	// ResourceChangeTypeRuleset captures enum value "ruleset"
	ResourceChangeTypeRuleset string = "ruleset"

	// ResourceChangeTypeSessionPlayerRace captures enum value "session_player_race"
	ResourceChangeTypeSessionPlayerRace string = "session_player_race"

	// ResourceChangeTypePendingRegistration captures enum value "pending_registration"
	ResourceChangeTypePendingRegistration string = "pending_registration"
)

// prop value enum
func (m *ResourceChange) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, resourceChangeTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ResourceChange) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this resource change based on context it is used
func (m *ResourceChange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceChange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceChange) UnmarshalBinary(b []byte) error {
	var res ResourceChange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
