// Code generated by go-swagger; DO NOT EDIT.

package notify

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SessionTurnMeta Metadata for session_turn notifications (action=ready)
//
// swagger:model SessionTurnMeta
type SessionTurnMeta struct {

	// The game year that is now ready
	Year int64 `json:"year,omitempty"`
}

// Validate validates this session turn meta
func (m *SessionTurnMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this session turn meta based on context it is used
func (m *SessionTurnMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SessionTurnMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SessionTurnMeta) UnmarshalBinary(b []byte) error {
	var res SessionTurnMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
