// Code generated by schema-generate. DO NOT EDIT.

package sync

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"

	jsoniter "github.com/json-iterator/go"
)

func ValueTypeToString(valueType jsoniter.ValueType) string {
	switch valueType {
	case jsoniter.StringValue:
		return "string"
	case jsoniter.NumberValue:
		return "number"
	case jsoniter.NilValue:
		return "nil"
	case jsoniter.BoolValue:
		return "bool"
	case jsoniter.ArrayValue:
		return "array"
	case jsoniter.ObjectValue:
		return "object"
	default:
		return "invalid"
	}
}

type commaTracker struct {
	stream  *jsoniter.Stream
	started bool
}

func (t *commaTracker) More() {
	if t.started {
		t.stream.WriteMore()
	} else {
		t.started = true
	}
}

type isEmptyChecker interface {
	IsEmpty() bool
}

// IsEmpty reports whether v is zero struct
// Does not support cycle pointers for performance, so as json
func IsEmpty(v interface{}) bool {
	if i, ok := v.(isEmptyChecker); ok {
		return i.IsEmpty()
	}
	rv := reflect.ValueOf(v)
	return !rv.IsValid() || rv.IsZero()
}

var (
	jsonNullValue = []byte("null")
)

// NewEmptyBool creates a non-empty EmptyBool
func NewEmptyBool(value bool) EmptyBool {
	return EmptyBool{value, true}
}

// EmptyBool is bool or nothing
type EmptyBool struct {
	Bool  bool
	Valid bool // Valid is true if Bool is not empty
}

func (t EmptyBool) IsEmpty() bool {
	return !t.Valid
}

func (t EmptyBool) MarshalJSON() ([]byte, error) {
	if t.Valid {
		return jsoniter.Marshal(t.Bool)
	}
	return []byte("\"\""), nil
}

func (t *EmptyBool) Set(value bool) {
	t.Bool = value
	t.Valid = true
}

func (t *EmptyBool) Unset() {
	t.Bool = false
	t.Valid = false
}

func (t EmptyBool) MarshalJSONStream(stream *jsoniter.Stream) {
	if t.Valid {
		stream.WriteBool(t.Bool)
	} else {
		stream.WriteBool(false)
	}
}

func (t *EmptyBool) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	t.Bool = iter.ReadBool()
	t.Valid = iter.Error == nil
}

func (t *EmptyBool) UnmarshalJSON(data []byte) error {
	if err := jsoniter.Unmarshal(data, &t.Bool); err != nil {
		return err
	}
	t.Valid = true
	return nil
}

// NewEmptyFloat64 creates a non-empty EmptyFloat64
func NewEmptyFloat64(value float64) EmptyFloat64 {
	return EmptyFloat64{value, true}
}

// EmptyFloat64 is float64 or nothing
type EmptyFloat64 struct {
	Float64 float64
	Valid   bool // Valid is true if Float64 is not empty
}

func (t EmptyFloat64) IsEmpty() bool {
	return !t.Valid
}

func (t EmptyFloat64) MarshalJSON() ([]byte, error) {
	if t.Valid {
		return jsoniter.Marshal(t.Float64)
	}
	return []byte("\"\""), nil
}

func (t *EmptyFloat64) Set(value float64) {
	t.Float64 = value
	t.Valid = true
}

func (t *EmptyFloat64) Unset() {
	t.Float64 = 0.0
	t.Valid = false
}

func (t EmptyFloat64) MarshalJSONStream(stream *jsoniter.Stream) {
	if t.Valid {
		stream.WriteFloat64(t.Float64)
	} else {
		stream.WriteFloat64(0.0)
	}
}

func (t *EmptyFloat64) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	t.Float64 = iter.ReadFloat64()
	t.Valid = iter.Error == nil
}

func (t *EmptyFloat64) UnmarshalJSON(data []byte) error {
	if err := jsoniter.Unmarshal(data, &t.Float64); err != nil {
		return err
	}
	t.Valid = true
	return nil
}

// NewEmptyInt creates a non-empty EmptyInt
func NewEmptyInt(value int) EmptyInt {
	return EmptyInt{value, true}
}

// EmptyInt is int or nothing
type EmptyInt struct {
	Int   int
	Valid bool // Valid is true if Int is not empty
}

func (t EmptyInt) IsEmpty() bool {
	return !t.Valid
}

func (t EmptyInt) MarshalJSON() ([]byte, error) {
	if t.Valid {
		return jsoniter.Marshal(t.Int)
	}
	return []byte("\"\""), nil
}

func (t *EmptyInt) Set(value int) {
	t.Int = value
	t.Valid = true
}

func (t *EmptyInt) Unset() {
	t.Int = 0
	t.Valid = false
}

func (t EmptyInt) MarshalJSONStream(stream *jsoniter.Stream) {
	if t.Valid {
		stream.WriteInt(t.Int)
	} else {
		stream.WriteInt(0)
	}
}

func (t *EmptyInt) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	t.Int = iter.ReadInt()
	t.Valid = iter.Error == nil
}

func (t *EmptyInt) UnmarshalJSON(data []byte) error {
	if err := jsoniter.Unmarshal(data, &t.Int); err != nil {
		return err
	}
	t.Valid = true
	return nil
}

// NewEmptyString creates a non-empty EmptyString
func NewEmptyString(value string) EmptyString {
	return EmptyString{value, true}
}

// EmptyString is string or nothing
type EmptyString struct {
	String string
	Valid  bool // Valid is true if String is not empty
}

func (t EmptyString) IsEmpty() bool {
	return !t.Valid
}

func (t EmptyString) MarshalJSON() ([]byte, error) {
	if t.Valid {
		return jsoniter.Marshal(t.String)
	}
	return []byte("\"\""), nil
}

func (t *EmptyString) Set(value string) {
	t.String = value
	t.Valid = true
}

func (t *EmptyString) Unset() {
	t.String = ""
	t.Valid = false
}

func (t EmptyString) MarshalJSONStream(stream *jsoniter.Stream) {
	if t.Valid {
		stream.WriteString(t.String)
	} else {
		stream.WriteString("")
	}
}

func (t *EmptyString) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	t.String = iter.ReadString()
	t.Valid = iter.Error == nil
}

func (t *EmptyString) UnmarshalJSON(data []byte) error {
	if err := jsoniter.Unmarshal(data, &t.String); err != nil {
		return err
	}
	t.Valid = true
	return nil
}

// OneOfStringNull is a 'string' or a 'null', and can be emptied
type OneOfStringNull struct {
	currentType jsoniter.ValueType
	stringValue string
}

// NewOneOfStringNull creates a empty OneOfStringNull
func NewOneOfStringNull() OneOfStringNull {
	return OneOfStringNull{jsoniter.InvalidValue, ""}
}

// NewOneOfStringNullString creates a OneOfStringNull of type string
func NewOneOfStringNullString(value string) OneOfStringNull {
	return OneOfStringNull{jsoniter.StringValue, value}
}

// NewOneOfStringNullNull creates a OneOfStringNull of type null
func NewOneOfStringNullNull() OneOfStringNull {
	return OneOfStringNull{jsoniter.NilValue, ""}
}

// IsEmpty returns true if the value is empty
func (value *OneOfStringNull) IsEmpty() bool {
	return value.currentType == jsoniter.InvalidValue
}

// IsNull returns true if the value is 'null'
func (value *OneOfStringNull) IsNull() bool {
	return value.currentType == jsoniter.NilValue
}

// IsString returns true if the value is a string
func (value *OneOfStringNull) IsString() bool {
	return value.currentType == jsoniter.StringValue
}

// StringValue returns the current value if IsString() is true, "" otherwise
func (value *OneOfStringNull) StringValue() string {
	if value.currentType == jsoniter.StringValue {
		return value.stringValue
	}
	return ""
}

// NullString returns the current value as a sql.NullString
func (value *OneOfStringNull) NullString() sql.NullString {
	return sql.NullString{
		Valid:  value.currentType == jsoniter.StringValue,
		String: value.stringValue,
	}
}

// MarshalJSONStream serializes to a jsoniter Stream
func (value OneOfStringNull) MarshalJSONStream(stream *jsoniter.Stream) {
	if value.currentType == jsoniter.StringValue {
		stream.WriteString(value.stringValue)
	} else {
		stream.WriteNil()
	}
}

// MarshalJSON serialize to json
func (value OneOfStringNull) MarshalJSON() ([]byte, error) {
	switch value.currentType {
	case jsoniter.InvalidValue:
		return jsonNullValue, nil
	case jsoniter.NilValue:
		return jsonNullValue, nil
	case jsoniter.StringValue:
		return jsoniter.Marshal(value.stringValue)
	}
	return nil, fmt.Errorf(
		"OneOfStringNull unsupported type: %s",
		ValueTypeToString(value.currentType))
}

func (value *OneOfStringNull) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	switch t := iter.WhatIsNext(); t {
	case jsoniter.NilValue:
		iter.ReadNil()
		value.currentType = jsoniter.NilValue
	case jsoniter.StringValue:
		value.currentType = jsoniter.StringValue
		value.stringValue = iter.ReadString()
	default:
		iter.ReportError("Read", fmt.Sprintf("unexpected value type: %v", t))
	}
}

// UnmarshalJSON unserialize a OneOfStringNull from json
func (value *OneOfStringNull) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, jsonNullValue) {
		value.currentType = jsoniter.NilValue
	} else {
		if err := jsoniter.Unmarshal(data, &value.stringValue); err != nil {
			return err
		}
		value.currentType = jsoniter.StringValue
	}
	return nil
}

// OneOfNumberNull is a 'string' or a 'null', and can be emptied
type OneOfNumberNull struct {
	currentType jsoniter.ValueType
	numberValue float64
}

// NewOneOfNumberNull creates a empty OneOfNumberNull
func NewOneOfNumberNull() OneOfNumberNull {
	return OneOfNumberNull{jsoniter.InvalidValue, 0}
}

// NewOneOfNumberNullNumber creates a OneOfNumberNull of type number
func NewOneOfNumberNullNumber(value float64) OneOfNumberNull {
	return OneOfNumberNull{jsoniter.NumberValue, value}
}

// NewOneOfNumberNullNull creates a OneOfNumberNull of type null
func NewOneOfNumberNullNull() OneOfNumberNull {
	return OneOfNumberNull{jsoniter.NilValue, 0}
}

// IsEmpty returns true if the value is empty
func (value *OneOfNumberNull) IsEmpty() bool {
	return value.currentType == jsoniter.InvalidValue
}

// IsNull returns true if the value is 'null'
func (value *OneOfNumberNull) IsNull() bool {
	return value.currentType == jsoniter.NilValue
}

// IsNumber returns true if the value is a number
func (value *OneOfNumberNull) IsNumber() bool {
	return value.currentType == jsoniter.NumberValue
}

// NumberValue returns the current value if IsNumber() is true, 0 otherwise
func (value *OneOfNumberNull) NumberValue() float64 {
	if value.currentType == jsoniter.NumberValue {
		return value.numberValue
	}
	return 0
}

// MarshalJSON serialize to json
func (value OneOfNumberNull) MarshalJSON() ([]byte, error) {
	switch value.currentType {
	case jsoniter.InvalidValue:
		return jsonNullValue, nil
	case jsoniter.NilValue:
		return jsonNullValue, nil
	case jsoniter.NumberValue:
		return jsoniter.Marshal(value.numberValue)
	}
	return nil, fmt.Errorf(
		"OneOfNumberNull unsupported type: %s",
		ValueTypeToString(value.currentType))
}

// UnmarshalJSON unserialize a OneOfNumberNull from json
func (value *OneOfNumberNull) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, jsonNullValue) {
		value.currentType = jsoniter.NilValue
	} else {
		if err := jsoniter.Unmarshal(data, &value.numberValue); err != nil {
			return err
		}
		value.currentType = jsoniter.NumberValue
	}
	return nil
}

// OneOfBoolNull is a 'bool' or a 'null', and can be emptied
type OneOfBoolNull struct {
	currentType jsoniter.ValueType
	boolValue   bool
}

// NewOneOfBoolNull creates a empty OneOfBoolNull
func NewOneOfBoolNull() OneOfBoolNull {
	return OneOfBoolNull{jsoniter.InvalidValue, false}
}

// NewOneOfBoolNullBool creates a OneOfBoolNull of type number
func NewOneOfBoolNullBool(value bool) OneOfBoolNull {
	return OneOfBoolNull{jsoniter.BoolValue, value}
}

// NewOneOfBoolNullNull creates a OneOfBoolNull of type null
func NewOneOfBoolNullNull() OneOfBoolNull {
	return OneOfBoolNull{jsoniter.NilValue, false}
}

// IsEmpty returns true if the value is empty
func (value *OneOfBoolNull) IsEmpty() bool {
	return value.currentType == jsoniter.InvalidValue
}

// IsNull returns true if the value is 'null'
func (value *OneOfBoolNull) IsNull() bool {
	return value.currentType == jsoniter.NilValue
}

// IsBool returns true if the value is a bool
func (value *OneOfBoolNull) IsBool() bool {
	return value.currentType == jsoniter.BoolValue
}

// BoolValue returns the current value if IsBool() is true, false otherwise
func (value *OneOfBoolNull) BoolValue() bool {
	if value.currentType == jsoniter.BoolValue {
		return value.boolValue
	}
	return false
}

// MarshalJSON serialize to json
func (value OneOfBoolNull) MarshalJSON() ([]byte, error) {
	switch value.currentType {
	case jsoniter.InvalidValue:
		return jsonNullValue, nil
	case jsoniter.NilValue:
		return jsonNullValue, nil
	case jsoniter.BoolValue:
		return jsoniter.Marshal(value.boolValue)
	}
	return nil, fmt.Errorf(
		"OneOfBoolNull unsupported type: %s",
		ValueTypeToString(value.currentType))
}

// UnmarshalJSON unserialize a OneOfBoolNull from json
func (value *OneOfBoolNull) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, jsonNullValue) {
		value.currentType = jsoniter.NilValue
	} else {
		if err := jsoniter.Unmarshal(data, &value.boolValue); err != nil {
			return err
		}
		value.currentType = jsoniter.BoolValue
	}
	return nil
}

type DataTypeEnum = int

const (
	DataTypeEnumNotSet DataTypeEnum = iota
	DataTypeEnumSession
	DataTypeEnumRace
	DataTypeEnumUserProfile
	DataTypeEnumInvitation
)

type DataType struct {
	Type DataTypeEnum

	value interface{}
}

func (o DataType) IsNotSet() bool {
	return o.Type == DataTypeEnumNotSet
}

func (o DataType) IsSession() bool {
	return o.Type == DataTypeEnumSession
}
func (o DataType) Session() *Session {
	return o.value.(*Session)
}

func (o *DataType) SetSession(v *Session) {
	o.value = v
	o.Type = DataTypeEnumSession
}

func (o DataType) IsRace() bool {
	return o.Type == DataTypeEnumRace
}
func (o DataType) Race() *Race {
	return o.value.(*Race)
}

func (o *DataType) SetRace(v *Race) {
	o.value = v
	o.Type = DataTypeEnumRace
}

func (o DataType) IsUserProfile() bool {
	return o.Type == DataTypeEnumUserProfile
}
func (o DataType) UserProfile() *UserProfile {
	return o.value.(*UserProfile)
}

func (o *DataType) SetUserProfile(v *UserProfile) {
	o.value = v
	o.Type = DataTypeEnumUserProfile
}

func (o DataType) IsInvitation() bool {
	return o.Type == DataTypeEnumInvitation
}
func (o DataType) Invitation() *Invitation {
	return o.value.(*Invitation)
}

func (o *DataType) SetInvitation(v *Invitation) {
	o.value = v
	o.Type = DataTypeEnumInvitation
}

func (o DataType) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	o.MarshalJSONStream(stream)
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (o DataType) MarshalJSONStream(stream *jsoniter.Stream) {
	switch o.Type {
	case DataTypeEnumSession:
		stream.WriteVal(o.value)
	case DataTypeEnumRace:
		stream.WriteVal(o.value)
	case DataTypeEnumUserProfile:
		stream.WriteVal(o.value)
	case DataTypeEnumInvitation:
		stream.WriteVal(o.value)
	}
}

func (o *DataType) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	o.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (o *DataType) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	switch t := iter.WhatIsNext(); t {
	case jsoniter.ObjectValue:
		// I would have used ReadAny, but its 'ToVal' function does not returns
		// the underlying iterator errors, hence makes it impossible to implement
		// a proper oneOf
		buf := iter.SkipAndReturnBytes()

		var lastError error

		{ // attempt to read a *Session
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value Session
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetSession(&value)
				return
			}
		}

		{ // attempt to read a *Race
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value Race
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetRace(&value)
				return
			}
		}

		{ // attempt to read a *UserProfile
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value UserProfile
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetUserProfile(&value)
				return
			}
		}

		{ // attempt to read a *Invitation
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value Invitation
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetInvitation(&value)
				return
			}
		}

		iter.Error = lastError
	}
}

// ChangesItems
type ChangesItems struct {
	// Data
	Data DataType `json:"data"`

	// Operation
	Operation string `json:"operation"`
}

// FileMetadata A file metadata
type FileMetadata struct {
	// Customtype A application-specific file type
	Customtype string `json:"customtype,omitempty"`

	// Encoding The file encoding
	Encoding string `json:"encoding,omitempty"`

	// Filename The file name
	Filename string `json:"filename,omitempty"`

	// Hash The file hashes
	Hash []string `json:"hash,omitempty"`

	// Location The file body actual location
	Location *Location `json:"location,omitempty"`

	// Size The file size in bytes
	Size int `json:"size,omitempty"`

	// Type The file mimetype
	Type string `json:"type,omitempty"`
}

// Invitation invitation
type Invitation struct {
	// Id unique record id
	Id string `json:"id"`

	// SessionId session on which the invitation is
	SessionId string `json:"session_id"`

	// Type data type
	Type string `json:"__type__"`

	// UserProfileId user profile id of the invited person
	UserProfileId string `json:"user_profile_id"`
}

// Location
type Location struct {
	// BucketName 's3' location only
	BucketName string `json:"bucket-name,omitempty"`

	// Objectid 's3' location only
	Objectid string `json:"objectid,omitempty"`

	// Provider 's3' location only
	Provider string `json:"provider,omitempty"`

	// Region 's3' location only
	Region string `json:"region,omitempty"`

	// Type The location type
	Type string `json:"type,omitempty"`
}

// Race race
type Race struct {
	// Data base64 encoded data of the race file as produced by the stars race wizard
	Data string `json:"data"`

	// Id unique record id
	Id string `json:"id"`

	// NamePlural name in plural form
	NamePlural string `json:"name_plural"`

	// NameSingular name in singular form
	NameSingular string `json:"name_singular"`

	// Type data type
	Type string `json:"__type__"`

	// UserId user id of the race owner
	UserId string `json:"user_id"`
}

// ReferentialSync Referential synchronization that may aggregate multiple records of different types
type ReferentialSync struct {
	// Changes
	Changes []*ChangesItems `json:"changes"`

	// Version
	Version int `json:"version,omitempty"`
}

// Session session
type Session struct {
	// Id unique record id
	Id string `json:"id"`

	// Members list of member IDs represented as a user_profile_session_rel, sessionID is optional
	Members []*UserProfileSessionRel `json:"members,omitempty"`

	// Name name
	Name string `json:"name"`

	// Private if the session is private only managers can add new members. The session will not be publicly listed.
	Private bool `json:"private,omitempty"`

	// Type data type
	Type string `json:"__type__"`
}

// UserProfile user profile
type UserProfile struct {
	// ApiKey API Key
	ApiKey string `json:"api_key,omitempty"`

	// Email email
	Email string `json:"email"`

	// Id unique record id
	Id string `json:"id"`

	// IsActive set to true if a login/password exists for this profile
	IsActive bool `json:"is_active"`

	// IsManager Is this user a global manager
	IsManager bool `json:"is_manager,omitempty"`

	// Nickname nickname of this user (name displayed to other users)
	Nickname string `json:"nickname,omitempty"`

	// SessionList List of session ID. Defines the sessions linked to this profile. Represented as user_profile_rel, user_profile_id is optional
	SessionList []*UserProfileSessionRel `json:"session_list,omitempty"`

	// Type data type
	Type string `json:"__type__"`
}

// UserProfileSessionRel user profile session relation table
type UserProfileSessionRel struct {
	// IsManager if the user is manager for this session
	IsManager bool `json:"is_manager,omitempty"`

	// SessionId id of the session
	SessionId string `json:"session_id,omitempty"`

	// UserProfileId id of the user
	UserProfileId string `json:"user_profile_id,omitempty"`
}

// MarshalJSON serializes to JSON
func (s *ChangesItems) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s ChangesItems) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Data field
	ct.More()
	stream.WriteObjectField("data")
	stream.WriteVal(s.Data)
	if stream.Error != nil {
		return
	}

	// Marshal the Operation field
	ct.More()
	stream.WriteObjectField("operation")
	stream.WriteString(s.Operation)
	stream.WriteObjectEnd()
}

func (s *ChangesItems) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *ChangesItems) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	DataReceived := false
	OperationReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "data":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field data", "data is 'true', but the expected type is DataType")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Data)
			if iter.Error != nil {
				return
			}
			DataReceived = true
		case "operation":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field operation", "operation is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Operation = iter.ReadString()
			if iter.Error != nil {
				return
			}
			OperationReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !DataReceived {
		iter.ReportError("validating ChangesItems", "\"data\" is required but was not present")
	}

	if !OperationReceived {
		iter.ReportError("validating ChangesItems", "\"operation\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *Invitation) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s Invitation) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the SessionId field
	ct.More()
	stream.WriteObjectField("session_id")
	stream.WriteString(s.SessionId)

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)

	// Marshal the UserProfileId field
	ct.More()
	stream.WriteObjectField("user_profile_id")
	stream.WriteString(s.UserProfileId)
	stream.WriteObjectEnd()
}

func (s *Invitation) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *Invitation) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	IdReceived := false
	SessionIdReceived := false
	TypeReceived := false
	UserProfileIdReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "session_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field session_id", "session_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.SessionId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			SessionIdReceived = true
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "invitation" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "invitation", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		case "user_profile_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field user_profile_id", "user_profile_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.UserProfileId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			UserProfileIdReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !IdReceived {
		iter.ReportError("validating Invitation", "\"id\" is required but was not present")
	}

	if !SessionIdReceived {
		iter.ReportError("validating Invitation", "\"session_id\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating Invitation", "\"__type__\" is required but was not present")
	}

	if !UserProfileIdReceived {
		iter.ReportError("validating Invitation", "\"user_profile_id\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *Race) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s Race) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Data field
	ct.More()
	stream.WriteObjectField("data")
	stream.WriteString(s.Data)

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the NamePlural field
	ct.More()
	stream.WriteObjectField("name_plural")
	stream.WriteString(s.NamePlural)

	// Marshal the NameSingular field
	ct.More()
	stream.WriteObjectField("name_singular")
	stream.WriteString(s.NameSingular)

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)

	// Marshal the UserId field
	ct.More()
	stream.WriteObjectField("user_id")
	stream.WriteString(s.UserId)
	stream.WriteObjectEnd()
}

func (s *Race) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *Race) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	DataReceived := false
	IdReceived := false
	NamePluralReceived := false
	NameSingularReceived := false
	TypeReceived := false
	UserIdReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "data":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field data", "data is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Data = iter.ReadString()
			if iter.Error != nil {
				return
			}
			DataReceived = true
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "name_plural":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field name_plural", "name_plural is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.NamePlural = iter.ReadString()
			if iter.Error != nil {
				return
			}
			NamePluralReceived = true
		case "name_singular":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field name_singular", "name_singular is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.NameSingular = iter.ReadString()
			if iter.Error != nil {
				return
			}
			NameSingularReceived = true
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "race" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "race", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		case "user_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field user_id", "user_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.UserId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			UserIdReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !DataReceived {
		iter.ReportError("validating Race", "\"data\" is required but was not present")
	}

	if !IdReceived {
		iter.ReportError("validating Race", "\"id\" is required but was not present")
	}

	if !NamePluralReceived {
		iter.ReportError("validating Race", "\"name_plural\" is required but was not present")
	}

	if !NameSingularReceived {
		iter.ReportError("validating Race", "\"name_singular\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating Race", "\"__type__\" is required but was not present")
	}

	if !UserIdReceived {
		iter.ReportError("validating Race", "\"user_id\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *ReferentialSync) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s ReferentialSync) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Changes field
	ct.More()
	stream.WriteObjectField("changes")
	stream.WriteVal(s.Changes)
	if stream.Error != nil {
		return
	}

	// Marshal the Version field
	if !IsEmpty(s.Version) {
		ct.More()
		stream.WriteObjectField("version")
		stream.WriteVal(s.Version)
		if stream.Error != nil {
			return
		}
	}
	stream.WriteObjectEnd()
}

func (s *ReferentialSync) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *ReferentialSync) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	ChangesReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "changes":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field changes", "changes is 'true', but the expected type is []*ChangesItems")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Changes)
			if iter.Error != nil {
				return
			}
			ChangesReceived = true
		case "version":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field version", "version is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Version)
			if iter.Error != nil {
				return
			}
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !ChangesReceived {
		iter.ReportError("validating ReferentialSync", "\"changes\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *Session) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s Session) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the Members field
	if !IsEmpty(s.Members) {
		ct.More()
		stream.WriteObjectField("members")
		stream.WriteVal(s.Members)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Name field
	ct.More()
	stream.WriteObjectField("name")
	stream.WriteString(s.Name)

	// Marshal the Private field
	if !IsEmpty(s.Private) {
		ct.More()
		stream.WriteObjectField("private")
		stream.WriteVal(s.Private)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)
	stream.WriteObjectEnd()
}

func (s *Session) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *Session) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	IdReceived := false
	NameReceived := false
	TypeReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "members":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field members", "members is 'true', but the expected type is []*UserProfileSessionRel")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Members)
			if iter.Error != nil {
				return
			}
		case "name":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field name", "name is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Name = iter.ReadString()
			if iter.Error != nil {
				return
			}
			NameReceived = true
		case "private":
			s.Private = iter.ReadBool()
			if iter.Error != nil {
				return
			}
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "session" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "session", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !IdReceived {
		iter.ReportError("validating Session", "\"id\" is required but was not present")
	}

	if !NameReceived {
		iter.ReportError("validating Session", "\"name\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating Session", "\"__type__\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *UserProfile) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s UserProfile) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the ApiKey field
	if !IsEmpty(s.ApiKey) {
		ct.More()
		stream.WriteObjectField("api_key")
		stream.WriteString(s.ApiKey)
	}

	// Marshal the Email field
	ct.More()
	stream.WriteObjectField("email")
	stream.WriteString(s.Email)

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the IsActive field
	ct.More()
	stream.WriteObjectField("is_active")
	stream.WriteVal(s.IsActive)
	if stream.Error != nil {
		return
	}

	// Marshal the IsManager field
	if !IsEmpty(s.IsManager) {
		ct.More()
		stream.WriteObjectField("is_manager")
		stream.WriteVal(s.IsManager)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Nickname field
	if !IsEmpty(s.Nickname) {
		ct.More()
		stream.WriteObjectField("nickname")
		stream.WriteString(s.Nickname)
	}

	// Marshal the SessionList field
	if !IsEmpty(s.SessionList) {
		ct.More()
		stream.WriteObjectField("session_list")
		stream.WriteVal(s.SessionList)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)
	stream.WriteObjectEnd()
}

func (s *UserProfile) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *UserProfile) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	EmailReceived := false
	IdReceived := false
	IsActiveReceived := false
	TypeReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "api_key":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field api_key", "api_key is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.ApiKey = iter.ReadString()
			if iter.Error != nil {
				return
			}
		case "email":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field email", "email is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Email = iter.ReadString()
			if iter.Error != nil {
				return
			}
			EmailReceived = true
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "is_active":
			s.IsActive = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			IsActiveReceived = true
		case "is_manager":
			s.IsManager = iter.ReadBool()
			if iter.Error != nil {
				return
			}
		case "nickname":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field nickname", "nickname is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Nickname = iter.ReadString()
			if iter.Error != nil {
				return
			}
		case "session_list":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field session_list", "session_list is 'true', but the expected type is []*UserProfileSessionRel")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.SessionList)
			if iter.Error != nil {
				return
			}
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "user_profile" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "user_profile", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !EmailReceived {
		iter.ReportError("validating UserProfile", "\"email\" is required but was not present")
	}

	if !IdReceived {
		iter.ReportError("validating UserProfile", "\"id\" is required but was not present")
	}

	if !IsActiveReceived {
		iter.ReportError("validating UserProfile", "\"is_active\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating UserProfile", "\"__type__\" is required but was not present")
	}
}
