// Code generated by schema-generate. DO NOT EDIT.

package sync

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"

	jsoniter "github.com/json-iterator/go"
)

func ValueTypeToString(valueType jsoniter.ValueType) string {
	switch valueType {
	case jsoniter.StringValue:
		return "string"
	case jsoniter.NumberValue:
		return "number"
	case jsoniter.NilValue:
		return "nil"
	case jsoniter.BoolValue:
		return "bool"
	case jsoniter.ArrayValue:
		return "array"
	case jsoniter.ObjectValue:
		return "object"
	default:
		return "invalid"
	}
}

type commaTracker struct {
	stream  *jsoniter.Stream
	started bool
}

func (t *commaTracker) More() {
	if t.started {
		t.stream.WriteMore()
	} else {
		t.started = true
	}
}

type isEmptyChecker interface {
	IsEmpty() bool
}

// IsEmpty reports whether v is zero struct
// Does not support cycle pointers for performance, so as json
func IsEmpty(v interface{}) bool {
	if i, ok := v.(isEmptyChecker); ok {
		return i.IsEmpty()
	}
	rv := reflect.ValueOf(v)
	return !rv.IsValid() || rv.IsZero()
}

var (
	jsonNullValue = []byte("null")
)

// NewEmptyBool creates a non-empty EmptyBool
func NewEmptyBool(value bool) EmptyBool {
	return EmptyBool{value, true}
}

// EmptyBool is bool or nothing
type EmptyBool struct {
	Bool  bool
	Valid bool // Valid is true if Bool is not empty
}

func (t EmptyBool) IsEmpty() bool {
	return !t.Valid
}

func (t EmptyBool) MarshalJSON() ([]byte, error) {
	if t.Valid {
		return jsoniter.Marshal(t.Bool)
	}
	return []byte("\"\""), nil
}

func (t *EmptyBool) Set(value bool) {
	t.Bool = value
	t.Valid = true
}

func (t *EmptyBool) Unset() {
	t.Bool = false
	t.Valid = false
}

func (t EmptyBool) MarshalJSONStream(stream *jsoniter.Stream) {
	if t.Valid {
		stream.WriteBool(t.Bool)
	} else {
		stream.WriteBool(false)
	}
}

func (t *EmptyBool) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	t.Bool = iter.ReadBool()
	t.Valid = iter.Error == nil
}

func (t *EmptyBool) UnmarshalJSON(data []byte) error {
	if err := jsoniter.Unmarshal(data, &t.Bool); err != nil {
		return err
	}
	t.Valid = true
	return nil
}

// NewEmptyFloat64 creates a non-empty EmptyFloat64
func NewEmptyFloat64(value float64) EmptyFloat64 {
	return EmptyFloat64{value, true}
}

// EmptyFloat64 is float64 or nothing
type EmptyFloat64 struct {
	Float64 float64
	Valid   bool // Valid is true if Float64 is not empty
}

func (t EmptyFloat64) IsEmpty() bool {
	return !t.Valid
}

func (t EmptyFloat64) MarshalJSON() ([]byte, error) {
	if t.Valid {
		return jsoniter.Marshal(t.Float64)
	}
	return []byte("\"\""), nil
}

func (t *EmptyFloat64) Set(value float64) {
	t.Float64 = value
	t.Valid = true
}

func (t *EmptyFloat64) Unset() {
	t.Float64 = 0.0
	t.Valid = false
}

func (t EmptyFloat64) MarshalJSONStream(stream *jsoniter.Stream) {
	if t.Valid {
		stream.WriteFloat64(t.Float64)
	} else {
		stream.WriteFloat64(0.0)
	}
}

func (t *EmptyFloat64) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	t.Float64 = iter.ReadFloat64()
	t.Valid = iter.Error == nil
}

func (t *EmptyFloat64) UnmarshalJSON(data []byte) error {
	if err := jsoniter.Unmarshal(data, &t.Float64); err != nil {
		return err
	}
	t.Valid = true
	return nil
}

// NewEmptyInt creates a non-empty EmptyInt
func NewEmptyInt(value int) EmptyInt {
	return EmptyInt{value, true}
}

// EmptyInt is int or nothing
type EmptyInt struct {
	Int   int
	Valid bool // Valid is true if Int is not empty
}

func (t EmptyInt) IsEmpty() bool {
	return !t.Valid
}

func (t EmptyInt) MarshalJSON() ([]byte, error) {
	if t.Valid {
		return jsoniter.Marshal(t.Int)
	}
	return []byte("\"\""), nil
}

func (t *EmptyInt) Set(value int) {
	t.Int = value
	t.Valid = true
}

func (t *EmptyInt) Unset() {
	t.Int = 0
	t.Valid = false
}

func (t EmptyInt) MarshalJSONStream(stream *jsoniter.Stream) {
	if t.Valid {
		stream.WriteInt(t.Int)
	} else {
		stream.WriteInt(0)
	}
}

func (t *EmptyInt) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	t.Int = iter.ReadInt()
	t.Valid = iter.Error == nil
}

func (t *EmptyInt) UnmarshalJSON(data []byte) error {
	if err := jsoniter.Unmarshal(data, &t.Int); err != nil {
		return err
	}
	t.Valid = true
	return nil
}

// NewEmptyString creates a non-empty EmptyString
func NewEmptyString(value string) EmptyString {
	return EmptyString{value, true}
}

// EmptyString is string or nothing
type EmptyString struct {
	String string
	Valid  bool // Valid is true if String is not empty
}

func (t EmptyString) IsEmpty() bool {
	return !t.Valid
}

func (t EmptyString) MarshalJSON() ([]byte, error) {
	if t.Valid {
		return jsoniter.Marshal(t.String)
	}
	return []byte("\"\""), nil
}

func (t *EmptyString) Set(value string) {
	t.String = value
	t.Valid = true
}

func (t *EmptyString) Unset() {
	t.String = ""
	t.Valid = false
}

func (t EmptyString) MarshalJSONStream(stream *jsoniter.Stream) {
	if t.Valid {
		stream.WriteString(t.String)
	} else {
		stream.WriteString("")
	}
}

func (t *EmptyString) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	t.String = iter.ReadString()
	t.Valid = iter.Error == nil
}

func (t *EmptyString) UnmarshalJSON(data []byte) error {
	if err := jsoniter.Unmarshal(data, &t.String); err != nil {
		return err
	}
	t.Valid = true
	return nil
}

// OneOfStringNull is a 'string' or a 'null', and can be emptied
type OneOfStringNull struct {
	currentType jsoniter.ValueType
	stringValue string
}

// NewOneOfStringNull creates a empty OneOfStringNull
func NewOneOfStringNull() OneOfStringNull {
	return OneOfStringNull{jsoniter.InvalidValue, ""}
}

// NewOneOfStringNullString creates a OneOfStringNull of type string
func NewOneOfStringNullString(value string) OneOfStringNull {
	return OneOfStringNull{jsoniter.StringValue, value}
}

// NewOneOfStringNullNull creates a OneOfStringNull of type null
func NewOneOfStringNullNull() OneOfStringNull {
	return OneOfStringNull{jsoniter.NilValue, ""}
}

// IsEmpty returns true if the value is empty
func (value *OneOfStringNull) IsEmpty() bool {
	return value.currentType == jsoniter.InvalidValue
}

// IsNull returns true if the value is 'null'
func (value *OneOfStringNull) IsNull() bool {
	return value.currentType == jsoniter.NilValue
}

// IsString returns true if the value is a string
func (value *OneOfStringNull) IsString() bool {
	return value.currentType == jsoniter.StringValue
}

// StringValue returns the current value if IsString() is true, "" otherwise
func (value *OneOfStringNull) StringValue() string {
	if value.currentType == jsoniter.StringValue {
		return value.stringValue
	}
	return ""
}

// NullString returns the current value as a sql.NullString
func (value *OneOfStringNull) NullString() sql.NullString {
	return sql.NullString{
		Valid:  value.currentType == jsoniter.StringValue,
		String: value.stringValue,
	}
}

// MarshalJSONStream serializes to a jsoniter Stream
func (value OneOfStringNull) MarshalJSONStream(stream *jsoniter.Stream) {
	if value.currentType == jsoniter.StringValue {
		stream.WriteString(value.stringValue)
	} else {
		stream.WriteNil()
	}
}

// MarshalJSON serialize to json
func (value OneOfStringNull) MarshalJSON() ([]byte, error) {
	switch value.currentType {
	case jsoniter.InvalidValue:
		return jsonNullValue, nil
	case jsoniter.NilValue:
		return jsonNullValue, nil
	case jsoniter.StringValue:
		return jsoniter.Marshal(value.stringValue)
	}
	return nil, fmt.Errorf(
		"OneOfStringNull unsupported type: %s",
		ValueTypeToString(value.currentType))
}

func (value *OneOfStringNull) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	switch t := iter.WhatIsNext(); t {
	case jsoniter.NilValue:
		iter.ReadNil()
		value.currentType = jsoniter.NilValue
	case jsoniter.StringValue:
		value.currentType = jsoniter.StringValue
		value.stringValue = iter.ReadString()
	default:
		iter.ReportError("Read", fmt.Sprintf("unexpected value type: %v", t))
	}
}

// UnmarshalJSON unserialize a OneOfStringNull from json
func (value *OneOfStringNull) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, jsonNullValue) {
		value.currentType = jsoniter.NilValue
	} else {
		if err := jsoniter.Unmarshal(data, &value.stringValue); err != nil {
			return err
		}
		value.currentType = jsoniter.StringValue
	}
	return nil
}

// OneOfNumberNull is a 'string' or a 'null', and can be emptied
type OneOfNumberNull struct {
	currentType jsoniter.ValueType
	numberValue float64
}

// NewOneOfNumberNull creates a empty OneOfNumberNull
func NewOneOfNumberNull() OneOfNumberNull {
	return OneOfNumberNull{jsoniter.InvalidValue, 0}
}

// NewOneOfNumberNullNumber creates a OneOfNumberNull of type number
func NewOneOfNumberNullNumber(value float64) OneOfNumberNull {
	return OneOfNumberNull{jsoniter.NumberValue, value}
}

// NewOneOfNumberNullNull creates a OneOfNumberNull of type null
func NewOneOfNumberNullNull() OneOfNumberNull {
	return OneOfNumberNull{jsoniter.NilValue, 0}
}

// IsEmpty returns true if the value is empty
func (value *OneOfNumberNull) IsEmpty() bool {
	return value.currentType == jsoniter.InvalidValue
}

// IsNull returns true if the value is 'null'
func (value *OneOfNumberNull) IsNull() bool {
	return value.currentType == jsoniter.NilValue
}

// IsNumber returns true if the value is a number
func (value *OneOfNumberNull) IsNumber() bool {
	return value.currentType == jsoniter.NumberValue
}

// NumberValue returns the current value if IsNumber() is true, 0 otherwise
func (value *OneOfNumberNull) NumberValue() float64 {
	if value.currentType == jsoniter.NumberValue {
		return value.numberValue
	}
	return 0
}

// MarshalJSON serialize to json
func (value OneOfNumberNull) MarshalJSON() ([]byte, error) {
	switch value.currentType {
	case jsoniter.InvalidValue:
		return jsonNullValue, nil
	case jsoniter.NilValue:
		return jsonNullValue, nil
	case jsoniter.NumberValue:
		return jsoniter.Marshal(value.numberValue)
	}
	return nil, fmt.Errorf(
		"OneOfNumberNull unsupported type: %s",
		ValueTypeToString(value.currentType))
}

// UnmarshalJSON unserialize a OneOfNumberNull from json
func (value *OneOfNumberNull) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, jsonNullValue) {
		value.currentType = jsoniter.NilValue
	} else {
		if err := jsoniter.Unmarshal(data, &value.numberValue); err != nil {
			return err
		}
		value.currentType = jsoniter.NumberValue
	}
	return nil
}

// OneOfBoolNull is a 'bool' or a 'null', and can be emptied
type OneOfBoolNull struct {
	currentType jsoniter.ValueType
	boolValue   bool
}

// NewOneOfBoolNull creates a empty OneOfBoolNull
func NewOneOfBoolNull() OneOfBoolNull {
	return OneOfBoolNull{jsoniter.InvalidValue, false}
}

// NewOneOfBoolNullBool creates a OneOfBoolNull of type number
func NewOneOfBoolNullBool(value bool) OneOfBoolNull {
	return OneOfBoolNull{jsoniter.BoolValue, value}
}

// NewOneOfBoolNullNull creates a OneOfBoolNull of type null
func NewOneOfBoolNullNull() OneOfBoolNull {
	return OneOfBoolNull{jsoniter.NilValue, false}
}

// IsEmpty returns true if the value is empty
func (value *OneOfBoolNull) IsEmpty() bool {
	return value.currentType == jsoniter.InvalidValue
}

// IsNull returns true if the value is 'null'
func (value *OneOfBoolNull) IsNull() bool {
	return value.currentType == jsoniter.NilValue
}

// IsBool returns true if the value is a bool
func (value *OneOfBoolNull) IsBool() bool {
	return value.currentType == jsoniter.BoolValue
}

// BoolValue returns the current value if IsBool() is true, false otherwise
func (value *OneOfBoolNull) BoolValue() bool {
	if value.currentType == jsoniter.BoolValue {
		return value.boolValue
	}
	return false
}

// MarshalJSON serialize to json
func (value OneOfBoolNull) MarshalJSON() ([]byte, error) {
	switch value.currentType {
	case jsoniter.InvalidValue:
		return jsonNullValue, nil
	case jsoniter.NilValue:
		return jsonNullValue, nil
	case jsoniter.BoolValue:
		return jsoniter.Marshal(value.boolValue)
	}
	return nil, fmt.Errorf(
		"OneOfBoolNull unsupported type: %s",
		ValueTypeToString(value.currentType))
}

// UnmarshalJSON unserialize a OneOfBoolNull from json
func (value *OneOfBoolNull) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, jsonNullValue) {
		value.currentType = jsoniter.NilValue
	} else {
		if err := jsoniter.Unmarshal(data, &value.boolValue); err != nil {
			return err
		}
		value.currentType = jsoniter.BoolValue
	}
	return nil
}

type DataTypeEnum = int

const (
	DataTypeEnumNotSet DataTypeEnum = iota
	DataTypeEnumSession
	DataTypeEnumRace
	DataTypeEnumUserProfile
	DataTypeEnumInvitation
	DataTypeEnumSessionPlayerRace
	DataTypeEnumSessionFiles
	DataTypeEnumRuleset
)

type DataType struct {
	Type DataTypeEnum

	value interface{}
}

func (o DataType) IsNotSet() bool {
	return o.Type == DataTypeEnumNotSet
}

func (o DataType) IsSession() bool {
	return o.Type == DataTypeEnumSession
}
func (o DataType) Session() *Session {
	return o.value.(*Session)
}

func (o *DataType) SetSession(v *Session) {
	o.value = v
	o.Type = DataTypeEnumSession
}

func (o DataType) IsRace() bool {
	return o.Type == DataTypeEnumRace
}
func (o DataType) Race() *Race {
	return o.value.(*Race)
}

func (o *DataType) SetRace(v *Race) {
	o.value = v
	o.Type = DataTypeEnumRace
}

func (o DataType) IsUserProfile() bool {
	return o.Type == DataTypeEnumUserProfile
}
func (o DataType) UserProfile() *UserProfile {
	return o.value.(*UserProfile)
}

func (o *DataType) SetUserProfile(v *UserProfile) {
	o.value = v
	o.Type = DataTypeEnumUserProfile
}

func (o DataType) IsInvitation() bool {
	return o.Type == DataTypeEnumInvitation
}
func (o DataType) Invitation() *Invitation {
	return o.value.(*Invitation)
}

func (o *DataType) SetInvitation(v *Invitation) {
	o.value = v
	o.Type = DataTypeEnumInvitation
}

func (o DataType) IsSessionPlayerRace() bool {
	return o.Type == DataTypeEnumSessionPlayerRace
}
func (o DataType) SessionPlayerRace() *SessionPlayerRace {
	return o.value.(*SessionPlayerRace)
}

func (o *DataType) SetSessionPlayerRace(v *SessionPlayerRace) {
	o.value = v
	o.Type = DataTypeEnumSessionPlayerRace
}

func (o DataType) IsSessionFiles() bool {
	return o.Type == DataTypeEnumSessionFiles
}
func (o DataType) SessionFiles() *SessionFiles {
	return o.value.(*SessionFiles)
}

func (o *DataType) SetSessionFiles(v *SessionFiles) {
	o.value = v
	o.Type = DataTypeEnumSessionFiles
}

func (o DataType) IsRuleset() bool {
	return o.Type == DataTypeEnumRuleset
}
func (o DataType) Ruleset() *Ruleset {
	return o.value.(*Ruleset)
}

func (o *DataType) SetRuleset(v *Ruleset) {
	o.value = v
	o.Type = DataTypeEnumRuleset
}

func (o DataType) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	o.MarshalJSONStream(stream)
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (o DataType) MarshalJSONStream(stream *jsoniter.Stream) {
	switch o.Type {
	case DataTypeEnumSession:
		stream.WriteVal(o.value)
	case DataTypeEnumRace:
		stream.WriteVal(o.value)
	case DataTypeEnumUserProfile:
		stream.WriteVal(o.value)
	case DataTypeEnumInvitation:
		stream.WriteVal(o.value)
	case DataTypeEnumSessionPlayerRace:
		stream.WriteVal(o.value)
	case DataTypeEnumSessionFiles:
		stream.WriteVal(o.value)
	case DataTypeEnumRuleset:
		stream.WriteVal(o.value)
	}
}

func (o *DataType) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	o.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (o *DataType) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	switch t := iter.WhatIsNext(); t {
	case jsoniter.ObjectValue:
		// I would have used ReadAny, but its 'ToVal' function does not returns
		// the underlying iterator errors, hence makes it impossible to implement
		// a proper oneOf
		buf := iter.SkipAndReturnBytes()

		var lastError error

		{ // attempt to read a *Session
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value Session
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetSession(&value)
				return
			}
		}

		{ // attempt to read a *Race
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value Race
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetRace(&value)
				return
			}
		}

		{ // attempt to read a *UserProfile
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value UserProfile
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetUserProfile(&value)
				return
			}
		}

		{ // attempt to read a *Invitation
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value Invitation
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetInvitation(&value)
				return
			}
		}

		{ // attempt to read a *SessionPlayerRace
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value SessionPlayerRace
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetSessionPlayerRace(&value)
				return
			}
		}

		{ // attempt to read a *SessionFiles
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value SessionFiles
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetSessionFiles(&value)
				return
			}
		}

		{ // attempt to read a *Ruleset
			subIter := jsoniter.ConfigDefault.BorrowIterator(buf)
			var value Ruleset
			subIter.ReadVal(&value)
			lastError = subIter.Error
			jsoniter.ConfigDefault.ReturnIterator(subIter)
			if lastError == nil {
				o.SetRuleset(&value)
				return
			}
		}

		iter.Error = lastError
	}
}

// ChangesItems
type ChangesItems struct {
	// Data
	Data DataType `json:"data"`

	// Operation
	Operation string `json:"operation"`
}

// FileMetadata A file metadata
type FileMetadata struct {
	// Customtype A application-specific file type
	Customtype string `json:"customtype,omitempty"`

	// Encoding The file encoding
	Encoding string `json:"encoding,omitempty"`

	// Filename The file name
	Filename string `json:"filename,omitempty"`

	// Hash The file hashes
	Hash []string `json:"hash,omitempty"`

	// Location The file body actual location
	Location *Location `json:"location,omitempty"`

	// Size The file size in bytes
	Size int `json:"size,omitempty"`

	// Type The file mimetype
	Type string `json:"type,omitempty"`
}

// Invitation invitation
type Invitation struct {
	// Id unique record id
	Id string `json:"id"`

	// InviterId user profile id of the person who sent the invitation
	InviterId string `json:"inviter_id,omitempty"`

	// SessionId session on which the invitation is
	SessionId string `json:"session_id"`

	// Type data type
	Type string `json:"__type__"`

	// UserProfileId user profile id of the invited person
	UserProfileId string `json:"user_profile_id"`
}

// Location
type Location struct {
	// BucketName 's3' location only
	BucketName string `json:"bucket-name,omitempty"`

	// Objectid 's3' location only
	Objectid string `json:"objectid,omitempty"`

	// Provider 's3' location only
	Provider string `json:"provider,omitempty"`

	// Region 's3' location only
	Region string `json:"region,omitempty"`

	// Type The location type
	Type string `json:"type,omitempty"`
}

// Order
type Order struct {
	// B64Data The file content in base64 encoded form
	B64Data string `json:"b64_data,omitempty"`
}

// Race race
type Race struct {
	// Data base64 encoded data of the race file as produced by the stars race wizard
	Data string `json:"data"`

	// Id unique record id
	Id string `json:"id"`

	// NamePlural name in plural form
	NamePlural string `json:"name_plural"`

	// NameSingular name in singular form
	NameSingular string `json:"name_singular"`

	// Type data type
	Type string `json:"__type__"`

	// UserId user id of the race owner
	UserId string `json:"user_id"`
}

// ReferentialSync Referential synchronization that may aggregate multiple records of different types
type ReferentialSync struct {
	// Changes
	Changes []*ChangesItems `json:"changes"`

	// Version
	Version int `json:"version,omitempty"`
}

// Ruleset ruleset
type Ruleset struct {
	// AcceleratedBbsPlay
	AcceleratedBbsPlay bool `json:"accelerated_bbs_play"`

	// ComputerPlayersFormAlliances
	ComputerPlayersFormAlliances bool `json:"computer_players_form_alliances"`

	// Density
	Density int `json:"density"`

	// GalaxyClumping
	GalaxyClumping bool `json:"galaxy_clumping"`

	// Id unique record id
	Id string `json:"id"`

	// MaximumMinerals
	MaximumMinerals bool `json:"maximum_minerals"`

	// NoRandomEvents
	NoRandomEvents bool `json:"no_random_events"`

	// PublicPlayerScores
	PublicPlayerScores bool `json:"public_player_scores"`

	// RandomSeed
	RandomSeed int `json:"random_seed,omitempty"`

	// SessionId unique id of the related session
	SessionId string `json:"session_id"`

	// SlowerTechAdvances
	SlowerTechAdvances bool `json:"slower_tech_advances"`

	// StartingDistance
	StartingDistance int `json:"starting_distance"`

	// Type data type
	Type string `json:"__type__"`

	// UniverseSize
	UniverseSize int `json:"universe_size"`

	// VcAtLeastXYearsMustPassBeforeAWinnerIsDeclared
	VcAtLeastXYearsMustPassBeforeAWinnerIsDeclared int `json:"vc_at_least_x_years_must_pass_before_a_winner_is_declared"`

	// VcAttainTechXInYField
	VcAttainTechXInYField bool `json:"vc_attain_tech_X_in_Y_field"`

	// VcAttainTechXInYFieldFieldsValue
	VcAttainTechXInYFieldFieldsValue int `json:"vc_attain_tech_X_in_Y_field_fields_value,omitempty"`

	// VcAttainTechXInYFieldTechValue
	VcAttainTechXInYFieldTechValue int `json:"vc_attain_tech_X_in_Y_field_tech_value,omitempty"`

	// VcExceedNextPlayerScoreByX
	VcExceedNextPlayerScoreByX bool `json:"vc_exceed_next_player_score_by_x"`

	// VcExceedNextPlayerScoreByXValue percentage of excess score from 2nd player
	VcExceedNextPlayerScoreByXValue int `json:"vc_exceed_next_player_score_by_x_value,omitempty"`

	// VcExceedScoreOfX
	VcExceedScoreOfX bool `json:"vc_exceed_score_of_x,omitempty"`

	// VcExceedScoreOfXValue
	VcExceedScoreOfXValue int `json:"vc_exceed_score_of_x_value,omitempty"`

	// VcHasProductionCapacityOfXThousand
	VcHasProductionCapacityOfXThousand bool `json:"vc_has_production_capacity_of_x_thousand"`

	// VcHasProductionCapacityOfXThousandValue expressed in 1000 (k)
	VcHasProductionCapacityOfXThousandValue int `json:"vc_has_production_capacity_of_x_thousand_value,omitempty"`

	// VcHaveHighestScoreAfterXYears
	VcHaveHighestScoreAfterXYears bool `json:"vc_have_highest_score_after_x_years"`

	// VcHaveHighestScoreAfterXYearsValue expressed in years
	VcHaveHighestScoreAfterXYearsValue int `json:"vc_have_highest_score_after_x_years_value,omitempty"`

	// VcOwnsXCapitalShips
	VcOwnsXCapitalShips bool `json:"vc_owns_x_capital_ships"`

	// VcOwnsXCapitalShipsValue
	VcOwnsXCapitalShipsValue int `json:"vc_owns_x_capital_ships_value,omitempty"`

	// VcOwnsXPercentOfPlanets
	VcOwnsXPercentOfPlanets bool `json:"vc_owns_x_percent_of_planets"`

	// VcOwnsXPercentOfPlanetsValue expressed in percent
	VcOwnsXPercentOfPlanetsValue int `json:"vc_owns_x_percent_of_planets_value,omitempty"`

	// VcWinnerMustMeetXOfTheAbove
	VcWinnerMustMeetXOfTheAbove int `json:"vc_winner_must_meet_x_of_the_above"`
}

// Session session
type Session struct {
	// Id unique record id
	Id string `json:"id"`

	// Members list of member IDs represented as a user_profile_session_rel, sessionID is optional
	Members []*UserProfileSessionRel `json:"members,omitempty"`

	// Name name
	Name string `json:"name"`

	// Private if the session is private only managers can add new members. The session will not be publicly listed.
	Private bool `json:"private,omitempty"`

	// RulesIsSet true if the ruleset has been configured for this session
	RulesIsSet bool `json:"rules_is_set,omitempty"`

	// Started whether the game has been started for this session
	Started bool `json:"started,omitempty"`

	// Type data type
	Type string `json:"__type__"`
}

// SessionFiles represents all the files for either a turn that as just been generated or a turn that will be generated (orders)
type SessionFiles struct {
	// Hostfile the host file content (game.hst) stored in base64
	Hostfile string `json:"hostfile"`

	// Id id
	Id string `json:"id"`

	// Orders
	Orders []*Order `json:"orders"`

	// SessionId id of the session
	SessionId string `json:"session_id"`

	// Turns
	Turns []*Turn `json:"turns"`

	// Type data type
	Type string `json:"__type__"`

	// Universe the universe file content (game.xy) stored in base64
	Universe string `json:"universe"`

	// Year the year those files are for (this is kind of like the turn number)
	Year int `json:"year"`
}

// SessionPlayerRace setup for a session of a player and its race
type SessionPlayerRace struct {
	// BotLevel if is_bot is true, we need a level between 0 and 4
	BotLevel int `json:"bot_level,omitempty"`

	// Id id
	Id string `json:"id"`

	// IsBot if true the player is a bot. In this case the user ID must be 'system'
	IsBot bool `json:"is_bot"`

	// PlayerOrder in which slot the player is. ranges from 0 to 15
	PlayerOrder int `json:"player_order"`

	// RaceId id of the race. If is bot, the race_id should be between 0 and 6
	RaceId string `json:"race_id"`

	// Ready whether the player has marked their race as ready
	Ready bool `json:"ready,omitempty"`

	// SessionId id of the session
	SessionId string `json:"session_id"`

	// Type data type
	Type string `json:"__type__"`

	// UserProfileId id of the user
	UserProfileId string `json:"user_profile_id"`
}

// Turn
type Turn struct {
	// B64Data The file content in base64 encoded form
	B64Data string `json:"b64_data,omitempty"`
}

// UserProfile user profile
type UserProfile struct {
	// ApiKey API Key
	ApiKey string `json:"api_key,omitempty"`

	// Email email
	Email string `json:"email"`

	// Id unique record id
	Id string `json:"id"`

	// IsActive set to true if a login/password exists for this profile
	IsActive bool `json:"is_active"`

	// IsManager Is this user a global manager
	IsManager bool `json:"is_manager,omitempty"`

	// Nickname nickname of this user (name displayed to other users)
	Nickname string `json:"nickname,omitempty"`

	// SessionList List of session ID. Defines the sessions linked to this profile. Represented as user_profile_rel, user_profile_id is optional
	SessionList []*UserProfileSessionRel `json:"session_list,omitempty"`

	// Type data type
	Type string `json:"__type__"`
}

// UserProfileSessionRel user profile session relation table
type UserProfileSessionRel struct {
	// IsManager if the user is manager for this session
	IsManager bool `json:"is_manager,omitempty"`

	// SessionId id of the session
	SessionId string `json:"session_id,omitempty"`

	// UserProfileId id of the user
	UserProfileId string `json:"user_profile_id,omitempty"`
}

// MarshalJSON serializes to JSON
func (s *ChangesItems) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s ChangesItems) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Data field
	ct.More()
	stream.WriteObjectField("data")
	stream.WriteVal(s.Data)
	if stream.Error != nil {
		return
	}

	// Marshal the Operation field
	ct.More()
	stream.WriteObjectField("operation")
	stream.WriteString(s.Operation)
	stream.WriteObjectEnd()
}

func (s *ChangesItems) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *ChangesItems) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	DataReceived := false
	OperationReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "data":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field data", "data is 'true', but the expected type is DataType")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Data)
			if iter.Error != nil {
				return
			}
			DataReceived = true
		case "operation":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field operation", "operation is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Operation = iter.ReadString()
			if iter.Error != nil {
				return
			}
			OperationReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !DataReceived {
		iter.ReportError("validating ChangesItems", "\"data\" is required but was not present")
	}

	if !OperationReceived {
		iter.ReportError("validating ChangesItems", "\"operation\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *Invitation) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s Invitation) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the InviterId field
	if !IsEmpty(s.InviterId) {
		ct.More()
		stream.WriteObjectField("inviter_id")
		stream.WriteString(s.InviterId)
	}

	// Marshal the SessionId field
	ct.More()
	stream.WriteObjectField("session_id")
	stream.WriteString(s.SessionId)

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)

	// Marshal the UserProfileId field
	ct.More()
	stream.WriteObjectField("user_profile_id")
	stream.WriteString(s.UserProfileId)
	stream.WriteObjectEnd()
}

func (s *Invitation) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *Invitation) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	IdReceived := false
	SessionIdReceived := false
	TypeReceived := false
	UserProfileIdReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "inviter_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field inviter_id", "inviter_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.InviterId = iter.ReadString()
			if iter.Error != nil {
				return
			}
		case "session_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field session_id", "session_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.SessionId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			SessionIdReceived = true
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "invitation" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "invitation", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		case "user_profile_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field user_profile_id", "user_profile_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.UserProfileId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			UserProfileIdReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !IdReceived {
		iter.ReportError("validating Invitation", "\"id\" is required but was not present")
	}

	if !SessionIdReceived {
		iter.ReportError("validating Invitation", "\"session_id\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating Invitation", "\"__type__\" is required but was not present")
	}

	if !UserProfileIdReceived {
		iter.ReportError("validating Invitation", "\"user_profile_id\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *Race) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s Race) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Data field
	ct.More()
	stream.WriteObjectField("data")
	stream.WriteString(s.Data)

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the NamePlural field
	ct.More()
	stream.WriteObjectField("name_plural")
	stream.WriteString(s.NamePlural)

	// Marshal the NameSingular field
	ct.More()
	stream.WriteObjectField("name_singular")
	stream.WriteString(s.NameSingular)

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)

	// Marshal the UserId field
	ct.More()
	stream.WriteObjectField("user_id")
	stream.WriteString(s.UserId)
	stream.WriteObjectEnd()
}

func (s *Race) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *Race) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	DataReceived := false
	IdReceived := false
	NamePluralReceived := false
	NameSingularReceived := false
	TypeReceived := false
	UserIdReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "data":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field data", "data is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Data = iter.ReadString()
			if iter.Error != nil {
				return
			}
			DataReceived = true
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "name_plural":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field name_plural", "name_plural is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.NamePlural = iter.ReadString()
			if iter.Error != nil {
				return
			}
			NamePluralReceived = true
		case "name_singular":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field name_singular", "name_singular is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.NameSingular = iter.ReadString()
			if iter.Error != nil {
				return
			}
			NameSingularReceived = true
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "race" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "race", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		case "user_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field user_id", "user_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.UserId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			UserIdReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !DataReceived {
		iter.ReportError("validating Race", "\"data\" is required but was not present")
	}

	if !IdReceived {
		iter.ReportError("validating Race", "\"id\" is required but was not present")
	}

	if !NamePluralReceived {
		iter.ReportError("validating Race", "\"name_plural\" is required but was not present")
	}

	if !NameSingularReceived {
		iter.ReportError("validating Race", "\"name_singular\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating Race", "\"__type__\" is required but was not present")
	}

	if !UserIdReceived {
		iter.ReportError("validating Race", "\"user_id\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *ReferentialSync) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s ReferentialSync) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Changes field
	ct.More()
	stream.WriteObjectField("changes")
	stream.WriteVal(s.Changes)
	if stream.Error != nil {
		return
	}

	// Marshal the Version field
	if !IsEmpty(s.Version) {
		ct.More()
		stream.WriteObjectField("version")
		stream.WriteVal(s.Version)
		if stream.Error != nil {
			return
		}
	}
	stream.WriteObjectEnd()
}

func (s *ReferentialSync) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *ReferentialSync) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	ChangesReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "changes":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field changes", "changes is 'true', but the expected type is []*ChangesItems")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Changes)
			if iter.Error != nil {
				return
			}
			ChangesReceived = true
		case "version":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field version", "version is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Version)
			if iter.Error != nil {
				return
			}
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !ChangesReceived {
		iter.ReportError("validating ReferentialSync", "\"changes\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *Ruleset) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s Ruleset) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the AcceleratedBbsPlay field
	ct.More()
	stream.WriteObjectField("accelerated_bbs_play")
	stream.WriteVal(s.AcceleratedBbsPlay)
	if stream.Error != nil {
		return
	}

	// Marshal the ComputerPlayersFormAlliances field
	ct.More()
	stream.WriteObjectField("computer_players_form_alliances")
	stream.WriteVal(s.ComputerPlayersFormAlliances)
	if stream.Error != nil {
		return
	}

	// Marshal the Density field
	ct.More()
	stream.WriteObjectField("density")
	stream.WriteVal(s.Density)
	if stream.Error != nil {
		return
	}

	// Marshal the GalaxyClumping field
	ct.More()
	stream.WriteObjectField("galaxy_clumping")
	stream.WriteVal(s.GalaxyClumping)
	if stream.Error != nil {
		return
	}

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the MaximumMinerals field
	ct.More()
	stream.WriteObjectField("maximum_minerals")
	stream.WriteVal(s.MaximumMinerals)
	if stream.Error != nil {
		return
	}

	// Marshal the NoRandomEvents field
	ct.More()
	stream.WriteObjectField("no_random_events")
	stream.WriteVal(s.NoRandomEvents)
	if stream.Error != nil {
		return
	}

	// Marshal the PublicPlayerScores field
	ct.More()
	stream.WriteObjectField("public_player_scores")
	stream.WriteVal(s.PublicPlayerScores)
	if stream.Error != nil {
		return
	}

	// Marshal the RandomSeed field
	if !IsEmpty(s.RandomSeed) {
		ct.More()
		stream.WriteObjectField("random_seed")
		stream.WriteVal(s.RandomSeed)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the SessionId field
	ct.More()
	stream.WriteObjectField("session_id")
	stream.WriteString(s.SessionId)

	// Marshal the SlowerTechAdvances field
	ct.More()
	stream.WriteObjectField("slower_tech_advances")
	stream.WriteVal(s.SlowerTechAdvances)
	if stream.Error != nil {
		return
	}

	// Marshal the StartingDistance field
	ct.More()
	stream.WriteObjectField("starting_distance")
	stream.WriteVal(s.StartingDistance)
	if stream.Error != nil {
		return
	}

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)

	// Marshal the UniverseSize field
	ct.More()
	stream.WriteObjectField("universe_size")
	stream.WriteVal(s.UniverseSize)
	if stream.Error != nil {
		return
	}

	// Marshal the VcAtLeastXYearsMustPassBeforeAWinnerIsDeclared field
	ct.More()
	stream.WriteObjectField("vc_at_least_x_years_must_pass_before_a_winner_is_declared")
	stream.WriteVal(s.VcAtLeastXYearsMustPassBeforeAWinnerIsDeclared)
	if stream.Error != nil {
		return
	}

	// Marshal the VcAttainTechXInYField field
	ct.More()
	stream.WriteObjectField("vc_attain_tech_X_in_Y_field")
	stream.WriteVal(s.VcAttainTechXInYField)
	if stream.Error != nil {
		return
	}

	// Marshal the VcAttainTechXInYFieldFieldsValue field
	if !IsEmpty(s.VcAttainTechXInYFieldFieldsValue) {
		ct.More()
		stream.WriteObjectField("vc_attain_tech_X_in_Y_field_fields_value")
		stream.WriteVal(s.VcAttainTechXInYFieldFieldsValue)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcAttainTechXInYFieldTechValue field
	if !IsEmpty(s.VcAttainTechXInYFieldTechValue) {
		ct.More()
		stream.WriteObjectField("vc_attain_tech_X_in_Y_field_tech_value")
		stream.WriteVal(s.VcAttainTechXInYFieldTechValue)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcExceedNextPlayerScoreByX field
	ct.More()
	stream.WriteObjectField("vc_exceed_next_player_score_by_x")
	stream.WriteVal(s.VcExceedNextPlayerScoreByX)
	if stream.Error != nil {
		return
	}

	// Marshal the VcExceedNextPlayerScoreByXValue field
	if !IsEmpty(s.VcExceedNextPlayerScoreByXValue) {
		ct.More()
		stream.WriteObjectField("vc_exceed_next_player_score_by_x_value")
		stream.WriteVal(s.VcExceedNextPlayerScoreByXValue)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcExceedScoreOfX field
	if !IsEmpty(s.VcExceedScoreOfX) {
		ct.More()
		stream.WriteObjectField("vc_exceed_score_of_x")
		stream.WriteVal(s.VcExceedScoreOfX)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcExceedScoreOfXValue field
	if !IsEmpty(s.VcExceedScoreOfXValue) {
		ct.More()
		stream.WriteObjectField("vc_exceed_score_of_x_value")
		stream.WriteVal(s.VcExceedScoreOfXValue)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcHasProductionCapacityOfXThousand field
	ct.More()
	stream.WriteObjectField("vc_has_production_capacity_of_x_thousand")
	stream.WriteVal(s.VcHasProductionCapacityOfXThousand)
	if stream.Error != nil {
		return
	}

	// Marshal the VcHasProductionCapacityOfXThousandValue field
	if !IsEmpty(s.VcHasProductionCapacityOfXThousandValue) {
		ct.More()
		stream.WriteObjectField("vc_has_production_capacity_of_x_thousand_value")
		stream.WriteVal(s.VcHasProductionCapacityOfXThousandValue)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcHaveHighestScoreAfterXYears field
	ct.More()
	stream.WriteObjectField("vc_have_highest_score_after_x_years")
	stream.WriteVal(s.VcHaveHighestScoreAfterXYears)
	if stream.Error != nil {
		return
	}

	// Marshal the VcHaveHighestScoreAfterXYearsValue field
	if !IsEmpty(s.VcHaveHighestScoreAfterXYearsValue) {
		ct.More()
		stream.WriteObjectField("vc_have_highest_score_after_x_years_value")
		stream.WriteVal(s.VcHaveHighestScoreAfterXYearsValue)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcOwnsXCapitalShips field
	ct.More()
	stream.WriteObjectField("vc_owns_x_capital_ships")
	stream.WriteVal(s.VcOwnsXCapitalShips)
	if stream.Error != nil {
		return
	}

	// Marshal the VcOwnsXCapitalShipsValue field
	if !IsEmpty(s.VcOwnsXCapitalShipsValue) {
		ct.More()
		stream.WriteObjectField("vc_owns_x_capital_ships_value")
		stream.WriteVal(s.VcOwnsXCapitalShipsValue)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcOwnsXPercentOfPlanets field
	ct.More()
	stream.WriteObjectField("vc_owns_x_percent_of_planets")
	stream.WriteVal(s.VcOwnsXPercentOfPlanets)
	if stream.Error != nil {
		return
	}

	// Marshal the VcOwnsXPercentOfPlanetsValue field
	if !IsEmpty(s.VcOwnsXPercentOfPlanetsValue) {
		ct.More()
		stream.WriteObjectField("vc_owns_x_percent_of_planets_value")
		stream.WriteVal(s.VcOwnsXPercentOfPlanetsValue)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the VcWinnerMustMeetXOfTheAbove field
	ct.More()
	stream.WriteObjectField("vc_winner_must_meet_x_of_the_above")
	stream.WriteVal(s.VcWinnerMustMeetXOfTheAbove)
	if stream.Error != nil {
		return
	}
	stream.WriteObjectEnd()
}

func (s *Ruleset) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *Ruleset) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	AcceleratedBbsPlayReceived := false
	ComputerPlayersFormAlliancesReceived := false
	DensityReceived := false
	GalaxyClumpingReceived := false
	IdReceived := false
	MaximumMineralsReceived := false
	NoRandomEventsReceived := false
	PublicPlayerScoresReceived := false
	SessionIdReceived := false
	SlowerTechAdvancesReceived := false
	StartingDistanceReceived := false
	TypeReceived := false
	UniverseSizeReceived := false
	VcAtLeastXYearsMustPassBeforeAWinnerIsDeclaredReceived := false
	VcAttainTechXInYFieldReceived := false
	VcExceedNextPlayerScoreByXReceived := false
	VcHasProductionCapacityOfXThousandReceived := false
	VcHaveHighestScoreAfterXYearsReceived := false
	VcOwnsXCapitalShipsReceived := false
	VcOwnsXPercentOfPlanetsReceived := false
	VcWinnerMustMeetXOfTheAboveReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "accelerated_bbs_play":
			s.AcceleratedBbsPlay = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			AcceleratedBbsPlayReceived = true
		case "computer_players_form_alliances":
			s.ComputerPlayersFormAlliances = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			ComputerPlayersFormAlliancesReceived = true
		case "density":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field density", "density is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Density)
			if iter.Error != nil {
				return
			}
			DensityReceived = true
		case "galaxy_clumping":
			s.GalaxyClumping = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			GalaxyClumpingReceived = true
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "maximum_minerals":
			s.MaximumMinerals = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			MaximumMineralsReceived = true
		case "no_random_events":
			s.NoRandomEvents = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			NoRandomEventsReceived = true
		case "public_player_scores":
			s.PublicPlayerScores = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			PublicPlayerScoresReceived = true
		case "random_seed":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field random_seed", "random_seed is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.RandomSeed)
			if iter.Error != nil {
				return
			}
		case "session_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field session_id", "session_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.SessionId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			SessionIdReceived = true
		case "slower_tech_advances":
			s.SlowerTechAdvances = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			SlowerTechAdvancesReceived = true
		case "starting_distance":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field starting_distance", "starting_distance is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.StartingDistance)
			if iter.Error != nil {
				return
			}
			StartingDistanceReceived = true
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "ruleset" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "ruleset", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		case "universe_size":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field universe_size", "universe_size is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.UniverseSize)
			if iter.Error != nil {
				return
			}
			UniverseSizeReceived = true
		case "vc_at_least_x_years_must_pass_before_a_winner_is_declared":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_at_least_x_years_must_pass_before_a_winner_is_declared", "vc_at_least_x_years_must_pass_before_a_winner_is_declared is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcAtLeastXYearsMustPassBeforeAWinnerIsDeclared)
			if iter.Error != nil {
				return
			}
			VcAtLeastXYearsMustPassBeforeAWinnerIsDeclaredReceived = true
		case "vc_attain_tech_X_in_Y_field":
			s.VcAttainTechXInYField = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			VcAttainTechXInYFieldReceived = true
		case "vc_attain_tech_X_in_Y_field_fields_value":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_attain_tech_X_in_Y_field_fields_value", "vc_attain_tech_X_in_Y_field_fields_value is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcAttainTechXInYFieldFieldsValue)
			if iter.Error != nil {
				return
			}
		case "vc_attain_tech_X_in_Y_field_tech_value":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_attain_tech_X_in_Y_field_tech_value", "vc_attain_tech_X_in_Y_field_tech_value is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcAttainTechXInYFieldTechValue)
			if iter.Error != nil {
				return
			}
		case "vc_exceed_next_player_score_by_x":
			s.VcExceedNextPlayerScoreByX = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			VcExceedNextPlayerScoreByXReceived = true
		case "vc_exceed_next_player_score_by_x_value":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_exceed_next_player_score_by_x_value", "vc_exceed_next_player_score_by_x_value is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcExceedNextPlayerScoreByXValue)
			if iter.Error != nil {
				return
			}
		case "vc_exceed_score_of_x":
			s.VcExceedScoreOfX = iter.ReadBool()
			if iter.Error != nil {
				return
			}
		case "vc_exceed_score_of_x_value":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_exceed_score_of_x_value", "vc_exceed_score_of_x_value is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcExceedScoreOfXValue)
			if iter.Error != nil {
				return
			}
		case "vc_has_production_capacity_of_x_thousand":
			s.VcHasProductionCapacityOfXThousand = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			VcHasProductionCapacityOfXThousandReceived = true
		case "vc_has_production_capacity_of_x_thousand_value":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_has_production_capacity_of_x_thousand_value", "vc_has_production_capacity_of_x_thousand_value is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcHasProductionCapacityOfXThousandValue)
			if iter.Error != nil {
				return
			}
		case "vc_have_highest_score_after_x_years":
			s.VcHaveHighestScoreAfterXYears = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			VcHaveHighestScoreAfterXYearsReceived = true
		case "vc_have_highest_score_after_x_years_value":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_have_highest_score_after_x_years_value", "vc_have_highest_score_after_x_years_value is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcHaveHighestScoreAfterXYearsValue)
			if iter.Error != nil {
				return
			}
		case "vc_owns_x_capital_ships":
			s.VcOwnsXCapitalShips = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			VcOwnsXCapitalShipsReceived = true
		case "vc_owns_x_capital_ships_value":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_owns_x_capital_ships_value", "vc_owns_x_capital_ships_value is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcOwnsXCapitalShipsValue)
			if iter.Error != nil {
				return
			}
		case "vc_owns_x_percent_of_planets":
			s.VcOwnsXPercentOfPlanets = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			VcOwnsXPercentOfPlanetsReceived = true
		case "vc_owns_x_percent_of_planets_value":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_owns_x_percent_of_planets_value", "vc_owns_x_percent_of_planets_value is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcOwnsXPercentOfPlanetsValue)
			if iter.Error != nil {
				return
			}
		case "vc_winner_must_meet_x_of_the_above":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field vc_winner_must_meet_x_of_the_above", "vc_winner_must_meet_x_of_the_above is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.VcWinnerMustMeetXOfTheAbove)
			if iter.Error != nil {
				return
			}
			VcWinnerMustMeetXOfTheAboveReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !AcceleratedBbsPlayReceived {
		iter.ReportError("validating Ruleset", "\"accelerated_bbs_play\" is required but was not present")
	}

	if !ComputerPlayersFormAlliancesReceived {
		iter.ReportError("validating Ruleset", "\"computer_players_form_alliances\" is required but was not present")
	}

	if !DensityReceived {
		iter.ReportError("validating Ruleset", "\"density\" is required but was not present")
	}

	if !GalaxyClumpingReceived {
		iter.ReportError("validating Ruleset", "\"galaxy_clumping\" is required but was not present")
	}

	if !IdReceived {
		iter.ReportError("validating Ruleset", "\"id\" is required but was not present")
	}

	if !MaximumMineralsReceived {
		iter.ReportError("validating Ruleset", "\"maximum_minerals\" is required but was not present")
	}

	if !NoRandomEventsReceived {
		iter.ReportError("validating Ruleset", "\"no_random_events\" is required but was not present")
	}

	if !PublicPlayerScoresReceived {
		iter.ReportError("validating Ruleset", "\"public_player_scores\" is required but was not present")
	}

	if !SessionIdReceived {
		iter.ReportError("validating Ruleset", "\"session_id\" is required but was not present")
	}

	if !SlowerTechAdvancesReceived {
		iter.ReportError("validating Ruleset", "\"slower_tech_advances\" is required but was not present")
	}

	if !StartingDistanceReceived {
		iter.ReportError("validating Ruleset", "\"starting_distance\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating Ruleset", "\"__type__\" is required but was not present")
	}

	if !UniverseSizeReceived {
		iter.ReportError("validating Ruleset", "\"universe_size\" is required but was not present")
	}

	if !VcAtLeastXYearsMustPassBeforeAWinnerIsDeclaredReceived {
		iter.ReportError("validating Ruleset", "\"vc_at_least_x_years_must_pass_before_a_winner_is_declared\" is required but was not present")
	}

	if !VcAttainTechXInYFieldReceived {
		iter.ReportError("validating Ruleset", "\"vc_attain_tech_X_in_Y_field\" is required but was not present")
	}

	if !VcExceedNextPlayerScoreByXReceived {
		iter.ReportError("validating Ruleset", "\"vc_exceed_next_player_score_by_x\" is required but was not present")
	}

	if !VcHasProductionCapacityOfXThousandReceived {
		iter.ReportError("validating Ruleset", "\"vc_has_production_capacity_of_x_thousand\" is required but was not present")
	}

	if !VcHaveHighestScoreAfterXYearsReceived {
		iter.ReportError("validating Ruleset", "\"vc_have_highest_score_after_x_years\" is required but was not present")
	}

	if !VcOwnsXCapitalShipsReceived {
		iter.ReportError("validating Ruleset", "\"vc_owns_x_capital_ships\" is required but was not present")
	}

	if !VcOwnsXPercentOfPlanetsReceived {
		iter.ReportError("validating Ruleset", "\"vc_owns_x_percent_of_planets\" is required but was not present")
	}

	if !VcWinnerMustMeetXOfTheAboveReceived {
		iter.ReportError("validating Ruleset", "\"vc_winner_must_meet_x_of_the_above\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *Session) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s Session) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the Members field
	if !IsEmpty(s.Members) {
		ct.More()
		stream.WriteObjectField("members")
		stream.WriteVal(s.Members)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Name field
	ct.More()
	stream.WriteObjectField("name")
	stream.WriteString(s.Name)

	// Marshal the Private field
	if !IsEmpty(s.Private) {
		ct.More()
		stream.WriteObjectField("private")
		stream.WriteVal(s.Private)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the RulesIsSet field
	if !IsEmpty(s.RulesIsSet) {
		ct.More()
		stream.WriteObjectField("rules_is_set")
		stream.WriteVal(s.RulesIsSet)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Started field
	if !IsEmpty(s.Started) {
		ct.More()
		stream.WriteObjectField("started")
		stream.WriteVal(s.Started)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)
	stream.WriteObjectEnd()
}

func (s *Session) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *Session) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	IdReceived := false
	NameReceived := false
	TypeReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "members":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field members", "members is 'true', but the expected type is []*UserProfileSessionRel")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Members)
			if iter.Error != nil {
				return
			}
		case "name":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field name", "name is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Name = iter.ReadString()
			if iter.Error != nil {
				return
			}
			NameReceived = true
		case "private":
			s.Private = iter.ReadBool()
			if iter.Error != nil {
				return
			}
		case "rules_is_set":
			s.RulesIsSet = iter.ReadBool()
			if iter.Error != nil {
				return
			}
		case "started":
			s.Started = iter.ReadBool()
			if iter.Error != nil {
				return
			}
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "session" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "session", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !IdReceived {
		iter.ReportError("validating Session", "\"id\" is required but was not present")
	}

	if !NameReceived {
		iter.ReportError("validating Session", "\"name\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating Session", "\"__type__\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *SessionFiles) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s SessionFiles) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the Hostfile field
	ct.More()
	stream.WriteObjectField("hostfile")
	stream.WriteString(s.Hostfile)

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the Orders field
	ct.More()
	stream.WriteObjectField("orders")
	stream.WriteVal(s.Orders)
	if stream.Error != nil {
		return
	}

	// Marshal the SessionId field
	ct.More()
	stream.WriteObjectField("session_id")
	stream.WriteString(s.SessionId)

	// Marshal the Turns field
	ct.More()
	stream.WriteObjectField("turns")
	stream.WriteVal(s.Turns)
	if stream.Error != nil {
		return
	}

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)

	// Marshal the Universe field
	ct.More()
	stream.WriteObjectField("universe")
	stream.WriteString(s.Universe)

	// Marshal the Year field
	ct.More()
	stream.WriteObjectField("year")
	stream.WriteVal(s.Year)
	if stream.Error != nil {
		return
	}
	stream.WriteObjectEnd()
}

func (s *SessionFiles) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *SessionFiles) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	HostfileReceived := false
	IdReceived := false
	OrdersReceived := false
	SessionIdReceived := false
	TurnsReceived := false
	TypeReceived := false
	UniverseReceived := false
	YearReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "hostfile":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field hostfile", "hostfile is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Hostfile = iter.ReadString()
			if iter.Error != nil {
				return
			}
			HostfileReceived = true
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "orders":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field orders", "orders is 'true', but the expected type is []*Order")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Orders)
			if iter.Error != nil {
				return
			}
			OrdersReceived = true
		case "session_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field session_id", "session_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.SessionId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			SessionIdReceived = true
		case "turns":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field turns", "turns is 'true', but the expected type is []*Turn")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Turns)
			if iter.Error != nil {
				return
			}
			TurnsReceived = true
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "session_files" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "session_files", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		case "universe":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field universe", "universe is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Universe = iter.ReadString()
			if iter.Error != nil {
				return
			}
			UniverseReceived = true
		case "year":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field year", "year is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.Year)
			if iter.Error != nil {
				return
			}
			YearReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !HostfileReceived {
		iter.ReportError("validating SessionFiles", "\"hostfile\" is required but was not present")
	}

	if !IdReceived {
		iter.ReportError("validating SessionFiles", "\"id\" is required but was not present")
	}

	if !OrdersReceived {
		iter.ReportError("validating SessionFiles", "\"orders\" is required but was not present")
	}

	if !SessionIdReceived {
		iter.ReportError("validating SessionFiles", "\"session_id\" is required but was not present")
	}

	if !TurnsReceived {
		iter.ReportError("validating SessionFiles", "\"turns\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating SessionFiles", "\"__type__\" is required but was not present")
	}

	if !UniverseReceived {
		iter.ReportError("validating SessionFiles", "\"universe\" is required but was not present")
	}

	if !YearReceived {
		iter.ReportError("validating SessionFiles", "\"year\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *SessionPlayerRace) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s SessionPlayerRace) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the BotLevel field
	if !IsEmpty(s.BotLevel) {
		ct.More()
		stream.WriteObjectField("bot_level")
		stream.WriteVal(s.BotLevel)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the IsBot field
	ct.More()
	stream.WriteObjectField("is_bot")
	stream.WriteVal(s.IsBot)
	if stream.Error != nil {
		return
	}

	// Marshal the PlayerOrder field
	ct.More()
	stream.WriteObjectField("player_order")
	stream.WriteVal(s.PlayerOrder)
	if stream.Error != nil {
		return
	}

	// Marshal the RaceId field
	ct.More()
	stream.WriteObjectField("race_id")
	stream.WriteString(s.RaceId)

	// Marshal the Ready field
	if !IsEmpty(s.Ready) {
		ct.More()
		stream.WriteObjectField("ready")
		stream.WriteVal(s.Ready)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the SessionId field
	ct.More()
	stream.WriteObjectField("session_id")
	stream.WriteString(s.SessionId)

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)

	// Marshal the UserProfileId field
	ct.More()
	stream.WriteObjectField("user_profile_id")
	stream.WriteString(s.UserProfileId)
	stream.WriteObjectEnd()
}

func (s *SessionPlayerRace) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *SessionPlayerRace) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	IdReceived := false
	IsBotReceived := false
	PlayerOrderReceived := false
	RaceIdReceived := false
	SessionIdReceived := false
	TypeReceived := false
	UserProfileIdReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "bot_level":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field bot_level", "bot_level is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.BotLevel)
			if iter.Error != nil {
				return
			}
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "is_bot":
			s.IsBot = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			IsBotReceived = true
		case "player_order":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field player_order", "player_order is 'true', but the expected type is int")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.PlayerOrder)
			if iter.Error != nil {
				return
			}
			PlayerOrderReceived = true
		case "race_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field race_id", "race_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.RaceId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			RaceIdReceived = true
		case "ready":
			s.Ready = iter.ReadBool()
			if iter.Error != nil {
				return
			}
		case "session_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field session_id", "session_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.SessionId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			SessionIdReceived = true
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "session_player_race" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "session_player_race", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		case "user_profile_id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field user_profile_id", "user_profile_id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.UserProfileId = iter.ReadString()
			if iter.Error != nil {
				return
			}
			UserProfileIdReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !IdReceived {
		iter.ReportError("validating SessionPlayerRace", "\"id\" is required but was not present")
	}

	if !IsBotReceived {
		iter.ReportError("validating SessionPlayerRace", "\"is_bot\" is required but was not present")
	}

	if !PlayerOrderReceived {
		iter.ReportError("validating SessionPlayerRace", "\"player_order\" is required but was not present")
	}

	if !RaceIdReceived {
		iter.ReportError("validating SessionPlayerRace", "\"race_id\" is required but was not present")
	}

	if !SessionIdReceived {
		iter.ReportError("validating SessionPlayerRace", "\"session_id\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating SessionPlayerRace", "\"__type__\" is required but was not present")
	}

	if !UserProfileIdReceived {
		iter.ReportError("validating SessionPlayerRace", "\"user_profile_id\" is required but was not present")
	}
}

// MarshalJSON serializes to JSON
func (s *UserProfile) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	stream := jsoniter.ConfigDefault.BorrowStream(buf)
	s.MarshalJSONStream(stream)
	stream.Flush()
	err := stream.Error
	jsoniter.ConfigDefault.ReturnStream(stream)

	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (s UserProfile) MarshalJSONStream(stream *jsoniter.Stream) {
	stream.WriteObjectStart()
	ct := commaTracker{stream: stream}

	// Marshal the ApiKey field
	if !IsEmpty(s.ApiKey) {
		ct.More()
		stream.WriteObjectField("api_key")
		stream.WriteString(s.ApiKey)
	}

	// Marshal the Email field
	ct.More()
	stream.WriteObjectField("email")
	stream.WriteString(s.Email)

	// Marshal the Id field
	ct.More()
	stream.WriteObjectField("id")
	stream.WriteString(s.Id)

	// Marshal the IsActive field
	ct.More()
	stream.WriteObjectField("is_active")
	stream.WriteVal(s.IsActive)
	if stream.Error != nil {
		return
	}

	// Marshal the IsManager field
	if !IsEmpty(s.IsManager) {
		ct.More()
		stream.WriteObjectField("is_manager")
		stream.WriteVal(s.IsManager)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Nickname field
	if !IsEmpty(s.Nickname) {
		ct.More()
		stream.WriteObjectField("nickname")
		stream.WriteString(s.Nickname)
	}

	// Marshal the SessionList field
	if !IsEmpty(s.SessionList) {
		ct.More()
		stream.WriteObjectField("session_list")
		stream.WriteVal(s.SessionList)
		if stream.Error != nil {
			return
		}
	}

	// Marshal the Type field
	ct.More()
	stream.WriteObjectField("__type__")
	stream.WriteString(s.Type)
	stream.WriteObjectEnd()
}

func (s *UserProfile) UnmarshalJSON(data []byte) error {
	iter := jsoniter.ConfigDefault.BorrowIterator(data)
	s.UnmarshalJSONIterator(iter)
	err := iter.Error
	jsoniter.ConfigDefault.ReturnIterator(iter)
	return err
}

func (s *UserProfile) UnmarshalJSONIterator(iter *jsoniter.Iterator) {
	EmailReceived := false
	IdReceived := false
	IsActiveReceived := false
	TypeReceived := false

	for field := iter.ReadObject(); field != ""; field = iter.ReadObject() {
		switch field {
		case "api_key":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field api_key", "api_key is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.ApiKey = iter.ReadString()
			if iter.Error != nil {
				return
			}
		case "email":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field email", "email is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Email = iter.ReadString()
			if iter.Error != nil {
				return
			}
			EmailReceived = true
		case "id":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field id", "id is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Id = iter.ReadString()
			if iter.Error != nil {
				return
			}
			IdReceived = true
		case "is_active":
			s.IsActive = iter.ReadBool()
			if iter.Error != nil {
				return
			}
			IsActiveReceived = true
		case "is_manager":
			s.IsManager = iter.ReadBool()
			if iter.Error != nil {
				return
			}
		case "nickname":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field nickname", "nickname is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Nickname = iter.ReadString()
			if iter.Error != nil {
				return
			}
		case "session_list":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field session_list", "session_list is 'true', but the expected type is []*UserProfileSessionRel")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			iter.ReadVal(&s.SessionList)
			if iter.Error != nil {
				return
			}
		case "__type__":
			if iter.WhatIsNext() == jsoniter.BoolValue {
				if iter.ReadBool() {
					iter.ReportError("reading field __type__", "__type__ is 'true', but the expected type is string")
					return
				}
				// received 'false', which we accept and ignore for now
			}
			s.Type = iter.ReadString()
			if s.Type != "user_profile" {
				iter.ReportError(
					"__type__",
					fmt.Sprintf("Expected %s, got \"%s\"", "user_profile", s.Type),
				)
			}
			if iter.Error != nil {
				return
			}
			TypeReceived = true
		default:
			// Ignore the additional property
			iter.Skip()
		}
	}

	if !EmailReceived {
		iter.ReportError("validating UserProfile", "\"email\" is required but was not present")
	}

	if !IdReceived {
		iter.ReportError("validating UserProfile", "\"id\" is required but was not present")
	}

	if !IsActiveReceived {
		iter.ReportError("validating UserProfile", "\"is_active\" is required but was not present")
	}

	if !TypeReceived {
		iter.ReportError("validating UserProfile", "\"__type__\" is required but was not present")
	}
}
