// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApikeyReset Response containing the new API key after reset
//
// swagger:model apikeyReset
type ApikeyReset struct {

	// The new API key
	Apikey string `json:"apikey,omitempty"`

	// The user profile ID
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this apikey reset
func (m *ApikeyReset) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apikey reset based on context it is used
func (m *ApikeyReset) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApikeyReset) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApikeyReset) UnmarshalBinary(b []byte) error {
	var res ApikeyReset
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
