// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlayerControlStatus Control status for a player in a session.
// Shows whether the player is human or AI controlled, and the AI type if applicable.
//
//
// swagger:model playerControlStatus
type PlayerControlStatus struct {

	// The AI expert type if this player is AI-controlled.
	// NULL means human controlled.
	// Valid values: HE, SS, IS, CA, PP, AR
	//
	// Enum: [HE SS IS CA PP AR]
	AiControlType *string `json:"ai_control_type,omitempty"`

	// Current control status: "human" or "ai"
	//
	// Enum: [human ai]
	ControlStatus string `json:"control_status,omitempty"`

	// Whether this player was originally created as a bot slot.
	// This tracks the initial player type, not the current control status.
	//
	IsBot bool `json:"is_bot,omitempty"`

	// The player's nickname
	Nickname string `json:"nickname,omitempty"`

	// The player order number (0-15)
	// Maximum: 15
	// Minimum: 0
	PlayerOrder int64 `json:"player_order,omitempty"`

	// The user profile ID associated with this player slot
	UserProfileID string `json:"user_profile_id,omitempty"`
}

// Validate validates this player control status
func (m *PlayerControlStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAiControlType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateControlStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlayerOrder(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var playerControlStatusTypeAiControlTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["HE","SS","IS","CA","PP","AR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		playerControlStatusTypeAiControlTypePropEnum = append(playerControlStatusTypeAiControlTypePropEnum, v)
	}
}

const (

	// PlayerControlStatusAiControlTypeHE captures enum value "HE"
	PlayerControlStatusAiControlTypeHE string = "HE"

	// PlayerControlStatusAiControlTypeSS captures enum value "SS"
	PlayerControlStatusAiControlTypeSS string = "SS"

	// PlayerControlStatusAiControlTypeIS captures enum value "IS"
	PlayerControlStatusAiControlTypeIS string = "IS"

	// PlayerControlStatusAiControlTypeCA captures enum value "CA"
	PlayerControlStatusAiControlTypeCA string = "CA"

	// PlayerControlStatusAiControlTypePP captures enum value "PP"
	PlayerControlStatusAiControlTypePP string = "PP"

	// PlayerControlStatusAiControlTypeAR captures enum value "AR"
	PlayerControlStatusAiControlTypeAR string = "AR"
)

// prop value enum
func (m *PlayerControlStatus) validateAiControlTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, playerControlStatusTypeAiControlTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PlayerControlStatus) validateAiControlType(formats strfmt.Registry) error {
	if swag.IsZero(m.AiControlType) { // not required
		return nil
	}

	// value enum
	if err := m.validateAiControlTypeEnum("ai_control_type", "body", *m.AiControlType); err != nil {
		return err
	}

	return nil
}

var playerControlStatusTypeControlStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["human","ai"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		playerControlStatusTypeControlStatusPropEnum = append(playerControlStatusTypeControlStatusPropEnum, v)
	}
}

const (

	// PlayerControlStatusControlStatusHuman captures enum value "human"
	PlayerControlStatusControlStatusHuman string = "human"

	// PlayerControlStatusControlStatusAi captures enum value "ai"
	PlayerControlStatusControlStatusAi string = "ai"
)

// prop value enum
func (m *PlayerControlStatus) validateControlStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, playerControlStatusTypeControlStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PlayerControlStatus) validateControlStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.ControlStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateControlStatusEnum("control_status", "body", m.ControlStatus); err != nil {
		return err
	}

	return nil
}

func (m *PlayerControlStatus) validatePlayerOrder(formats strfmt.Registry) error {
	if swag.IsZero(m.PlayerOrder) { // not required
		return nil
	}

	if err := validate.MinimumInt("player_order", "body", m.PlayerOrder, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("player_order", "body", m.PlayerOrder, 15, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this player control status based on context it is used
func (m *PlayerControlStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlayerControlStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlayerControlStatus) UnmarshalBinary(b []byte) error {
	var res PlayerControlStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
