// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlayerOrderStatus Order submission status for a player
//
// swagger:model playerOrderStatus
type PlayerOrderStatus struct {

	// True if this is a bot player
	IsBot bool `json:"is_bot,omitempty"`

	// Player nickname
	Nickname string `json:"nickname,omitempty"`

	// The player order number (0-15)
	PlayerOrder int64 `json:"player_order,omitempty"`

	// True if orders have been submitted for this turn
	Submitted bool `json:"submitted,omitempty"`
}

// Validate validates this player order status
func (m *PlayerOrderStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this player order status based on context it is used
func (m *PlayerOrderStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlayerOrderStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlayerOrderStatus) UnmarshalBinary(b []byte) error {
	var res PlayerOrderStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
