// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RegistrationRequest Request body for user registration
//
// swagger:model registrationRequest
type RegistrationRequest struct {

	// user email address (must be unique)
	// Required: true
	Email string `json:"email"`

	// optional message explaining why you want to join
	Message *string `json:"message,omitempty"`

	// requested user nickname (must be unique)
	// Required: true
	Nickname string `json:"nickname"`
}

// Validate validates this registration request
func (m *RegistrationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNickname(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegistrationRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.RequiredString("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

func (m *RegistrationRequest) validateNickname(formats strfmt.Registry) error {

	if err := validate.RequiredString("nickname", "body", m.Nickname); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this registration request based on context it is used
func (m *RegistrationRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegistrationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistrationRequest) UnmarshalBinary(b []byte) error {
	var res RegistrationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
