// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SessionPlayer Information about a player in a session
//
// swagger:model sessionPlayer
type SessionPlayer struct {

	// The order number for this player in the game.
	// As there can be a maximum of 16 players in a Stars! game, the value range is limited between 0 and 15
	//
	// Maximum: 15
	// Minimum: 0
	PlayerOrder int64 `json:"player_order,omitempty"`

	// whether the player has marked their race as ready
	Ready bool `json:"ready,omitempty"`

	// the user profile id of the player
	UserProfileID string `json:"user_profile_id,omitempty"`
}

// Validate validates this session player
func (m *SessionPlayer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlayerOrder(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SessionPlayer) validatePlayerOrder(formats strfmt.Registry) error {
	if swag.IsZero(m.PlayerOrder) { // not required
		return nil
	}

	if err := validate.MinimumInt("player_order", "body", m.PlayerOrder, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("player_order", "body", m.PlayerOrder, 15, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this session player based on context it is used
func (m *SessionPlayer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SessionPlayer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SessionPlayer) UnmarshalBinary(b []byte) error {
	var res SessionPlayer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
