// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SessionPlayerRace a binding between a player race and a session. The host can also choose the player order.
//
// swagger:model sessionPlayerRace
type SessionPlayerRace struct {

	// if the player is a bot, the host can set a level with this field:
	//   0=Random
	//   1=Easy
	//   2=Standard
	//   3=Tough
	//   4=Expert
	//
	// Maximum: 4
	// Minimum: 0
	BotLevel *int64 `json:"bot_level,omitempty" db:"bot_level"`

	// id of this mapping
	// Read Only: true
	ID string `json:"id,omitempty" db:"id"`

	// if this player race should be player by a bot.
	// If this value is true then you need to provide the bot_level.
	// If this value is false any value given in the bot_level will be ignored
	//
	IsBot bool `json:"is_bot,omitempty"`

	// The order number for this player. Only the host can set this value.
	// As there can be a maximum of 16 players in a Stars! game, the value range is limited between 0 and 15
	//
	// Maximum: 15
	// Minimum: 0
	PlayerOrder int64 `json:"player_order,omitempty" db:"player_order"`

	// the race ID you will use during this session
	// For a normal player you must use the ID of a race file you previously uploaded
	// in your user profile.
	//
	// If the host is adding a bot player here is the list of race ids to chose from:
	//   "0"=Random
	//   "1"=Robotoids
	//   "2"=Turndrones
	//   "3"=Automitrons
	//   "4"=Rototills
	//   "5"=Cybertrons
	//   "6"=Mcinti
	//
	RaceID string `json:"race_id,omitempty" db:"race_id"`

	// the session id on which this race will be used. This value is automatically set by the server.
	// Read Only: true
	SessionID string `json:"session_id,omitempty" db:"session_id"`

	// the user profile is automatically set if you are a simple player. Only hosts can set this value to something different
	// Read Only: true
	UserProfileID string `json:"user_profile_id,omitempty" db:"user_profile_id"`
}

// Validate validates this session player race
func (m *SessionPlayerRace) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBotLevel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlayerOrder(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SessionPlayerRace) validateBotLevel(formats strfmt.Registry) error {
	if swag.IsZero(m.BotLevel) { // not required
		return nil
	}

	if err := validate.MinimumInt("bot_level", "body", *m.BotLevel, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("bot_level", "body", *m.BotLevel, 4, false); err != nil {
		return err
	}

	return nil
}

func (m *SessionPlayerRace) validatePlayerOrder(formats strfmt.Registry) error {
	if swag.IsZero(m.PlayerOrder) { // not required
		return nil
	}

	if err := validate.MinimumInt("player_order", "body", m.PlayerOrder, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("player_order", "body", m.PlayerOrder, 15, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this session player race based on the context it is used
func (m *SessionPlayerRace) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSessionID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserProfileID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SessionPlayerRace) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *SessionPlayerRace) contextValidateSessionID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "session_id", "body", string(m.SessionID)); err != nil {
		return err
	}

	return nil
}

func (m *SessionPlayerRace) contextValidateUserProfileID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "user_profile_id", "body", string(m.UserProfileID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SessionPlayerRace) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SessionPlayerRace) UnmarshalBinary(b []byte) error {
	var res SessionPlayerRace
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
